<?php

namespace Google\AdsApi\AdWords\v201802\o;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class TargetingIdeaErrorReason
{
    const DUPLICATE_SEARCH_FILTER_TYPES_PRESENT = 'DUPLICATE_SEARCH_FILTER_TYPES_PRESENT';
    const INSUFFICIENT_SEARCH_PARAMETERS = 'INSUFFICIENT_SEARCH_PARAMETERS';
    const INVALID_ATTRIBUTE_TYPE = 'INVALID_ATTRIBUTE_TYPE';
    const INVALID_SEARCH_PARAMETERS = 'INVALID_SEARCH_PARAMETERS';
    const INVALID_DOMAIN_SUFFIX = 'INVALID_DOMAIN_SUFFIX';
    const MUTUALLY_EXCLUSIVE_SEARCH_PARAMETERS_IN_QUERY = 'MUTUALLY_EXCLUSIVE_SEARCH_PARAMETERS_IN_QUERY';
    const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    const INVALID_URL_IN_SEARCH_PARAMETER = 'INVALID_URL_IN_SEARCH_PARAMETER';
    const TOO_MANY_RESULTS_REQUESTED = 'TOO_MANY_RESULTS_REQUESTED';
    const NO_PAGING_IN_SELECTOR = 'NO_PAGING_IN_SELECTOR';
    const INVALID_INCLUDED_EXCLUDED_KEYWORDS = 'INVALID_INCLUDED_EXCLUDED_KEYWORDS';


}
