<?php

namespace Google\AdsApi\AdManager\v202405;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class EntityLimitReachedErrorReason
{
    const CUSTOM_TARGETING_VALUES_LIMIT_REACHED = 'CUSTOM_TARGETING_VALUES_LIMIT_REACHED';
    const AD_EXCLUSION_RULES_LIMIT_REACHED = 'AD_EXCLUSION_RULES_LIMIT_REACHED';
    const FIRST_PARTY_AUDIENCE_SEGMENTS_LIMIT_REACHED = 'FIRST_PARTY_AUDIENCE_SEGMENTS_LIMIT_REACHED';
    const PLACEMENTS_LIMIT_REACHED = 'PLACEMENTS_LIMIT_REACHED';
    const LINE_ITEMS_LIMIT_REACHED = 'LINE_ITEMS_LIMIT_REACHED';
    const ACTIVE_LINE_ITEMS_LIMIT_REACHED = 'ACTIVE_LINE_ITEMS_LIMIT_REACHED';
    const DAI_ENCODING_PROFILES_LIMIT_REACHED = 'DAI_ENCODING_PROFILES_LIMIT_REACHED';
    const TRAFFIC_FORECAST_SEGMENTS_LIMIT_REACHED = 'TRAFFIC_FORECAST_SEGMENTS_LIMIT_REACHED';
    const FORECAST_ADJUSTMENTS_LIMIT_REACHED = 'FORECAST_ADJUSTMENTS_LIMIT_REACHED';
    const ACTIVE_EXPERIMENTS_LIMIT_REACHED = 'ACTIVE_EXPERIMENTS_LIMIT_REACHED';
    const SITES_LIMIT_REACHED = 'SITES_LIMIT_REACHED';
    const USER_TEAMS_LIMIT_REACHED = 'USER_TEAMS_LIMIT_REACHED';
    const UNKNOWN = 'UNKNOWN';


}
