<?php

namespace Google\AdsApi\AdManager\v202405;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class McmErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const DUPLICATE_CHILD_PUBLISHER_NETWORK_CODE = 'DUPLICATE_CHILD_PUBLISHER_NETWORK_CODE';
    const DUPLICATE_CHILD_PUBLISHER_ACTIVE_EMAIL = 'DUPLICATE_CHILD_PUBLISHER_ACTIVE_EMAIL';


}
