<?php

namespace Google\AdsApi\Dfp\v201705;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ClickTrackingLineItemErrorReason
{
    const TYPE_IMMUTABLE = 'TYPE_IMMUTABLE';
    const INVALID_TARGETING_TYPE = 'INVALID_TARGETING_TYPE';
    const INVALID_ROADBLOCKING_TYPE = 'INVALID_ROADBLOCKING_TYPE';
    const INVALID_CREATIVEROTATION_TYPE = 'INVALID_CREATIVEROTATION_TYPE';
    const INVALID_DELIVERY_RATE_TYPE = 'INVALID_DELIVERY_RATE_TYPE';
    const UNSUPPORTED_FIELD = 'UNSUPPORTED_FIELD';
    const UNKNOWN = 'UNKNOWN';


}
