<?php

namespace Google\AdsApi\Dfp\v201705;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ConversionEvent
{
    const UNKNOWN = 'UNKNOWN';
    const CREATIVE_VIEW = 'CREATIVE_VIEW';
    const START = 'START';
    const SKIP_SHOWN = 'SKIP_SHOWN';
    const FIRST_QUARTILE = 'FIRST_QUARTILE';
    const MIDPOINT = 'MIDPOINT';
    const THIRD_QUARTILE = 'THIRD_QUARTILE';
    const ENGAGED_VIEW = 'ENGAGED_VIEW';
    const COMPLETE = 'COMPLETE';
    const MUTE = 'MUTE';
    const UNMUTE = 'UNMUTE';
    const PAUSE = 'PAUSE';
    const REWIND = 'REWIND';
    const RESUME = 'RESUME';
    const SKIPPED = 'SKIPPED';
    const FULLSCREEN = 'FULLSCREEN';
    const EXPAND = 'EXPAND';
    const COLLAPSE = 'COLLAPSE';
    const ACCEPT_INVITATION = 'ACCEPT_INVITATION';
    const CLOSE = 'CLOSE';
    const CLICK_TRACKING = 'CLICK_TRACKING';
    const SURVEY = 'SURVEY';
    const CUSTOM_CLICK = 'CUSTOM_CLICK';
    const MEASURABLE_IMPRESSION = 'MEASURABLE_IMPRESSION';
    const VIEWABLE_IMPRESSION = 'VIEWABLE_IMPRESSION';
    const VIDEO_ABANDON = 'VIDEO_ABANDON';
    const FULLY_VIEWABLE_AUDIBLE_HALF_DURATION_IMPRESSION = 'FULLY_VIEWABLE_AUDIBLE_HALF_DURATION_IMPRESSION';


}
