<?php

namespace Google\AdsApi\Dfp\v201705;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ReportErrorReason
{
    const DEFAULT_VALUE = 'DEFAULT';
    const REPORT_ACCESS_NOT_ALLOWED = 'REPORT_ACCESS_NOT_ALLOWED';
    const DIMENSION_VIEW_NOT_ALLOWED = 'DIMENSION_VIEW_NOT_ALLOWED';
    const ATTRIBUTE_VIEW_NOT_ALLOWED = 'ATTRIBUTE_VIEW_NOT_ALLOWED';
    const COLUMN_VIEW_NOT_ALLOWED = 'COLUMN_VIEW_NOT_ALLOWED';
    const TOO_MANY_CONCURRENT_REPORTS = 'TOO_MANY_CONCURRENT_REPORTS';
    const REPORT_QUERY_TOO_LONG = 'REPORT_QUERY_TOO_LONG';
    const INVALID_OPERATION_FOR_REPORT_STATE = 'INVALID_OPERATION_FOR_REPORT_STATE';
    const INVALID_DIMENSIONS = 'INVALID_DIMENSIONS';
    const INVALID_ATTRIBUTES = 'INVALID_ATTRIBUTES';
    const INVALID_CONTENT_HIERARCHY_DIMENSIONS = 'INVALID_CONTENT_HIERARCHY_DIMENSIONS';
    const INVALID_COLUMNS = 'INVALID_COLUMNS';
    const INVALID_DIMENSION_FILTERS = 'INVALID_DIMENSION_FILTERS';
    const INVALID_DATE = 'INVALID_DATE';
    const END_DATE_TIME_NOT_AFTER_START_TIME = 'END_DATE_TIME_NOT_AFTER_START_TIME';
    const START_DATE_MORE_THAN_THREE_YEARS_AGO = 'START_DATE_MORE_THAN_THREE_YEARS_AGO';
    const NOT_NULL = 'NOT_NULL';
    const ATTRIBUTES_NOT_SUPPORTED_FOR_REQUEST = 'ATTRIBUTES_NOT_SUPPORTED_FOR_REQUEST';
    const COLUMNS_NOT_SUPPORTED_FOR_REQUESTED_DIMENSIONS = 'COLUMNS_NOT_SUPPORTED_FOR_REQUESTED_DIMENSIONS';
    const FAILED_TO_STORE_REPORT = 'FAILED_TO_STORE_REPORT';
    const REPORT_NOT_FOUND = 'REPORT_NOT_FOUND';
    const SR_CANNOT_RUN_REPORT_IN_ANOTHER_NETWORK = 'SR_CANNOT_RUN_REPORT_IN_ANOTHER_NETWORK';
    const UNKNOWN = 'UNKNOWN';


}
