<?php

namespace Google\AdsApi\Dfp\v201705;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class TargetingDimension
{
    const CUSTOM_CRITERIA = 'CUSTOM_CRITERIA';
    const GEOGRAPHY = 'GEOGRAPHY';
    const BROWSER = 'BROWSER';
    const BROWSER_LANGUAGE = 'BROWSER_LANGUAGE';
    const BANDWIDTH_GROUP = 'BANDWIDTH_GROUP';
    const OPERATING_SYSTEM = 'OPERATING_SYSTEM';
    const USER_DOMAIN = 'USER_DOMAIN';
    const CONTENT = 'CONTENT';
    const VIDEO_POSITION = 'VIDEO_POSITION';
    const AD_SIZE = 'AD_SIZE';
    const AD_UNIT = 'AD_UNIT';
    const PLACEMENT = 'PLACEMENT';
    const MOBILE_CARRIER = 'MOBILE_CARRIER';
    const DEVICE_CAPABILITY = 'DEVICE_CAPABILITY';
    const DEVICE_CATEGORY = 'DEVICE_CATEGORY';
    const DEVICE_MANUFACTURER = 'DEVICE_MANUFACTURER';
    const MOBILE_APPLICATION = 'MOBILE_APPLICATION';
    const UNKNOWN = 'UNKNOWN';


}
