<?php

namespace Google\AdsApi\AdManager\v202311;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class MobileApplicationErrorReason
{
    const INVALID_APP_ID = 'INVALID_APP_ID';
    const INVALID_EXCHANGE_PARTNER_SETTINGS = 'INVALID_EXCHANGE_PARTNER_SETTINGS';
    const INTERNAL = 'INTERNAL';
    const NAME_OR_STORE_ID_MUST_BE_SET = 'NAME_OR_STORE_ID_MUST_BE_SET';
    const PUBLISHER_HAS_TOO_MANY_ACTIVE_APPS = 'PUBLISHER_HAS_TOO_MANY_ACTIVE_APPS';
    const LINKED_APPLICATION_STORE_ID_TOO_LONG = 'LINKED_APPLICATION_STORE_ID_TOO_LONG';
    const MANUAL_APP_NAME_TOO_LONG = 'MANUAL_APP_NAME_TOO_LONG';
    const MANUAL_APP_NAME_EMPTY = 'MANUAL_APP_NAME_EMPTY';
    const INVALID_COMBINED_PRODUCT_KEY = 'INVALID_COMBINED_PRODUCT_KEY';
    const LINKED_APP_SKIPPING_ID_VERIFICATION_MUST_BE_ANDROID_APP = 'LINKED_APP_SKIPPING_ID_VERIFICATION_MUST_BE_ANDROID_APP';
    const MISSING_APP_STORE_ENTRY = 'MISSING_APP_STORE_ENTRY';
    const CANNOT_SET_STORE_ID_MISSING_STORE_ENTRY = 'CANNOT_SET_STORE_ID_MISSING_STORE_ENTRY';
    const CANNOT_SET_STORE_ID_INVALID_APP_STORE = 'CANNOT_SET_STORE_ID_INVALID_APP_STORE';
    const CANNOT_SET_STORE_ID_INVALID_STORE_ID = 'CANNOT_SET_STORE_ID_INVALID_STORE_ID';
    const CANNOT_SET_STORE_ID_NON_UNIQUE_STORE_ID = 'CANNOT_SET_STORE_ID_NON_UNIQUE_STORE_ID';
    const CANNOT_SET_STORE_ID_NON_UNIQUE_STORE_ID_WITHIN_PLATFORM = 'CANNOT_SET_STORE_ID_NON_UNIQUE_STORE_ID_WITHIN_PLATFORM';
    const CANNOT_SET_STORE_ID_INVALID_ANDROID_PACKAGE_NAME = 'CANNOT_SET_STORE_ID_INVALID_ANDROID_PACKAGE_NAME';
    const INCOMPATIBLE_APP_STORE_LIST = 'INCOMPATIBLE_APP_STORE_LIST';
    const APP_STORE_LIST_CANNOT_HAVE_UNKNOWN_APP_STORE = 'APP_STORE_LIST_CANNOT_HAVE_UNKNOWN_APP_STORE';
    const APP_STORE_LIST_CANNOT_REMOVE_FIRST_PARTY_APP_STORE = 'APP_STORE_LIST_CANNOT_REMOVE_FIRST_PARTY_APP_STORE';
    const UNKNOWN = 'UNKNOWN';


}
