<?php

namespace Google\AdsApi\AdManager\v202511;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class GrpSettingsErrorReason
{
    const INVALID_AGE_RANGE = 'INVALID_AGE_RANGE';
    const UNDER_18_MIN_AGE_REQUIRES_ALL_AGES = 'UNDER_18_MIN_AGE_REQUIRES_ALL_AGES';
    const LINE_ITEM_ENVIRONMENT_TYPE_NOT_SUPPORTED = 'LINE_ITEM_ENVIRONMENT_TYPE_NOT_SUPPORTED';
    const NIELSEN_DAR_REQUIRES_INSTREAM_VIDEO = 'NIELSEN_DAR_REQUIRES_INSTREAM_VIDEO';
    const LINE_ITEM_TYPE_NOT_SUPPORTED = 'LINE_ITEM_TYPE_NOT_SUPPORTED';
    const CANNOT_SPECIFY_GENDER_FOR_GIVEN_AGE_RANGE = 'CANNOT_SPECIFY_GENDER_FOR_GIVEN_AGE_RANGE';
    const INVALID_MIN_AGE = 'INVALID_MIN_AGE';
    const INVALID_MAX_AGE = 'INVALID_MAX_AGE';
    const CANNOT_DISABLE_GRP_AFTER_ENABLING = 'CANNOT_DISABLE_GRP_AFTER_ENABLING';
    const CANNOT_CHANGE_GRP_PROVIDERS = 'CANNOT_CHANGE_GRP_PROVIDERS';
    const CANNOT_CHANGE_GRP_SETTINGS = 'CANNOT_CHANGE_GRP_SETTINGS';
    const GRP_AUDIENCE_GOAL_NOT_SUPPORTED = 'GRP_AUDIENCE_GOAL_NOT_SUPPORTED';
    const DEMOG_GOAL_EXPECTED = 'DEMOG_GOAL_EXPECTED';
    const CANNOT_SET_GRP_AUDIENCE_GOAL = 'CANNOT_SET_GRP_AUDIENCE_GOAL';
    const CANNOT_REMOVE_GRP_AUDIENCE_GOAL = 'CANNOT_REMOVE_GRP_AUDIENCE_GOAL';
    const UNSUPPORTED_GEO_TARGETING = 'UNSUPPORTED_GEO_TARGETING';
    const UNSUPPORTED_GRP_SETTING = 'UNSUPPORTED_GRP_SETTING';
    const SHOULD_SET_IN_TARGET_GOAL_THROUGH_GRP_SETTINGS = 'SHOULD_SET_IN_TARGET_GOAL_THROUGH_GRP_SETTINGS';
    const SHOULD_SET_IN_TARGET_GOAL_THROUGH_PRIMARY_GOAL = 'SHOULD_SET_IN_TARGET_GOAL_THROUGH_PRIMARY_GOAL';
    const NIELSEN_REGISTRATION_FAILED = 'NIELSEN_REGISTRATION_FAILED';
    const LEGACY_NIELSEN_CAMPAIGN_REGISTRATION_ATTEMPT = 'LEGACY_NIELSEN_CAMPAIGN_REGISTRATION_ATTEMPT';
    const UNKNOWN = 'UNKNOWN';


}
