<?php

namespace Google\AdsApi\Dfp\v201708;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AssetErrorReason
{
    const NON_UNIQUE_NAME = 'NON_UNIQUE_NAME';
    const FILE_NAME_TOO_LONG = 'FILE_NAME_TOO_LONG';
    const FILE_SIZE_TOO_LARGE = 'FILE_SIZE_TOO_LARGE';
    const MISSING_REQUIRED_DYNAMIC_ALLOCATION_CLIENT = 'MISSING_REQUIRED_DYNAMIC_ALLOCATION_CLIENT';
    const MISSING_REQUIRED_DYNAMIC_ALLOCATION_HEIGHT = 'MISSING_REQUIRED_DYNAMIC_ALLOCATION_HEIGHT';
    const MISSING_REQUIRED_DYNAMIC_ALLOCATION_WIDTH = 'MISSING_REQUIRED_DYNAMIC_ALLOCATION_WIDTH';
    const MISSING_REQUIRED_DYNAMIC_ALLOCATION_FORMAT = 'MISSING_REQUIRED_DYNAMIC_ALLOCATION_FORMAT';
    const INVALID_CODE_SNIPPET_PARAMETER_VALUE = 'INVALID_CODE_SNIPPET_PARAMETER_VALUE';
    const INVALID_ASSET_ID = 'INVALID_ASSET_ID';
    const UNKNOWN = 'UNKNOWN';


}
