<?php

namespace Google\AdsApi\Dfp\v201708;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CreativeWrapperErrorReason
{
    const LABEL_ALREADY_ASSOCIATED_WITH_CREATIVE_WRAPPER = 'LABEL_ALREADY_ASSOCIATED_WITH_CREATIVE_WRAPPER';
    const INVALID_LABEL_TYPE = 'INVALID_LABEL_TYPE';
    const UNRECOGNIZED_MACRO = 'UNRECOGNIZED_MACRO';
    const NEITHER_HEADER_NOR_FOOTER_SPECIFIED = 'NEITHER_HEADER_NOR_FOOTER_SPECIFIED';
    const CANNOT_USE_CREATIVE_WRAPPER_TYPE = 'CANNOT_USE_CREATIVE_WRAPPER_TYPE';
    const CANNOT_UPDATE_LABEL_ID = 'CANNOT_UPDATE_LABEL_ID';
    const CANNOT_APPLY_TO_AD_UNIT_WITH_VIDEO_SIZES = 'CANNOT_APPLY_TO_AD_UNIT_WITH_VIDEO_SIZES';
    const CANNOT_APPLY_TO_MOBILE_AD_UNIT = 'CANNOT_APPLY_TO_MOBILE_AD_UNIT';
    const UNKNOWN = 'UNKNOWN';


}
