<?php

namespace Google\AdsApi\Dfp\v201708;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ImageErrorReason
{
    const INVALID_IMAGE = 'INVALID_IMAGE';
    const INVALID_SIZE = 'INVALID_SIZE';
    const UNEXPECTED_SIZE = 'UNEXPECTED_SIZE';
    const OVERLAY_SIZE_TOO_LARGE = 'OVERLAY_SIZE_TOO_LARGE';
    const ANIMATED_NOT_ALLOWED = 'ANIMATED_NOT_ALLOWED';
    const ANIMATION_TOO_LONG = 'ANIMATION_TOO_LONG';
    const CMYK_JPEG_NOT_ALLOWED = 'CMYK_JPEG_NOT_ALLOWED';
    const FLASH_NOT_ALLOWED = 'FLASH_NOT_ALLOWED';
    const FLASH_WITHOUT_CLICKTAG = 'FLASH_WITHOUT_CLICKTAG';
    const ANIMATED_VISUAL_EFFECT = 'ANIMATED_VISUAL_EFFECT';
    const FLASH_ERROR = 'FLASH_ERROR';
    const LAYOUT_PROBLEM = 'LAYOUT_PROBLEM';
    const FLASH_HAS_NETWORK_OBJECTS = 'FLASH_HAS_NETWORK_OBJECTS';
    const FLASH_HAS_NETWORK_METHODS = 'FLASH_HAS_NETWORK_METHODS';
    const FLASH_HAS_URL = 'FLASH_HAS_URL';
    const FLASH_HAS_MOUSE_TRACKING = 'FLASH_HAS_MOUSE_TRACKING';
    const FLASH_HAS_RANDOM_NUM = 'FLASH_HAS_RANDOM_NUM';
    const FLASH_SELF_TARGETS = 'FLASH_SELF_TARGETS';
    const FLASH_BAD_GETURL_TARGET = 'FLASH_BAD_GETURL_TARGET';
    const FLASH_VERSION_NOT_SUPPORTED = 'FLASH_VERSION_NOT_SUPPORTED';
    const FILE_TOO_LARGE = 'FILE_TOO_LARGE';
    const SYSTEM_ERROR = 'SYSTEM_ERROR';
    const UNEXPECTED_PRIMARY_ASSET_DENSITY = 'UNEXPECTED_PRIMARY_ASSET_DENSITY';
    const DUPLICATE_ASSET_DENSITY = 'DUPLICATE_ASSET_DENSITY';
    const MISSING_DEFAULT_ASSET = 'MISSING_DEFAULT_ASSET';
    const UNKNOWN = 'UNKNOWN';


}
