<?php

namespace Google\AdsApi\Dfp\v201708;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ReconciliationErrorReason
{
    const CANNOT_CREATE_RECONCILIATION_REPORT_VERSION = 'CANNOT_CREATE_RECONCILIATION_REPORT_VERSION';
    const INVALID_RECONCILIATION_REPORT_STATE_TRANSITION = 'INVALID_RECONCILIATION_REPORT_STATE_TRANSITION';
    const INVALID_RECONCILIATION_PROPOSAL_SUBMISSION_SEQUENCE = 'INVALID_RECONCILIATION_PROPOSAL_SUBMISSION_SEQUENCE';
    const USER_CANNOT_RECONCILE_RECONCILIATION_REPORT = 'USER_CANNOT_RECONCILE_RECONCILIATION_REPORT';
    const CONTRACTED_VOLUME_CANNOT_BE_NULL = 'CONTRACTED_VOLUME_CANNOT_BE_NULL';
    const DFP_VOLUME_CANNOT_BE_NULL = 'DFP_VOLUME_CANNOT_BE_NULL';
    const MANUAL_VOLUME_CANNOT_BE_NULL = 'MANUAL_VOLUME_CANNOT_BE_NULL';
    const THIRD_PARTY_VOLUME_CANNOT_BE_NULL = 'THIRD_PARTY_VOLUME_CANNOT_BE_NULL';
    const DUPLICATE_LINE_ITEM_AND_CREATIVE = 'DUPLICATE_LINE_ITEM_AND_CREATIVE';
    const CANNOT_RECONCILE_LINE_ITEM_CREATIVE = 'CANNOT_RECONCILE_LINE_ITEM_CREATIVE';
    const LINE_ITEM_DAYS_MISMATCH = 'LINE_ITEM_DAYS_MISMATCH';
    const LINE_ITEM_BILL_OFF_OF_MISMATCH = 'LINE_ITEM_BILL_OFF_OF_MISMATCH';
    const CANNOT_MODIFY_RECONCILED_ORDER = 'CANNOT_MODIFY_RECONCILED_ORDER';
    const CANNOT_MODIFY_ACROSS_MULTIPLE_RECONCILIATION_REPORTS = 'CANNOT_MODIFY_ACROSS_MULTIPLE_RECONCILIATION_REPORTS';
    const CANNOT_QUERY_ACROSS_MULTIPLE_RECONCILIATION_REPORTS = 'CANNOT_QUERY_ACROSS_MULTIPLE_RECONCILIATION_REPORTS';
    const CANNOT_UPDATE_VOLUME_WHEN_BILLABLE_REVENUE_OVERRIDDEN = 'CANNOT_UPDATE_VOLUME_WHEN_BILLABLE_REVENUE_OVERRIDDEN';
    const UNKNOWN = 'UNKNOWN';


}
