<?php

namespace Google\AdsApi\Dfp\v201708;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class TechnologyTargetingErrorReason
{
    const MOBILE_LINE_ITEM_CONTAINS_WEB_TECH_CRITERIA = 'MOBILE_LINE_ITEM_CONTAINS_WEB_TECH_CRITERIA';
    const WEB_LINE_ITEM_CONTAINS_MOBILE_TECH_CRITERIA = 'WEB_LINE_ITEM_CONTAINS_MOBILE_TECH_CRITERIA';
    const MOBILE_CARRIER_TARGETING_FEATURE_NOT_ENABLED = 'MOBILE_CARRIER_TARGETING_FEATURE_NOT_ENABLED';
    const DEVICE_CAPABILITY_TARGETING_FEATURE_NOT_ENABLED = 'DEVICE_CAPABILITY_TARGETING_FEATURE_NOT_ENABLED';
    const DEVICE_CATEGORY_TARGETING_FEATURE_NOT_ENABLED = 'DEVICE_CATEGORY_TARGETING_FEATURE_NOT_ENABLED';
    const UNKNOWN = 'UNKNOWN';


}
