<?php

namespace Google\AdsApi\Dfp\v201708;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class UnitType
{
    const IMPRESSIONS = 'IMPRESSIONS';
    const CLICKS = 'CLICKS';
    const CLICK_THROUGH_CPA_CONVERSIONS = 'CLICK_THROUGH_CPA_CONVERSIONS';
    const VIEW_THROUGH_CPA_CONVERSIONS = 'VIEW_THROUGH_CPA_CONVERSIONS';
    const TOTAL_CPA_CONVERSIONS = 'TOTAL_CPA_CONVERSIONS';
    const VIEWABLE_IMPRESSIONS = 'VIEWABLE_IMPRESSIONS';
    const UNKNOWN = 'UNKNOWN';


}
