<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdGroupType
{
    const UNKNOWN = 'UNKNOWN';
    const SEARCH_STANDARD = 'SEARCH_STANDARD';
    const SEARCH_DYNAMIC_ADS = 'SEARCH_DYNAMIC_ADS';
    const DISPLAY_STANDARD = 'DISPLAY_STANDARD';
    const SHOPPING_PRODUCT_ADS = 'SHOPPING_PRODUCT_ADS';
    const SHOPPING_SHOWCASE_ADS = 'SHOPPING_SHOWCASE_ADS';
    const SHOPPING_GOAL_OPTIMIZED_ADS = 'SHOPPING_GOAL_OPTIMIZED_ADS';


}
