<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdGroupFeedErrorReason
{
    const FEED_ALREADY_EXISTS_FOR_PLACEHOLDER_TYPE = 'FEED_ALREADY_EXISTS_FOR_PLACEHOLDER_TYPE';
    const INVALID_ID = 'INVALID_ID';
    const CANNOT_ADD_FOR_DELETED_FEED = 'CANNOT_ADD_FOR_DELETED_FEED';
    const CANNOT_ADD_ALREADY_EXISTING_ADGROUP_FEED = 'CANNOT_ADD_ALREADY_EXISTING_ADGROUP_FEED';
    const CANNOT_OPERATE_ON_REMOVED_ADGROUP_FEED = 'CANNOT_OPERATE_ON_REMOVED_ADGROUP_FEED';
    const INVALID_PLACEHOLDER_TYPES = 'INVALID_PLACEHOLDER_TYPES';
    const MISSING_FEEDMAPPING_FOR_PLACEHOLDER_TYPE = 'MISSING_FEEDMAPPING_FOR_PLACEHOLDER_TYPE';
    const NO_EXISTING_LOCATION_CUSTOMER_FEED = 'NO_EXISTING_LOCATION_CUSTOMER_FEED';
    const UNKNOWN = 'UNKNOWN';


}
