<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdGroupServiceErrorReason
{
    const DUPLICATE_ADGROUP_NAME = 'DUPLICATE_ADGROUP_NAME';
    const INVALID_ADGROUP_NAME = 'INVALID_ADGROUP_NAME';
    const USE_SET_OPERATOR_AND_MARK_STATUS_TO_REMOVED = 'USE_SET_OPERATOR_AND_MARK_STATUS_TO_REMOVED';
    const ADVERTISER_NOT_ON_CONTENT_NETWORK = 'ADVERTISER_NOT_ON_CONTENT_NETWORK';
    const BID_TOO_BIG = 'BID_TOO_BIG';
    const BID_TYPE_AND_BIDDING_STRATEGY_MISMATCH = 'BID_TYPE_AND_BIDDING_STRATEGY_MISMATCH';
    const MISSING_ADGROUP_NAME = 'MISSING_ADGROUP_NAME';
    const ADGROUP_LABEL_DOES_NOT_EXIST = 'ADGROUP_LABEL_DOES_NOT_EXIST';
    const ADGROUP_LABEL_ALREADY_EXISTS = 'ADGROUP_LABEL_ALREADY_EXISTS';
    const INVALID_CONTENT_BID_CRITERION_TYPE_GROUP = 'INVALID_CONTENT_BID_CRITERION_TYPE_GROUP';
    const AD_GROUP_TYPE_NOT_VALID_FOR_ADVERTISING_CHANNEL_TYPE = 'AD_GROUP_TYPE_NOT_VALID_FOR_ADVERTISING_CHANNEL_TYPE';
    const ADGROUP_TYPE_NOT_SUPPORTED_FOR_CAMPAIGN_SALES_COUNTRY = 'ADGROUP_TYPE_NOT_SUPPORTED_FOR_CAMPAIGN_SALES_COUNTRY';
    const CANNOT_ADD_ADGROUP_OF_TYPE_DSA_TO_CAMPAIGN_WITHOUT_DSA_SETTING = 'CANNOT_ADD_ADGROUP_OF_TYPE_DSA_TO_CAMPAIGN_WITHOUT_DSA_SETTING';


}
