<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdvertisingChannelSubType
{
    const UNKNOWN = 'UNKNOWN';
    const SEARCH_MOBILE_APP = 'SEARCH_MOBILE_APP';
    const DISPLAY_MOBILE_APP = 'DISPLAY_MOBILE_APP';
    const SEARCH_EXPRESS = 'SEARCH_EXPRESS';
    const DISPLAY_EXPRESS = 'DISPLAY_EXPRESS';
    const UNIVERSAL_APP_CAMPAIGN = 'UNIVERSAL_APP_CAMPAIGN';
    const DISPLAY_SMART_CAMPAIGN = 'DISPLAY_SMART_CAMPAIGN';
    const SHOPPING_GOAL_OPTIMIZED_ADS = 'SHOPPING_GOAL_OPTIMIZED_ADS';
    const DISPLAY_GMAIL_AD = 'DISPLAY_GMAIL_AD';


}
