<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BudgetErrorReason
{
    const BUDGET_CANNOT_BE_EXPLICITLY_SHARED = 'BUDGET_CANNOT_BE_EXPLICITLY_SHARED';
    const BUDGET_REMOVED = 'BUDGET_REMOVED';
    const BUDGET_ERROR = 'BUDGET_ERROR';
    const BUDGET_IN_USE = 'BUDGET_IN_USE';
    const BUDGET_PERIOD_NOT_AVAILABLE = 'BUDGET_PERIOD_NOT_AVAILABLE';
    const CANNOT_EDIT_SHARED_BUDGET = 'CANNOT_EDIT_SHARED_BUDGET';
    const CANNOT_MODIFY_FIELD_OF_IMPLICITLY_SHARED_BUDGET = 'CANNOT_MODIFY_FIELD_OF_IMPLICITLY_SHARED_BUDGET';
    const CANNOT_UPDATE_BUDGET_TO_IMPLICITLY_SHARED = 'CANNOT_UPDATE_BUDGET_TO_IMPLICITLY_SHARED';
    const CANNOT_UPDATE_BUDGET_TO_EXPLICITLY_SHARED_WITHOUT_NAME = 'CANNOT_UPDATE_BUDGET_TO_EXPLICITLY_SHARED_WITHOUT_NAME';
    const CANNOT_UPDATE_BUDGET_TO_EXPLICITLY_SHARED = 'CANNOT_UPDATE_BUDGET_TO_EXPLICITLY_SHARED';
    const CANNOT_USE_IMPLICITLY_SHARED_BUDGET_WITH_MULTIPLE_CAMPAIGNS = 'CANNOT_USE_IMPLICITLY_SHARED_BUDGET_WITH_MULTIPLE_CAMPAIGNS';
    const DUPLICATE_NAME = 'DUPLICATE_NAME';
    const MONEY_AMOUNT_IN_WRONG_CURRENCY = 'MONEY_AMOUNT_IN_WRONG_CURRENCY';
    const MONEY_AMOUNT_LESS_THAN_CURRENCY_MINIMUM_CPC = 'MONEY_AMOUNT_LESS_THAN_CURRENCY_MINIMUM_CPC';
    const MONEY_AMOUNT_TOO_LARGE = 'MONEY_AMOUNT_TOO_LARGE';
    const NEGATIVE_MONEY_AMOUNT = 'NEGATIVE_MONEY_AMOUNT';
    const NON_MULTIPLE_OF_MINIMUM_CURRENCY_UNIT = 'NON_MULTIPLE_OF_MINIMUM_CURRENCY_UNIT';


}
