<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CustomerNegativeCriterionErrorReason
{
    const INVALID_CRITERION_TYPE = 'INVALID_CRITERION_TYPE';
    const SHARED_SET_IS_DELETED = 'SHARED_SET_IS_DELETED';
    const INVALID_SHARED_SET_TYPE = 'INVALID_SHARED_SET_TYPE';
    const MANAGER_CUSTOMER_CANNOT_ADD = 'MANAGER_CUSTOMER_CANNOT_ADD';
    const CUSTOMER_EXCLUSION_CRITERION_ERROR = 'CUSTOMER_EXCLUSION_CRITERION_ERROR';


}
