<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class FeedItemErrorReason
{
    const CAMPAIGN_TARGETING_MISMATCH = 'CAMPAIGN_TARGETING_MISMATCH';
    const CANNOT_CONVERT_ATTRIBUTE_VALUE_FROM_STRING = 'CANNOT_CONVERT_ATTRIBUTE_VALUE_FROM_STRING';
    const CANNOT_OPERATE_ON_REMOVED_FEED_ITEM = 'CANNOT_OPERATE_ON_REMOVED_FEED_ITEM';
    const DATE_TIME_MUST_BE_IN_ACCOUNT_TIME_ZONE = 'DATE_TIME_MUST_BE_IN_ACCOUNT_TIME_ZONE';
    const KEY_ATTRIBUTES_NOT_FOUND = 'KEY_ATTRIBUTES_NOT_FOUND';
    const INVALID_DEVICE_PREFERENCE = 'INVALID_DEVICE_PREFERENCE';
    const INVALID_SCHEDULE_END = 'INVALID_SCHEDULE_END';
    const INVALID_URL = 'INVALID_URL';
    const MISSING_KEY_ATTRIBUTES = 'MISSING_KEY_ATTRIBUTES';
    const KEY_ATTRIBUTES_NOT_UNIQUE = 'KEY_ATTRIBUTES_NOT_UNIQUE';
    const CANNOT_MODIFY_KEY_ATTRIBUTE_VALUE = 'CANNOT_MODIFY_KEY_ATTRIBUTE_VALUE';
    const OVERLAPPING_SCHEDULES = 'OVERLAPPING_SCHEDULES';
    const SCHEDULE_END_NOT_AFTER_START = 'SCHEDULE_END_NOT_AFTER_START';
    const TOO_MANY_SCHEDULES_PER_DAY = 'TOO_MANY_SCHEDULES_PER_DAY';
    const SIZE_TOO_LARGE_FOR_MULTI_VALUE_ATTRIBUTE = 'SIZE_TOO_LARGE_FOR_MULTI_VALUE_ATTRIBUTE';
    const UNKNOWN = 'UNKNOWN';


}
