<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class FeedMappingErrorReason
{
    const INVALID_PLACEHOLDER_FIELD = 'INVALID_PLACEHOLDER_FIELD';
    const INVALID_CRITERION_FIELD = 'INVALID_CRITERION_FIELD';
    const INVALID_PLACEHOLDER_TYPE = 'INVALID_PLACEHOLDER_TYPE';
    const INVALID_CRITERION_TYPE = 'INVALID_CRITERION_TYPE';
    const CANNOT_SET_PLACEHOLDER_TYPE_AND_CRITERION_TYPE = 'CANNOT_SET_PLACEHOLDER_TYPE_AND_CRITERION_TYPE';
    const NO_ATTRIBUTE_FIELD_MAPPINGS = 'NO_ATTRIBUTE_FIELD_MAPPINGS';
    const FEED_ATTRIBUTE_TYPE_MISMATCH = 'FEED_ATTRIBUTE_TYPE_MISMATCH';
    const CANNOT_OPERATE_ON_MAPPINGS_FOR_SYSTEM_GENERATED_FEED = 'CANNOT_OPERATE_ON_MAPPINGS_FOR_SYSTEM_GENERATED_FEED';
    const MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_TYPE = 'MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_TYPE';
    const MULTIPLE_MAPPINGS_FOR_CRITERION_TYPE = 'MULTIPLE_MAPPINGS_FOR_CRITERION_TYPE';
    const MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_FIELD = 'MULTIPLE_MAPPINGS_FOR_PLACEHOLDER_FIELD';
    const MULTIPLE_MAPPINGS_FOR_CRITERION_FIELD = 'MULTIPLE_MAPPINGS_FOR_CRITERION_FIELD';
    const UNEXPECTED_ATTRIBUTE_FIELD_MAPPINGS = 'UNEXPECTED_ATTRIBUTE_FIELD_MAPPINGS';
    const LOCATION_PLACEHOLDER_ONLY_FOR_PLACES_FEEDS = 'LOCATION_PLACEHOLDER_ONLY_FOR_PLACES_FEEDS';
    const CANNOT_MODIFY_MAPPINGS_FOR_TYPED_FEED = 'CANNOT_MODIFY_MAPPINGS_FOR_TYPED_FEED';
    const INVALID_PLACEHOLDER_TYPE_FOR_NON_SYSTEM_GENERATED_FEED = 'INVALID_PLACEHOLDER_TYPE_FOR_NON_SYSTEM_GENERATED_FEED';
    const INVALID_PLACEHOLDER_TYPE_FOR_SYSTEM_GENERATED_FEED_TYPE = 'INVALID_PLACEHOLDER_TYPE_FOR_SYSTEM_GENERATED_FEED_TYPE';
    const UNKNOWN = 'UNKNOWN';


}
