<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class MediaErrorReason
{
    const CANNOT_ADD_STANDARD_ICON = 'CANNOT_ADD_STANDARD_ICON';
    const CANNOT_SELECT_STANDARD_ICON_WITH_OTHER_TYPES = 'CANNOT_SELECT_STANDARD_ICON_WITH_OTHER_TYPES';
    const CANNOT_SPECIFY_MEDIA_ID_AND_DATA = 'CANNOT_SPECIFY_MEDIA_ID_AND_DATA';
    const DUPLICATE_MEDIA = 'DUPLICATE_MEDIA';
    const EMPTY_FIELD = 'EMPTY_FIELD';
    const ENTITY_REFERENCED_IN_MULTIPLE_OPS = 'ENTITY_REFERENCED_IN_MULTIPLE_OPS';
    const FIELD_NOT_SUPPORTED_FOR_MEDIA_SUB_TYPE = 'FIELD_NOT_SUPPORTED_FOR_MEDIA_SUB_TYPE';
    const INVALID_MEDIA_ID = 'INVALID_MEDIA_ID';
    const INVALID_MEDIA_SUB_TYPE = 'INVALID_MEDIA_SUB_TYPE';
    const INVALID_MEDIA_TYPE = 'INVALID_MEDIA_TYPE';
    const INVALID_MIME_TYPE = 'INVALID_MIME_TYPE';
    const INVALID_REFERENCE_ID = 'INVALID_REFERENCE_ID';
    const INVALID_YOU_TUBE_ID = 'INVALID_YOU_TUBE_ID';
    const MEDIA_FAILED_TRANSCODING = 'MEDIA_FAILED_TRANSCODING';
    const MEDIA_NOT_TRANSCODED = 'MEDIA_NOT_TRANSCODED';
    const MEDIA_TYPE_DOES_NOT_MATCH_OBJECT_TYPE = 'MEDIA_TYPE_DOES_NOT_MATCH_OBJECT_TYPE';
    const NO_FIELDS_SPECIFIED = 'NO_FIELDS_SPECIFIED';
    const NULL_REFERENCE_ID_AND_MEDIA_ID = 'NULL_REFERENCE_ID_AND_MEDIA_ID';
    const TOO_LONG = 'TOO_LONG';
    const UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION';
    const UNSUPPORTED_TYPE = 'UNSUPPORTED_TYPE';
    const YOU_TUBE_SERVICE_UNAVAILABLE = 'YOU_TUBE_SERVICE_UNAVAILABLE';
    const YOU_TUBE_VIDEO_HAS_NON_POSITIVE_DURATION = 'YOU_TUBE_VIDEO_HAS_NON_POSITIVE_DURATION';
    const YOU_TUBE_VIDEO_NOT_FOUND = 'YOU_TUBE_VIDEO_NOT_FOUND';


}
