<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class OfflineConversionErrorReason
{
    const UNPARSEABLE_GCLID = 'UNPARSEABLE_GCLID';
    const CONVERSION_PRECEDES_CLICK = 'CONVERSION_PRECEDES_CLICK';
    const FUTURE_CONVERSION_TIME = 'FUTURE_CONVERSION_TIME';
    const EXPIRED_CLICK = 'EXPIRED_CLICK';
    const TOO_RECENT_CLICK = 'TOO_RECENT_CLICK';
    const INVALID_CLICK = 'INVALID_CLICK';
    const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
    const INVALID_CONVERSION_TYPE = 'INVALID_CONVERSION_TYPE';
    const TOO_RECENT_CONVERSION_TYPE = 'TOO_RECENT_CONVERSION_TYPE';
    const CLICK_MISSING_CONVERSION_LABEL = 'CLICK_MISSING_CONVERSION_LABEL';
    const ATTRIBUTED_CREDIT_SET_FOR_NON_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION = 'ATTRIBUTED_CREDIT_SET_FOR_NON_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION';
    const ATTRIBUTION_MODEL_SET_FOR_NON_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION = 'ATTRIBUTION_MODEL_SET_FOR_NON_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION';
    const ATTRIBUTED_CREDIT_NOT_SET_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION = 'ATTRIBUTED_CREDIT_NOT_SET_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION';
    const ATTRIBUTED_CREDIT_ZERO_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION = 'ATTRIBUTED_CREDIT_ZERO_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION';
    const ATTRIBUTION_MODEL_NOT_SET_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION = 'ATTRIBUTION_MODEL_NOT_SET_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION';
    const ORDER_ID_NOT_PERMITTED_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION = 'ORDER_ID_NOT_PERMITTED_FOR_EXTERNALLY_ATTRIBUTED_CONVERSION_ACTION';
    const UNKNOWN = 'UNKNOWN';


}
