<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class PerformanceTargetErrorReason
{
    const SPEND_TARGET_REQUIRES_DATE_RANGE = 'SPEND_TARGET_REQUIRES_DATE_RANGE';
    const VOLUME_TARGET_VALUE_REQUIRES_DATE_RANGE = 'VOLUME_TARGET_VALUE_REQUIRES_DATE_RANGE';
    const START_DATE_AFTER_END_DATE = 'START_DATE_AFTER_END_DATE';
    const INCOMPATIBLE_EFFICIENCY_TARGET_TYPE = 'INCOMPATIBLE_EFFICIENCY_TARGET_TYPE';
    const EFFICIENCY_TARGET_VALUE_AND_TYPE_ARE_MUTUALLY_REQUIRED = 'EFFICIENCY_TARGET_VALUE_AND_TYPE_ARE_MUTUALLY_REQUIRED';
    const OVERLAPPING_DATE_RANGE = 'OVERLAPPING_DATE_RANGE';
    const HISTORICAL_PERFORMANCE_TARGETS_CANNOT_BE_MODIFIED = 'HISTORICAL_PERFORMANCE_TARGETS_CANNOT_BE_MODIFIED';
    const SPEND_TARGET_AND_SPEND_TARGET_TYPE_ARE_MUTUALLY_REQUIRED = 'SPEND_TARGET_AND_SPEND_TARGET_TYPE_ARE_MUTUALLY_REQUIRED';
    const PERFORMANCE_TARGET_ERROR = 'PERFORMANCE_TARGET_ERROR';


}
