<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class SelectorErrorReason
{
    const INVALID_FIELD_NAME = 'INVALID_FIELD_NAME';
    const MISSING_FIELDS = 'MISSING_FIELDS';
    const MISSING_PREDICATES = 'MISSING_PREDICATES';
    const OPERATOR_DOES_NOT_SUPPORT_MULTIPLE_VALUES = 'OPERATOR_DOES_NOT_SUPPORT_MULTIPLE_VALUES';
    const INVALID_PREDICATE_ENUM_VALUE = 'INVALID_PREDICATE_ENUM_VALUE';
    const MISSING_PREDICATE_OPERATOR = 'MISSING_PREDICATE_OPERATOR';
    const MISSING_PREDICATE_VALUES = 'MISSING_PREDICATE_VALUES';
    const INVALID_PREDICATE_FIELD_NAME = 'INVALID_PREDICATE_FIELD_NAME';
    const INVALID_PREDICATE_OPERATOR = 'INVALID_PREDICATE_OPERATOR';
    const INVALID_FIELD_SELECTION = 'INVALID_FIELD_SELECTION';
    const INVALID_PREDICATE_VALUE = 'INVALID_PREDICATE_VALUE';
    const INVALID_SORT_FIELD_NAME = 'INVALID_SORT_FIELD_NAME';
    const SELECTOR_ERROR = 'SELECTOR_ERROR';
    const FILTER_BY_DATE_RANGE_NOT_SUPPORTED = 'FILTER_BY_DATE_RANGE_NOT_SUPPORTED';
    const START_INDEX_IS_TOO_HIGH = 'START_INDEX_IS_TOO_HIGH';
    const TOO_MANY_PREDICATE_VALUES = 'TOO_MANY_PREDICATE_VALUES';
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';


}
