<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class SharedSetErrorReason
{
    const CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE = 'CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE';
    const DUPLICATE_NAME = 'DUPLICATE_NAME';
    const MANAGER_CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE = 'MANAGER_CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE';
    const SHARED_SET_REMOVED = 'SHARED_SET_REMOVED';
    const SHARED_SET_IN_USE = 'SHARED_SET_IN_USE';
    const UNKNOWN = 'UNKNOWN';


}
