<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class TrialErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION';
    const CANNOT_USE_TRIAL_WITH_SHARED_BUDGET = 'CANNOT_USE_TRIAL_WITH_SHARED_BUDGET';
    const CANNOT_CREATE_TRIAL_WHEN_CAMPAIGN_HAS_ACTIVE_EXPERIMENTS = 'CANNOT_CREATE_TRIAL_WHEN_CAMPAIGN_HAS_ACTIVE_EXPERIMENTS';
    const CANNOT_CREATE_TRIAL_FOR_DELETED_BASE_CAMPAIGN = 'CANNOT_CREATE_TRIAL_FOR_DELETED_BASE_CAMPAIGN';
    const CANNOT_CREATE_TRIAL_FOR_NON_PROPOSED_DRAFT = 'CANNOT_CREATE_TRIAL_FOR_NON_PROPOSED_DRAFT';
    const CUSTOMER_CANNOT_CREATE_TRIAL = 'CUSTOMER_CANNOT_CREATE_TRIAL';
    const CAMPAIGN_CANNOT_CREATE_TRIAL = 'CAMPAIGN_CANNOT_CREATE_TRIAL';
    const NAME_ALREADY_IN_USE = 'NAME_ALREADY_IN_USE';
    const TRIAL_DURATIONS_MUST_NOT_OVERLAP = 'TRIAL_DURATIONS_MUST_NOT_OVERLAP';
    const TRIAL_DURATION_MUST_BE_WITHIN_CAMPAIGN_DURATION = 'TRIAL_DURATION_MUST_BE_WITHIN_CAMPAIGN_DURATION';


}
