<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class UrlErrorReason
{
    const INVALID_TRACKING_URL_TEMPLATE = 'INVALID_TRACKING_URL_TEMPLATE';
    const INVALID_TAG_IN_TRACKING_URL_TEMPLATE = 'INVALID_TAG_IN_TRACKING_URL_TEMPLATE';
    const MISSING_TRACKING_URL_TEMPLATE_TAG = 'MISSING_TRACKING_URL_TEMPLATE_TAG';
    const MISSING_PROTOCOL_IN_TRACKING_URL_TEMPLATE = 'MISSING_PROTOCOL_IN_TRACKING_URL_TEMPLATE';
    const INVALID_PROTOCOL_IN_TRACKING_URL_TEMPLATE = 'INVALID_PROTOCOL_IN_TRACKING_URL_TEMPLATE';
    const MALFORMED_TRACKING_URL_TEMPLATE = 'MALFORMED_TRACKING_URL_TEMPLATE';
    const MISSING_HOST_IN_TRACKING_URL_TEMPLATE = 'MISSING_HOST_IN_TRACKING_URL_TEMPLATE';
    const INVALID_TLD_IN_TRACKING_URL_TEMPLATE = 'INVALID_TLD_IN_TRACKING_URL_TEMPLATE';
    const REDUNDANT_NESTED_TRACKING_URL_TEMPLATE_TAG = 'REDUNDANT_NESTED_TRACKING_URL_TEMPLATE_TAG';
    const INVALID_FINAL_URL = 'INVALID_FINAL_URL';
    const INVALID_TAG_IN_FINAL_URL = 'INVALID_TAG_IN_FINAL_URL';
    const REDUNDANT_NESTED_FINAL_URL_TAG = 'REDUNDANT_NESTED_FINAL_URL_TAG';
    const MISSING_PROTOCOL_IN_FINAL_URL = 'MISSING_PROTOCOL_IN_FINAL_URL';
    const INVALID_PROTOCOL_IN_FINAL_URL = 'INVALID_PROTOCOL_IN_FINAL_URL';
    const MALFORMED_FINAL_URL = 'MALFORMED_FINAL_URL';
    const MISSING_HOST_IN_FINAL_URL = 'MISSING_HOST_IN_FINAL_URL';
    const INVALID_TLD_IN_FINAL_URL = 'INVALID_TLD_IN_FINAL_URL';
    const INVALID_FINAL_MOBILE_URL = 'INVALID_FINAL_MOBILE_URL';
    const INVALID_TAG_IN_FINAL_MOBILE_URL = 'INVALID_TAG_IN_FINAL_MOBILE_URL';
    const REDUNDANT_NESTED_FINAL_MOBILE_URL_TAG = 'REDUNDANT_NESTED_FINAL_MOBILE_URL_TAG';
    const MISSING_PROTOCOL_IN_FINAL_MOBILE_URL = 'MISSING_PROTOCOL_IN_FINAL_MOBILE_URL';
    const INVALID_PROTOCOL_IN_FINAL_MOBILE_URL = 'INVALID_PROTOCOL_IN_FINAL_MOBILE_URL';
    const MALFORMED_FINAL_MOBILE_URL = 'MALFORMED_FINAL_MOBILE_URL';
    const MISSING_HOST_IN_FINAL_MOBILE_URL = 'MISSING_HOST_IN_FINAL_MOBILE_URL';
    const INVALID_TLD_IN_FINAL_MOBILE_URL = 'INVALID_TLD_IN_FINAL_MOBILE_URL';
    const INVALID_FINAL_APP_URL = 'INVALID_FINAL_APP_URL';
    const INVALID_TAG_IN_FINAL_APP_URL = 'INVALID_TAG_IN_FINAL_APP_URL';
    const REDUNDANT_NESTED_FINAL_APP_URL_TAG = 'REDUNDANT_NESTED_FINAL_APP_URL_TAG';
    const MULTIPLE_APP_URLS_FOR_OSTYPE = 'MULTIPLE_APP_URLS_FOR_OSTYPE';
    const INVALID_OSTYPE = 'INVALID_OSTYPE';
    const INVALID_PROTOCOL_FOR_APP_URL = 'INVALID_PROTOCOL_FOR_APP_URL';
    const INVALID_PACKAGE_ID_FOR_APP_URL = 'INVALID_PACKAGE_ID_FOR_APP_URL';
    const URL_CUSTOM_PARAMETERS_COUNT_EXCEEDS_LIMIT = 'URL_CUSTOM_PARAMETERS_COUNT_EXCEEDS_LIMIT';
    const URL_CUSTOM_PARAMETER_REMOVAL_WITH_NON_NULL_VALUE = 'URL_CUSTOM_PARAMETER_REMOVAL_WITH_NON_NULL_VALUE';
    const CANNOT_REMOVE_URL_CUSTOM_PARAMETER_IN_ADD_OPERATION = 'CANNOT_REMOVE_URL_CUSTOM_PARAMETER_IN_ADD_OPERATION';
    const CANNOT_REMOVE_URL_CUSTOM_PARAMETER_DURING_FULL_REPLACEMENT = 'CANNOT_REMOVE_URL_CUSTOM_PARAMETER_DURING_FULL_REPLACEMENT';
    const FINAL_URL_SUFFIX_MALFORMED = 'FINAL_URL_SUFFIX_MALFORMED';
    const INVALID_TAG_IN_FINAL_URL_SUFFIX = 'INVALID_TAG_IN_FINAL_URL_SUFFIX';
    const NULL_CUSTOM_PARAMETER_VALUE_DURING_ADD_OR_FULL_REPLACEMENT = 'NULL_CUSTOM_PARAMETER_VALUE_DURING_ADD_OR_FULL_REPLACEMENT';
    const INVALID_CHARACTERS_IN_URL_CUSTOM_PARAMETER_KEY = 'INVALID_CHARACTERS_IN_URL_CUSTOM_PARAMETER_KEY';
    const INVALID_CHARACTERS_IN_URL_CUSTOM_PARAMETER_VALUE = 'INVALID_CHARACTERS_IN_URL_CUSTOM_PARAMETER_VALUE';
    const INVALID_TAG_IN_URL_CUSTOM_PARAMETER_VALUE = 'INVALID_TAG_IN_URL_CUSTOM_PARAMETER_VALUE';
    const REDUNDANT_NESTED_URL_CUSTOM_PARAMETER_TAG = 'REDUNDANT_NESTED_URL_CUSTOM_PARAMETER_TAG';
    const MISSING_PROTOCOL = 'MISSING_PROTOCOL';
    const INVALID_URL = 'INVALID_URL';
    const DESTINATION_URL_DEPRECATED = 'DESTINATION_URL_DEPRECATED';
    const INVALID_TAG_IN_URL = 'INVALID_TAG_IN_URL';
    const MISSING_URL_TAG = 'MISSING_URL_TAG';
    const DUPLICATE_URL_ID = 'DUPLICATE_URL_ID';
    const INVALID_URL_ID = 'INVALID_URL_ID';
    const URL_ERROR = 'URL_ERROR';


}
