<?php

namespace Google\AdsApi\AdWords\v201809\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class VideoErrorReason
{
    const INVALID_VIDEO = 'INVALID_VIDEO';
    const STORAGE_ERROR = 'STORAGE_ERROR';
    const BAD_REQUEST = 'BAD_REQUEST';
    const ERROR_GENERATING_STREAMING_URL = 'ERROR_GENERATING_STREAMING_URL';
    const UNEXPECTED_SIZE = 'UNEXPECTED_SIZE';
    const SERVER_ERROR = 'SERVER_ERROR';
    const FILE_TOO_LARGE = 'FILE_TOO_LARGE';
    const VIDEO_PROCESSING_ERROR = 'VIDEO_PROCESSING_ERROR';
    const INVALID_INPUT = 'INVALID_INPUT';
    const PROBLEM_READING_FILE = 'PROBLEM_READING_FILE';
    const INVALID_ISCI = 'INVALID_ISCI';
    const INVALID_AD_ID = 'INVALID_AD_ID';


}
