<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdExclusionRuleErrorReason
{
    const BLOCK_ALL_RULE_CANNOT_INCLUDE_ROOT_AD_UNIT = 'BLOCK_ALL_RULE_CANNOT_INCLUDE_ROOT_AD_UNIT';
    const BLOCK_ALL_RULE_CANNOT_HAVE_BLOCKED_LABELS = 'BLOCK_ALL_RULE_CANNOT_HAVE_BLOCKED_LABELS';
    const BLOCK_ALL_RULE_MUST_CONTAIN_ALLOWED_LABELS = 'BLOCK_ALL_RULE_MUST_CONTAIN_ALLOWED_LABELS';
    const RULE_MUST_CONTAIN_BLOCKING = 'RULE_MUST_CONTAIN_BLOCKING';
    const BLOCKED_LABEL_ALSO_ALLOWED = 'BLOCKED_LABEL_ALSO_ALLOWED';
    const LABELS_MUST_BE_AD_EXCLUSION_TYPE = 'LABELS_MUST_BE_AD_EXCLUSION_TYPE';
    const EXCLUDED_AD_UNIT_ALSO_INCLUDED = 'EXCLUDED_AD_UNIT_ALSO_INCLUDED';
    const UNKNOWN = 'UNKNOWN';


}
