<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AudienceSegmentErrorReason
{
    const FIRST_PARTY_AUDIENCE_SEGMENT_NOT_SUPPORTED = 'FIRST_PARTY_AUDIENCE_SEGMENT_NOT_SUPPORTED';
    const ONLY_RULE_BASED_FIRST_PARTY_AUDIENCE_SEGMENTS_CAN_BE_CREATED = 'ONLY_RULE_BASED_FIRST_PARTY_AUDIENCE_SEGMENTS_CAN_BE_CREATED';
    const AUDIENCE_SEGMENT_ID_NOT_FOUND = 'AUDIENCE_SEGMENT_ID_NOT_FOUND';
    const INVALID_AUDIENCE_SEGMENT_RULE = 'INVALID_AUDIENCE_SEGMENT_RULE';
    const AUDIENCE_SEGMENT_RULE_TOO_LONG = 'AUDIENCE_SEGMENT_RULE_TOO_LONG';
    const INVALID_AUDIENCE_SEGMENT_NAME = 'INVALID_AUDIENCE_SEGMENT_NAME';
    const DUPLICATE_AUDIENCE_SEGMENT_NAME = 'DUPLICATE_AUDIENCE_SEGMENT_NAME';
    const INVALID_AUDIENCE_SEGMENT_DESCRIPTION = 'INVALID_AUDIENCE_SEGMENT_DESCRIPTION';
    const INVALID_AUDIENCE_SEGMENT_PAGEVIEWS = 'INVALID_AUDIENCE_SEGMENT_PAGEVIEWS';
    const INVALID_AUDIENCE_SEGMENT_RECENCY = 'INVALID_AUDIENCE_SEGMENT_RECENCY';
    const INVALID_AUDIENCE_SEGMENT_MEMBERSHIP_EXPIRATION = 'INVALID_AUDIENCE_SEGMENT_MEMBERSHIP_EXPIRATION';
    const INVALID_AUDIENCE_SEGMENT_CUSTOM_KEY_NAME = 'INVALID_AUDIENCE_SEGMENT_CUSTOM_KEY_NAME';
    const INVALID_AUDIENCE_SEGMENT_CUSTOM_VALUE_NAME = 'INVALID_AUDIENCE_SEGMENT_CUSTOM_VALUE_NAME';
    const INVALID_AUDIENCE_SEGMENT_CUSTOM_VALUE_MATCH_TYPE = 'INVALID_AUDIENCE_SEGMENT_CUSTOM_VALUE_MATCH_TYPE';
    const INVALID_NESTED_FIRST_PARTY_AUDIENCE_SEGMENT = 'INVALID_NESTED_FIRST_PARTY_AUDIENCE_SEGMENT';
    const INVALID_NESTED_THIRD_PARTY_AUDIENCE_SEGMENT = 'INVALID_NESTED_THIRD_PARTY_AUDIENCE_SEGMENT';
    const INACTIVE_NESTED_AUDIENCE_SEGMENT = 'INACTIVE_NESTED_AUDIENCE_SEGMENT';
    const AUDIENCE_SEGMENT_GLOBAL_LICENSE_ERROR = 'AUDIENCE_SEGMENT_GLOBAL_LICENSE_ERROR';
    const UNKNOWN = 'UNKNOWN';


}
