<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AuthenticationErrorReason
{
    const AMBIGUOUS_SOAP_REQUEST_HEADER = 'AMBIGUOUS_SOAP_REQUEST_HEADER';
    const INVALID_EMAIL = 'INVALID_EMAIL';
    const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
    const INVALID_OAUTH_SIGNATURE = 'INVALID_OAUTH_SIGNATURE';
    const INVALID_SERVICE = 'INVALID_SERVICE';
    const MISSING_SOAP_REQUEST_HEADER = 'MISSING_SOAP_REQUEST_HEADER';
    const MISSING_AUTHENTICATION_HTTP_HEADER = 'MISSING_AUTHENTICATION_HTTP_HEADER';
    const MISSING_AUTHENTICATION = 'MISSING_AUTHENTICATION';
    const NOT_WHITELISTED_FOR_API_ACCESS = 'NOT_WHITELISTED_FOR_API_ACCESS';
    const NO_NETWORKS_TO_ACCESS = 'NO_NETWORKS_TO_ACCESS';
    const NETWORK_NOT_FOUND = 'NETWORK_NOT_FOUND';
    const NETWORK_CODE_REQUIRED = 'NETWORK_CODE_REQUIRED';
    const CONNECTION_ERROR = 'CONNECTION_ERROR';
    const GOOGLE_ACCOUNT_ALREADY_ASSOCIATED_WITH_NETWORK = 'GOOGLE_ACCOUNT_ALREADY_ASSOCIATED_WITH_NETWORK';
    const UNDER_INVESTIGATION = 'UNDER_INVESTIGATION';
    const UNKNOWN = 'UNKNOWN';


}
