<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CreativePolicyViolation
{
    const MALWARE_IN_CREATIVE = 'MALWARE_IN_CREATIVE';
    const MALWARE_IN_LANDING_PAGE = 'MALWARE_IN_LANDING_PAGE';
    const LEGALLY_BLOCKED_REDIRECT_URL = 'LEGALLY_BLOCKED_REDIRECT_URL';
    const MISREPRESENTATION_OF_PRODUCT = 'MISREPRESENTATION_OF_PRODUCT';
    const SELF_CLICKING_CREATIVE = 'SELF_CLICKING_CREATIVE';
    const GAMING_GOOGLE_NETWORK = 'GAMING_GOOGLE_NETWORK';
    const DYNAMIC_DNS = 'DYNAMIC_DNS';
    const PHISHING = 'PHISHING';
    const DOWNLOAD_PROMPT_IN_CREATIVE = 'DOWNLOAD_PROMPT_IN_CREATIVE';
    const UNAUTHORIZED_COOKIE_DETECTED = 'UNAUTHORIZED_COOKIE_DETECTED';
    const UNKNOWN = 'UNKNOWN';


}
