<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class GeoTargetingErrorReason
{
    const TARGETED_LOCATIONS_NOT_EXCLUDABLE = 'TARGETED_LOCATIONS_NOT_EXCLUDABLE';
    const EXCLUDED_LOCATIONS_CANNOT_HAVE_CHILDREN_TARGETED = 'EXCLUDED_LOCATIONS_CANNOT_HAVE_CHILDREN_TARGETED';
    const POSTAL_CODES_CANNOT_BE_EXCLUDED = 'POSTAL_CODES_CANNOT_BE_EXCLUDED';
    const UNTARGETABLE_LOCATION = 'UNTARGETABLE_LOCATION';
    const UNKNOWN = 'UNKNOWN';


}
