<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class NativeStyleErrorReason
{
    const UNRECOGNIZED_PLACEHOLDER = 'UNRECOGNIZED_PLACEHOLDER';
    const NATIVE_CREATIVE_TEMPLATE_REQUIRED = 'NATIVE_CREATIVE_TEMPLATE_REQUIRED';
    const ACTIVE_CREATIVE_TEMPLATE_REQUIRED = 'ACTIVE_CREATIVE_TEMPLATE_REQUIRED';
    const UNIQUE_SNIPPET_REQUIRED = 'UNIQUE_SNIPPET_REQUIRED';
    const INVALID_CUSTOM_TARGETING_MATCH_TYPE = 'INVALID_CUSTOM_TARGETING_MATCH_TYPE';
    const TOO_MANY_CUSTOM_TARGETING_KEY_VALUES = 'TOO_MANY_CUSTOM_TARGETING_KEY_VALUES';
    const INVALID_TARGETING_TYPE = 'INVALID_TARGETING_TYPE';
    const INVALID_INVENTORY_TARTGETING_TYPE = 'INVALID_INVENTORY_TARTGETING_TYPE';
    const UNRECOGNIZED_MACRO = 'UNRECOGNIZED_MACRO';
    const UNKNOWN = 'UNKNOWN';


}
