<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProposalLineItemErrorReason
{
    const NOT_SAME_RATE_CARD = 'NOT_SAME_RATE_CARD';
    const LINE_ITEM_TYPE_NOT_ALLOWED = 'LINE_ITEM_TYPE_NOT_ALLOWED';
    const END_DATE_TIME_NOT_AFTER_START_TIME = 'END_DATE_TIME_NOT_AFTER_START_TIME';
    const END_DATE_TIME_TOO_LATE = 'END_DATE_TIME_TOO_LATE';
    const START_DATE_TIME_IS_IN_PAST = 'START_DATE_TIME_IS_IN_PAST';
    const END_DATE_TIME_IS_IN_PAST = 'END_DATE_TIME_IS_IN_PAST';
    const FRONTLOADED_NOT_ALLOWED = 'FRONTLOADED_NOT_ALLOWED';
    const ALL_ROADBLOCK_NOT_ALLOWED = 'ALL_ROADBLOCK_NOT_ALLOWED';
    const CREATIVE_SET_ROADBLOCK_NOT_ALLOWED = 'CREATIVE_SET_ROADBLOCK_NOT_ALLOWED';
    const ALREADY_STARTED = 'ALREADY_STARTED';
    const CONFLICT_WITH_PRODUCT = 'CONFLICT_WITH_PRODUCT';
    const VIOLATE_BUILT_IN_TARGETING_COMPATIBILITY_RESTRICTION = 'VIOLATE_BUILT_IN_TARGETING_COMPATIBILITY_RESTRICTION';
    const VIOLATE_BUILT_IN_TARGETING_LOCKED_RESTRICTION = 'VIOLATE_BUILT_IN_TARGETING_LOCKED_RESTRICTION';
    const MOBILE_TECH_CRITERIA_NOT_SUPPORTED = 'MOBILE_TECH_CRITERIA_NOT_SUPPORTED';
    const UNSUPPORTED_TARGETING_TYPE = 'UNSUPPORTED_TARGETING_TYPE';
    const WRONG_COST = 'WRONG_COST';
    const AGENCY_COMMISSION_MISMATCH = 'AGENCY_COMMISSION_MISMATCH';
    const CALCULATED_COST_TOO_HIGH = 'CALCULATED_COST_TOO_HIGH';
    const INVALID_PRIORITY_FOR_LINE_ITEM_TYPE = 'INVALID_PRIORITY_FOR_LINE_ITEM_TYPE';
    const UPDATE_PROPOSAL_LINE_ITEM_NOT_ALLOWED = 'UPDATE_PROPOSAL_LINE_ITEM_NOT_ALLOWED';
    const CANNOT_UPDATE_TO_OR_FROM_CREATIVE_SET_ROADBLOCK = 'CANNOT_UPDATE_TO_OR_FROM_CREATIVE_SET_ROADBLOCK';
    const SEQUENTIAL_CREATIVE_ROTATION_NOT_ALLOWED = 'SEQUENTIAL_CREATIVE_ROTATION_NOT_ALLOWED';
    const UPDATE_RESERVATION_NOT_ALLOWED = 'UPDATE_RESERVATION_NOT_ALLOWED';
    const INVALID_COMPANION_DELIVERY_OPTION_FOR_ROADBLOCKING_TYPE = 'INVALID_COMPANION_DELIVERY_OPTION_FOR_ROADBLOCKING_TYPE';
    const INVALID_COMPANION_DELIVERY_OPTION_FOR_ENVIRONMENT_TYPE = 'INVALID_COMPANION_DELIVERY_OPTION_FOR_ENVIRONMENT_TYPE';
    const INCONSISTENT_ROADBLOCK_TYPE = 'INCONSISTENT_ROADBLOCK_TYPE';
    const INVALID_CONTRACTED_QUANTITY_BUFFER = 'INVALID_CONTRACTED_QUANTITY_BUFFER';
    const INVALID_VALUES_FOR_CLICK_TRACKING_LINE_ITEM_TYPE = 'INVALID_VALUES_FOR_CLICK_TRACKING_LINE_ITEM_TYPE';
    const UPDATE_COST_ADJUSTMENT_NOT_ALLOWED = 'UPDATE_COST_ADJUSTMENT_NOT_ALLOWED';
    const UNSUPPORTED_RATE_CARD_CURRENCY_CODE = 'UNSUPPORTED_RATE_CARD_CURRENCY_CODE';
    const END_DATE_TIME_IS_BEFORE_LAST_PAUSED_TIME = 'END_DATE_TIME_IS_BEFORE_LAST_PAUSED_TIME';
    const VIDEO_INVALID_ROADBLOCKING = 'VIDEO_INVALID_ROADBLOCKING';
    const UPDATE_TIME_ZONE_NOT_ALLOWED = 'UPDATE_TIME_ZONE_NOT_ALLOWED';
    const INVALID_TIME_ZONE_FOR_RATE_TYPE = 'INVALID_TIME_ZONE_FOR_RATE_TYPE';
    const INVALID_TIME_ZONE_FOR_DEALS = 'INVALID_TIME_ZONE_FOR_DEALS';
    const INVALID_ENVIRONMENT_TYPE = 'INVALID_ENVIRONMENT_TYPE';
    const SIZE_REQUIRED = 'SIZE_REQUIRED';
    const COMPANION_NOT_ALLOWED = 'COMPANION_NOT_ALLOWED';
    const MISSING_COMPANION = 'MISSING_COMPANION';
    const DUPLICATED_MASTER_SIZE = 'DUPLICATED_MASTER_SIZE';
    const INVALID_EXPECTED_CREATIVE_COUNT = 'INVALID_EXPECTED_CREATIVE_COUNT';
    const CANNOT_HAVE_CREATIVE_TEMPLATE = 'CANNOT_HAVE_CREATIVE_TEMPLATE';
    const NATIVE_CREATIVE_TEMPLATE_REQUIRED = 'NATIVE_CREATIVE_TEMPLATE_REQUIRED';
    const CANNOT_INCLUDE_NATIVE_PLACEHOLDER_WITHOUT_TEMPLATE_ID = 'CANNOT_INCLUDE_NATIVE_PLACEHOLDER_WITHOUT_TEMPLATE_ID';
    const INVALID_CLICK_TRACKING_LINE_ITEM_TYPE = 'INVALID_CLICK_TRACKING_LINE_ITEM_TYPE';
    const INVALID_TARGETING_FOR_CLICK_TRACKING = 'INVALID_TARGETING_FOR_CLICK_TRACKING';
    const NOT_SAME_RATE_CARD_PRICING_MODEL = 'NOT_SAME_RATE_CARD_PRICING_MODEL';
    const NOT_SAME_RATE_CARD_WORKFLOW = 'NOT_SAME_RATE_CARD_WORKFLOW';
    const INVALID_CONTRACTED_UNITS_BOUGHT = 'INVALID_CONTRACTED_UNITS_BOUGHT';
    const PLACEHOLDER_CANNOT_CONTAIN_LABELS = 'PLACEHOLDER_CANNOT_CONTAIN_LABELS';
    const INVALID_LABEL_TYPE_IN_PLACEHOLDER = 'INVALID_LABEL_TYPE_IN_PLACEHOLDER';
    const PLACEHOLDER_CANNOT_CONTAIN_NEGATED_LABELS = 'PLACEHOLDER_CANNOT_CONTAIN_NEGATED_LABELS';
    const MARKETPLACE_RATE_CARD_NOT_ALLOWED = 'MARKETPLACE_RATE_CARD_NOT_ALLOWED';
    const CANNOT_CREATE_FROM_PRODUCT = 'CANNOT_CREATE_FROM_PRODUCT';
    const CONTRACTED_UNITS_LESS_THAN_DELIVERED = 'CONTRACTED_UNITS_LESS_THAN_DELIVERED';
    const DISPLAY_ENVIRONMENT_MUST_HAVE_EXCLUDED_MOBILE_APPS_TARGETING = 'DISPLAY_ENVIRONMENT_MUST_HAVE_EXCLUDED_MOBILE_APPS_TARGETING';
    const MOBILE_ENVIRONMENT_MUST_HAVE_INCLUDED_MOBILE_APPS_TARGETING = 'MOBILE_ENVIRONMENT_MUST_HAVE_INCLUDED_MOBILE_APPS_TARGETING';
    const UNKNOWN = 'UNKNOWN';


}
