<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class RateCardErrorReason
{
    const INVALID_CURRENCY_CODE = 'INVALID_CURRENCY_CODE';
    const INVALID_PRICING_MODEL = 'INVALID_PRICING_MODEL';
    const PRODUCT_PACKAGE_NOT_APPLICABLE_ON_MARKETPLACE_RATE_CARD = 'PRODUCT_PACKAGE_NOT_APPLICABLE_ON_MARKETPLACE_RATE_CARD';
    const UNSUPPORTED_CURRENCY_CODE = 'UNSUPPORTED_CURRENCY_CODE';
    const UNCHANGEABLE_CURRENCY_CODE = 'UNCHANGEABLE_CURRENCY_CODE';
    const UNCHANGEABLE_PRICING_MODEL = 'UNCHANGEABLE_PRICING_MODEL';
    const MARKETPLACE_RATE_CARD_NOT_UNIQUE = 'MARKETPLACE_RATE_CARD_NOT_UNIQUE';
    const NOT_ACCEPT_DEALS_SALES_ON_LEGAL_AGREEMENT = 'NOT_ACCEPT_DEALS_SALES_ON_LEGAL_AGREEMENT';
    const UNKNOWN = 'UNKNOWN';


}
