<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ReservationDetailsErrorReason
{
    const UNLIMITED_UNITS_BOUGHT_NOT_ALLOWED = 'UNLIMITED_UNITS_BOUGHT_NOT_ALLOWED';
    const UNLIMITED_END_DATE_TIME_NOT_ALLOWED = 'UNLIMITED_END_DATE_TIME_NOT_ALLOWED';
    const PERCENTAGE_UNITS_BOUGHT_TOO_HIGH = 'PERCENTAGE_UNITS_BOUGHT_TOO_HIGH';
    const DURATION_NOT_ALLOWED = 'DURATION_NOT_ALLOWED';
    const UNIT_TYPE_NOT_ALLOWED = 'UNIT_TYPE_NOT_ALLOWED';
    const COST_TYPE_NOT_ALLOWED = 'COST_TYPE_NOT_ALLOWED';
    const COST_TYPE_UNIT_TYPE_MISMATCH_NOT_ALLOWED = 'COST_TYPE_UNIT_TYPE_MISMATCH_NOT_ALLOWED';
    const LINE_ITEM_TYPE_NOT_ALLOWED = 'LINE_ITEM_TYPE_NOT_ALLOWED';
    const NETWORK_REMNANT_ORDER_CANNOT_UPDATE_LINEITEM_TYPE = 'NETWORK_REMNANT_ORDER_CANNOT_UPDATE_LINEITEM_TYPE';
    const BACKFILL_WEBPROPERTY_CODE_NOT_ALLOWED = 'BACKFILL_WEBPROPERTY_CODE_NOT_ALLOWED';
    const UNKNOWN = 'UNKNOWN';


}
