<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class SetTopBoxCreativeErrorReason
{
    const EXTERNAL_ASSET_ID_IMMUTABLE = 'EXTERNAL_ASSET_ID_IMMUTABLE';
    const EXTERNAL_ASSET_ID_REQUIRED = 'EXTERNAL_ASSET_ID_REQUIRED';
    const PROVIDER_ID_IMMUTABLE = 'PROVIDER_ID_IMMUTABLE';
    const INVALID_THIRD_PARTY_TRACKING_URL_EVENT_TYPE = 'INVALID_THIRD_PARTY_TRACKING_URL_EVENT_TYPE';
    const UNKNOWN = 'UNKNOWN';


}
