<?php

namespace Google\AdsApi\Dfp\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class WorkflowActionErrorReason
{
    const NOT_APPLICABLE = 'NOT_APPLICABLE';
    const WORKFLOW_DEFINITION_NOT_FOUND = 'WORKFLOW_DEFINITION_NOT_FOUND';
    const EMPTY_ACTION_LIST = 'EMPTY_ACTION_LIST';
    const NOT_ACTION_APPROVER = 'NOT_ACTION_APPROVER';
    const WORKFLOW_ALREADY_COMPLETED = 'WORKFLOW_ALREADY_COMPLETED';
    const WORKFLOW_ALREADY_FAILED = 'WORKFLOW_ALREADY_FAILED';
    const WORKFLOW_ALREADY_CANCELED = 'WORKFLOW_ALREADY_CANCELED';
    const ACTION_COMPLETED = 'ACTION_COMPLETED';
    const ACTION_FAILED = 'ACTION_FAILED';
    const ACTION_CANCELED = 'ACTION_CANCELED';
    const ACTION_NOT_ACTIVE = 'ACTION_NOT_ACTIVE';
    const UNKNOWN = 'UNKNOWN';


}
