<?php

namespace Google\AdsApi\AdWords\v201802\mcm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class LabelServiceErrorReason
{
    const EMPTY_LABEL_NAME = 'EMPTY_LABEL_NAME';
    const LABEL_NAME_TOO_LONG = 'LABEL_NAME_TOO_LONG';
    const DUPLICATE_LABEL_NAME = 'DUPLICATE_LABEL_NAME';
    const RESERVED_LABEL_NAME = 'RESERVED_LABEL_NAME';
    const CANNOT_BE_DELETED = 'CANNOT_BE_DELETED';
    const TOO_MANY_LABELS = 'TOO_MANY_LABELS';
    const INVALID_LABEL_ID = 'INVALID_LABEL_ID';
    const CUSTOMER_CANNOT_CREATE_LABELS = 'CUSTOMER_CANNOT_CREATE_LABELS';
    const SERVER_CLIENT_VERSION_MISMATCH = 'SERVER_CLIENT_VERSION_MISMATCH';


}
