<?php

namespace Google\AdsApi\AdWords\v201802\mcm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ManagedCustomerServiceErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const NOT_AUTHORIZED = 'NOT_AUTHORIZED';
    const INVALID_SELECTOR = 'INVALID_SELECTOR';
    const INVALID_TIMEZONE = 'INVALID_TIMEZONE';
    const INVALID_CURRENCY = 'INVALID_CURRENCY';
    const INVALID_DESCRIPTIVE_NAME = 'INVALID_DESCRIPTIVE_NAME';
    const ADD_CUSTOMER_FAILURE = 'ADD_CUSTOMER_FAILURE';
    const SAVE_CUSTOMERS_FAILURE = 'SAVE_CUSTOMERS_FAILURE';
    const ALREADY_MANAGED_BY_THIS_MANAGER = 'ALREADY_MANAGED_BY_THIS_MANAGER';
    const ALREADY_INVITED_BY_THIS_MANAGER = 'ALREADY_INVITED_BY_THIS_MANAGER';
    const ALREADY_MANAGED_IN_HIERARCHY = 'ALREADY_MANAGED_IN_HIERARCHY';
    const ALREADY_MANAGED_FOR_UI_ACCESS = 'ALREADY_MANAGED_FOR_UI_ACCESS';
    const MAX_LINK_DEPTH_EXCEEDED = 'MAX_LINK_DEPTH_EXCEEDED';
    const NO_PENDING_INVITATION = 'NO_PENDING_INVITATION';
    const TOO_MANY_ACCOUNTS = 'TOO_MANY_ACCOUNTS';
    const TOO_MANY_ACCOUNTS_AT_MANAGER = 'TOO_MANY_ACCOUNTS_AT_MANAGER';
    const TOO_MANY_UI_API_MANAGERS = 'TOO_MANY_UI_API_MANAGERS';
    const TEST_ACCOUNT_LINK_ERROR = 'TEST_ACCOUNT_LINK_ERROR';
    const INVALID_LABEL_ID = 'INVALID_LABEL_ID';
    const CANNOT_APPLY_INACTIVE_LABEL = 'CANNOT_APPLY_INACTIVE_LABEL';
    const APPLIED_LABEL_TO_TOO_MANY_ACCOUNTS = 'APPLIED_LABEL_TO_TOO_MANY_ACCOUNTS';


}
