<?php

namespace Google\AdsApi\AdManager\v202502;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class McmErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const REVENUE_SHARE_PERCENT_OUTSIDE_RANGE = 'REVENUE_SHARE_PERCENT_OUTSIDE_RANGE';
    const RESELLER_PARENT_REVENUE_SHARE_IS_NOT_100_PERCENT = 'RESELLER_PARENT_REVENUE_SHARE_IS_NOT_100_PERCENT';
    const MI_PARENT_REVENUE_SHARE_IS_NOT_100_PERCENT = 'MI_PARENT_REVENUE_SHARE_IS_NOT_100_PERCENT';
    const DUPLICATE_CHILD_PUBLISHER_NETWORK_CODE = 'DUPLICATE_CHILD_PUBLISHER_NETWORK_CODE';
    const DUPLICATE_CHILD_PUBLISHER_ACTIVE_EMAIL = 'DUPLICATE_CHILD_PUBLISHER_ACTIVE_EMAIL';
    const CHILD_NETWORK_DISAPPROVED = 'CHILD_NETWORK_DISAPPROVED';
    const MANAGE_INVENTORY_UNSUPPORTED_IN_RESELLER_NETWORK = 'MANAGE_INVENTORY_UNSUPPORTED_IN_RESELLER_NETWORK';
    const CANNOT_SEND_INVITATION_TO_MCM_PARENT = 'CANNOT_SEND_INVITATION_TO_MCM_PARENT';
    const CANNOT_SEND_INVITATION_TO_NETWORK_WITH_RESELLER_PARENT = 'CANNOT_SEND_INVITATION_TO_NETWORK_WITH_RESELLER_PARENT';
    const CANNOT_SEND_INVITATION_TO_SELF = 'CANNOT_SEND_INVITATION_TO_SELF';
    const CANNOT_CLOSE_MCM_WITH_ACTIVE_CHILDREN = 'CANNOT_CLOSE_MCM_WITH_ACTIVE_CHILDREN';
    const CANNOT_TURN_CHILD_INTO_PARENT_WITH_ACTIVE_INVITATION = 'CANNOT_TURN_CHILD_INTO_PARENT_WITH_ACTIVE_INVITATION';
    const MISSING_NETWORK_EXCHANGE_ACCOUNT = 'MISSING_NETWORK_EXCHANGE_ACCOUNT';


}
