<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdUnitCodeErrorReason
{
    const INVALID_CHARACTERS = 'INVALID_CHARACTERS';
    const INVALID_CHARACTERS_WHEN_UTF_CHARACTERS_ARE_ALLOWED = 'INVALID_CHARACTERS_WHEN_UTF_CHARACTERS_ARE_ALLOWED';
    const LEADING_FORWARD_SLASH = 'LEADING_FORWARD_SLASH';
    const RESERVED_CODE = 'RESERVED_CODE';
    const UNKNOWN = 'UNKNOWN';


}
