<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BaseRateErrorReason
{
    const INVALID_CURRENCY_CODE = 'INVALID_CURRENCY_CODE';
    const PRODUCT_TEMPLATE_ARCHIVED = 'PRODUCT_TEMPLATE_ARCHIVED';
    const PRODUCT_PACKAGE_ITEM_ARCHIVED = 'PRODUCT_PACKAGE_ITEM_ARCHIVED';
    const CANNOT_QUERY_ON_MULTIPLE_TYPES = 'CANNOT_QUERY_ON_MULTIPLE_TYPES';
    const PRODUCT_PACKAGE_RATE_CARD_ASSOCIATION_MISSING = 'PRODUCT_PACKAGE_RATE_CARD_ASSOCIATION_MISSING';
    const UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION';
    const PRODUCT_PACKAGE_ACTIVE = 'PRODUCT_PACKAGE_ACTIVE';
    const PRODUCT_TEMPLATE_BASE_RATE_NOT_FOUND = 'PRODUCT_TEMPLATE_BASE_RATE_NOT_FOUND';
    const PRODUCT_BASE_RATE_EXISTS = 'PRODUCT_BASE_RATE_EXISTS';
    const INVALID_RATE_CARD_CHANNEL = 'INVALID_RATE_CARD_CHANNEL';
    const ZERO_MARKETPLACE_RATE_NOT_SUPPORTED = 'ZERO_MARKETPLACE_RATE_NOT_SUPPORTED';
    const UNKNOWN = 'UNKNOWN';


}
