<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BillingCap
{
    const NO_CAP = 'NO_CAP';
    const CAPPED_CUMULATIVE = 'CAPPED_CUMULATIVE';
    const CAPPED_PER_BILLING_CYCLE = 'CAPPED_PER_BILLING_CYCLE';
    const CAPPED_CUMULATIVE_PER_BILLING_CYCLE = 'CAPPED_CUMULATIVE_PER_BILLING_CYCLE';
    const CAPPED_WITH_ROLLOVER_PER_BILLING_CYCLE = 'CAPPED_WITH_ROLLOVER_PER_BILLING_CYCLE';
    const UNKNOWN = 'UNKNOWN';


}
