<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CompanyCreditStatusErrorReason
{
    const COMPANY_CREDIT_STATUS_CHANGE_NOT_ALLOWED = 'COMPANY_CREDIT_STATUS_CHANGE_NOT_ALLOWED';
    const CANNOT_USE_CREDIT_STATUS_SETTING = 'CANNOT_USE_CREDIT_STATUS_SETTING';
    const CANNOT_USE_ADVANCED_CREDIT_STATUS_SETTING = 'CANNOT_USE_ADVANCED_CREDIT_STATUS_SETTING';
    const UNACCEPTABLE_COMPANY_CREDIT_STATUS_FOR_ORDER = 'UNACCEPTABLE_COMPANY_CREDIT_STATUS_FOR_ORDER';
    const UNACCEPTABLE_COMPANY_CREDIT_STATUS_FOR_LINE_ITEM = 'UNACCEPTABLE_COMPANY_CREDIT_STATUS_FOR_LINE_ITEM';
    const CANNOT_BLOCK_COMPANY_TOO_MANY_APPROVED_ORDERS = 'CANNOT_BLOCK_COMPANY_TOO_MANY_APPROVED_ORDERS';
    const UNKNOWN = 'UNKNOWN';


}
