<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CreativeTemplateErrorReason
{
    const CANNOT_PARSE_CREATIVE_TEMPLATE = 'CANNOT_PARSE_CREATIVE_TEMPLATE';
    const VARIABLE_DUPLICATE_UNIQUE_NAME = 'VARIABLE_DUPLICATE_UNIQUE_NAME';
    const VARIABLE_INVALID_UNIQUE_NAME = 'VARIABLE_INVALID_UNIQUE_NAME';
    const LIST_CHOICE_DUPLICATE_VALUE = 'LIST_CHOICE_DUPLICATE_VALUE';
    const LIST_CHOICE_NEEDS_DEFAULT = 'LIST_CHOICE_NEEDS_DEFAULT';
    const LIST_CHOICES_EMPTY = 'LIST_CHOICES_EMPTY';
    const NO_TARGET_PLATFORMS = 'NO_TARGET_PLATFORMS';
    const MULTIPLE_TARGET_PLATFORMS = 'MULTIPLE_TARGET_PLATFORMS';
    const UNRECOGNIZED_PLACEHOLDER = 'UNRECOGNIZED_PLACEHOLDER';
    const PLACEHOLDERS_NOT_IN_FORMATTER = 'PLACEHOLDERS_NOT_IN_FORMATTER';
    const MISSING_INTERSTITIAL_MACRO = 'MISSING_INTERSTITIAL_MACRO';
    const UNKNOWN = 'UNKNOWN';


}
