<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CrossSellErrorReason
{
    const COMPANY_IS_NOT_DISTRIBUTION_PARTNER = 'COMPANY_IS_NOT_DISTRIBUTION_PARTNER';
    const CHANGING_PARTNER_NETWORK_IS_NOT_SUPPORTED = 'CHANGING_PARTNER_NETWORK_IS_NOT_SUPPORTED';
    const MISSING_DISTRIBUTOR_PARTNER_NAME = 'MISSING_DISTRIBUTOR_PARTNER_NAME';
    const DISTRIBUTOR_NETWORK_MISSING_PUBLISHER_FEATURE = 'DISTRIBUTOR_NETWORK_MISSING_PUBLISHER_FEATURE';
    const CONTENT_PROVIDER_NETWORK_MISSING_PUBLISHER_FEATURE = 'CONTENT_PROVIDER_NETWORK_MISSING_PUBLISHER_FEATURE';
    const INVALID_DISTRIBUTOR_PARTNER_NAME = 'INVALID_DISTRIBUTOR_PARTNER_NAME';
    const INVALID_CONTENT_PROVIDER_NETWORK = 'INVALID_CONTENT_PROVIDER_NETWORK';
    const CONTENT_PROVIDER_NETWORK_CANNOT_BE_ACTIVE_NETWORK = 'CONTENT_PROVIDER_NETWORK_CANNOT_BE_ACTIVE_NETWORK';
    const CONTENT_PROVIDER_NETWORK_ALREADY_ENABLED_FOR_CROSS_SELLING = 'CONTENT_PROVIDER_NETWORK_ALREADY_ENABLED_FOR_CROSS_SELLING';
    const DISTRIBUTOR_RULE_VIOLATION_ERROR = 'DISTRIBUTOR_RULE_VIOLATION_ERROR';
    const DISTRIBUTOR_RULE_VIOLATION_WARNING = 'DISTRIBUTOR_RULE_VIOLATION_WARNING';
    const UNKNOWN = 'UNKNOWN';


}
