<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class DateTimeRangeTargetingErrorReason
{
    const EMPTY_RANGES = 'EMPTY_RANGES';
    const NOT_SPONSORSHIP_LINEITEM = 'NOT_SPONSORSHIP_LINEITEM';
    const PAST_RANGES_CHANGED = 'PAST_RANGES_CHANGED';
    const RANGES_OVERLAP = 'RANGES_OVERLAP';
    const RANGES_OUT_OF_LINEITEM_ACTIVE_PERIOD = 'RANGES_OUT_OF_LINEITEM_ACTIVE_PERIOD';
    const START_TIME_IS_NOT_START_OF_DAY = 'START_TIME_IS_NOT_START_OF_DAY';
    const END_TIME_IS_NOT_END_OF_DAY = 'END_TIME_IS_NOT_END_OF_DAY';
    const START_DATE_TIME_IS_IN_PAST = 'START_DATE_TIME_IS_IN_PAST';
    const RANGE_END_TIME_BEFORE_START_TIME = 'RANGE_END_TIME_BEFORE_START_TIME';
    const END_DATE_TIME_IS_TOO_LATE = 'END_DATE_TIME_IS_TOO_LATE';
    const LIMITED_RANGES_IN_UNLIMITED_LINEITEM = 'LIMITED_RANGES_IN_UNLIMITED_LINEITEM';
    const UNKNOWN = 'UNKNOWN';


}
