<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class InventoryTargetingErrorReason
{
    const AT_LEAST_ONE_PLACEMENT_OR_INVENTORY_UNIT_REQUIRED = 'AT_LEAST_ONE_PLACEMENT_OR_INVENTORY_UNIT_REQUIRED';
    const INVENTORY_CANNOT_BE_TARGETED_AND_EXCLUDED = 'INVENTORY_CANNOT_BE_TARGETED_AND_EXCLUDED';
    const INVENTORY_UNIT_CANNOT_BE_TARGETED_IF_ANCESTOR_IS_TARGETED = 'INVENTORY_UNIT_CANNOT_BE_TARGETED_IF_ANCESTOR_IS_TARGETED';
    const INVENTORY_UNIT_CANNOT_BE_TARGETED_IF_ANCESTOR_IS_EXCLUDED = 'INVENTORY_UNIT_CANNOT_BE_TARGETED_IF_ANCESTOR_IS_EXCLUDED';
    const INVENTORY_UNIT_CANNOT_BE_EXCLUDED_IF_ANCESTOR_IS_EXCLUDED = 'INVENTORY_UNIT_CANNOT_BE_EXCLUDED_IF_ANCESTOR_IS_EXCLUDED';
    const EXPLICITLY_TARGETED_INVENTORY_UNIT_CANNOT_BE_TARGETED = 'EXPLICITLY_TARGETED_INVENTORY_UNIT_CANNOT_BE_TARGETED';
    const EXPLICITLY_TARGETED_INVENTORY_UNIT_CANNOT_BE_EXCLUDED = 'EXPLICITLY_TARGETED_INVENTORY_UNIT_CANNOT_BE_EXCLUDED';
    const SELF_ONLY_INVENTORY_UNIT_NOT_ALLOWED = 'SELF_ONLY_INVENTORY_UNIT_NOT_ALLOWED';
    const SELF_ONLY_INVENTORY_UNIT_WITHOUT_DESCENDANTS = 'SELF_ONLY_INVENTORY_UNIT_WITHOUT_DESCENDANTS';
    const YOUTUBE_AUDIENCE_SEGMENTS_CAN_ONLY_BE_TARGETED_WITH_YOUTUBE_SHARED_INVENTORY = 'YOUTUBE_AUDIENCE_SEGMENTS_CAN_ONLY_BE_TARGETED_WITH_YOUTUBE_SHARED_INVENTORY';
    const UNKNOWN = 'UNKNOWN';


}
