<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class InventoryUnitErrorReason
{
    const EXPLICIT_TARGETING_NOT_ALLOWED = 'EXPLICIT_TARGETING_NOT_ALLOWED';
    const TARGET_PLATFORM_NOT_APPLICABLE = 'TARGET_PLATFORM_NOT_APPLICABLE';
    const ADSENSE_CANNOT_BE_ENABLED = 'ADSENSE_CANNOT_BE_ENABLED';
    const ROOT_UNIT_CANNOT_BE_DEACTIVATED = 'ROOT_UNIT_CANNOT_BE_DEACTIVATED';
    const UNKNOWN = 'UNKNOWN';


}
