<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class NetworkErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const MULTI_CURRENCY_NOT_SUPPORTED = 'MULTI_CURRENCY_NOT_SUPPORTED';
    const UNSUPPORTED_CURRENCY = 'UNSUPPORTED_CURRENCY';
    const NETWORK_CURRENCY_CANNOT_BE_SAME_AS_SECONDARY = 'NETWORK_CURRENCY_CANNOT_BE_SAME_AS_SECONDARY';
    const CANNOT_DELETE_CURRENCY_WITH_ACTIVE_RATE_CARDS = 'CANNOT_DELETE_CURRENCY_WITH_ACTIVE_RATE_CARDS';


}
