<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class PoddingErrorReason
{
    const INVALID_PODDING_TYPE_NONE = 'INVALID_PODDING_TYPE_NONE';
    const INVALID_PODDING_TYPE_STANDARD = 'INVALID_PODDING_TYPE_STANDARD';
    const INVALID_OPTIMIZED_POD_WITHOUT_DURATION = 'INVALID_OPTIMIZED_POD_WITHOUT_DURATION';
    const INVALID_OPTIMIZED_POD_WITHOUT_ADS = 'INVALID_OPTIMIZED_POD_WITHOUT_ADS';
    const INVALID_POD_DURATION_RANGE = 'INVALID_POD_DURATION_RANGE';


}
