<?php

namespace Google\AdsApi\AdManager\v201808;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProgrammaticEntitiesErrorReason
{
    const INVALID_RATE_TYPE = 'INVALID_RATE_TYPE';
    const INVALID_ENVIRONMENT_TYPE = 'INVALID_ENVIRONMENT_TYPE';
    const INVALID_PRODUCT_TYPE = 'INVALID_PRODUCT_TYPE';
    const INVALID_LINE_ITEM_TYPE = 'INVALID_LINE_ITEM_TYPE';
    const INVALID_ROADBLOCKING_TYPE = 'INVALID_ROADBLOCKING_TYPE';
    const INVALID_DELIVERY_RATE_TYPE = 'INVALID_DELIVERY_RATE_TYPE';
    const INVALID_COMPANION_DELIVERY_OPTION = 'INVALID_COMPANION_DELIVERY_OPTION';
    const INVALID_CREATIVE_ROTATION_TYPE = 'INVALID_CREATIVE_ROTATION_TYPE';
    const INVALID_COMPANION_CREATIVE_PLACEHOLDER = 'INVALID_COMPANION_CREATIVE_PLACEHOLDER';
    const EMPTY_CREATIVE_PLACEHOLDER = 'EMPTY_CREATIVE_PLACEHOLDER';
    const UNKNOWN = 'UNKNOWN';


}
