<?php

namespace Google\AdsApi\AdWords\v201802\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdGroupAdErrorReason
{
    const AD_GROUP_AD_LABEL_DOES_NOT_EXIST = 'AD_GROUP_AD_LABEL_DOES_NOT_EXIST';
    const AD_GROUP_AD_LABEL_ALREADY_EXISTS = 'AD_GROUP_AD_LABEL_ALREADY_EXISTS';
    const AD_NOT_UNDER_ADGROUP = 'AD_NOT_UNDER_ADGROUP';
    const CANNOT_OPERATE_ON_REMOVED_ADGROUPAD = 'CANNOT_OPERATE_ON_REMOVED_ADGROUPAD';
    const CANNOT_CREATE_DEPRECATED_ADS = 'CANNOT_CREATE_DEPRECATED_ADS';
    const CANNOT_CREATE_TEXT_ADS = 'CANNOT_CREATE_TEXT_ADS';
    const EMPTY_FIELD = 'EMPTY_FIELD';
    const ENTITY_REFERENCED_IN_MULTIPLE_OPS = 'ENTITY_REFERENCED_IN_MULTIPLE_OPS';
    const UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION';


}
