<?php

namespace Google\AdsApi\AdWords\v201802\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class FeedItemTargetErrorReason
{
    const CRITERION_TYPE_NOT_SUPPORTED = 'CRITERION_TYPE_NOT_SUPPORTED';
    const FEED_ITEM_TARGET_ALREADY_EXISTS = 'FEED_ITEM_TARGET_ALREADY_EXISTS';
    const NEGATIVE_TARGETING_NOT_SUPPORTED_FOR_CRITERION_TYPE = 'NEGATIVE_TARGETING_NOT_SUPPORTED_FOR_CRITERION_TYPE';
    const ONLY_MOBILE_TARGETING_IS_SUPPORTED_FOR_PLATFORM_CRITERION = 'ONLY_MOBILE_TARGETING_IS_SUPPORTED_FOR_PLATFORM_CRITERION';
    const FEED_ITEM_SCHEDULES_CANNOT_OVERLAP = 'FEED_ITEM_SCHEDULES_CANNOT_OVERLAP';
    const CRITERION_ID_MUST_BE_SET_FOR_GIVEN_TYPE = 'CRITERION_ID_MUST_BE_SET_FOR_GIVEN_TYPE';
    const TARGET_LIMIT_EXCEEDED_FOR_GIVEN_TYPE = 'TARGET_LIMIT_EXCEEDED_FOR_GIVEN_TYPE';
    const TOO_MANY_SCHEDULES_PER_DAY = 'TOO_MANY_SCHEDULES_PER_DAY';
    const CANNOT_HAVE_ACTIVE_CAMPAIGN_AND_ACTIVE_AD_GROUP_TARGETS = 'CANNOT_HAVE_ACTIVE_CAMPAIGN_AND_ACTIVE_AD_GROUP_TARGETS';
    const UNKNOWN = 'UNKNOWN';


}
