<?php

namespace Google\AdsApi\AdWords\v201802\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class FunctionParsingErrorReason
{
    const NO_MORE_INPUT = 'NO_MORE_INPUT';
    const EXPECTED_CHARACTER = 'EXPECTED_CHARACTER';
    const UNEXPECTED_SEPARATOR = 'UNEXPECTED_SEPARATOR';
    const UNMATCHED_LEFT_BRACKET = 'UNMATCHED_LEFT_BRACKET';
    const UNMATCHED_RIGHT_BRACKET = 'UNMATCHED_RIGHT_BRACKET';
    const TOO_MANY_NESTED_FUNCTIONS = 'TOO_MANY_NESTED_FUNCTIONS';
    const MISSING_RIGHT_HAND_OPERAND = 'MISSING_RIGHT_HAND_OPERAND';
    const INVALID_OPERATOR_NAME = 'INVALID_OPERATOR_NAME';
    const FEED_ATTRIBUTE_OPERAND_ARGUMENT_NOT_INTEGER = 'FEED_ATTRIBUTE_OPERAND_ARGUMENT_NOT_INTEGER';
    const NO_OPERANDS = 'NO_OPERANDS';
    const TOO_MANY_OPERANDS = 'TOO_MANY_OPERANDS';
    const UNKNOWN = 'UNKNOWN';


}
