<?php

namespace Google\AdsApi\AdWords\v201802\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ImageErrorReason
{
    const INVALID_IMAGE = 'INVALID_IMAGE';
    const STORAGE_ERROR = 'STORAGE_ERROR';
    const BAD_REQUEST = 'BAD_REQUEST';
    const UNEXPECTED_SIZE = 'UNEXPECTED_SIZE';
    const ANIMATED_NOT_ALLOWED = 'ANIMATED_NOT_ALLOWED';
    const ANIMATION_TOO_LONG = 'ANIMATION_TOO_LONG';
    const SERVER_ERROR = 'SERVER_ERROR';
    const CMYK_JPEG_NOT_ALLOWED = 'CMYK_JPEG_NOT_ALLOWED';
    const FLASH_NOT_ALLOWED = 'FLASH_NOT_ALLOWED';
    const FLASH_WITHOUT_CLICKTAG = 'FLASH_WITHOUT_CLICKTAG';
    const FLASH_ERROR_AFTER_FIXING_CLICK_TAG = 'FLASH_ERROR_AFTER_FIXING_CLICK_TAG';
    const ANIMATED_VISUAL_EFFECT = 'ANIMATED_VISUAL_EFFECT';
    const FLASH_ERROR = 'FLASH_ERROR';
    const LAYOUT_PROBLEM = 'LAYOUT_PROBLEM';
    const PROBLEM_READING_IMAGE_FILE = 'PROBLEM_READING_IMAGE_FILE';
    const ERROR_STORING_IMAGE = 'ERROR_STORING_IMAGE';
    const ASPECT_RATIO_NOT_ALLOWED = 'ASPECT_RATIO_NOT_ALLOWED';
    const FLASH_HAS_NETWORK_OBJECTS = 'FLASH_HAS_NETWORK_OBJECTS';
    const FLASH_HAS_NETWORK_METHODS = 'FLASH_HAS_NETWORK_METHODS';
    const FLASH_HAS_URL = 'FLASH_HAS_URL';
    const FLASH_HAS_MOUSE_TRACKING = 'FLASH_HAS_MOUSE_TRACKING';
    const FLASH_HAS_RANDOM_NUM = 'FLASH_HAS_RANDOM_NUM';
    const FLASH_SELF_TARGETS = 'FLASH_SELF_TARGETS';
    const FLASH_BAD_GETURL_TARGET = 'FLASH_BAD_GETURL_TARGET';
    const FLASH_VERSION_NOT_SUPPORTED = 'FLASH_VERSION_NOT_SUPPORTED';
    const FLASH_WITHOUT_HARD_CODED_CLICK_URL = 'FLASH_WITHOUT_HARD_CODED_CLICK_URL';
    const INVALID_FLASH_FILE = 'INVALID_FLASH_FILE';
    const FAILED_TO_FIX_CLICK_TAG_IN_FLASH = 'FAILED_TO_FIX_CLICK_TAG_IN_FLASH';
    const FLASH_ACCESSES_NETWORK_RESOURCES = 'FLASH_ACCESSES_NETWORK_RESOURCES';
    const FLASH_EXTERNAL_JS_CALL = 'FLASH_EXTERNAL_JS_CALL';
    const FLASH_EXTERNAL_FS_CALL = 'FLASH_EXTERNAL_FS_CALL';
    const FILE_TOO_LARGE = 'FILE_TOO_LARGE';
    const IMAGE_DATA_TOO_LARGE = 'IMAGE_DATA_TOO_LARGE';
    const IMAGE_PROCESSING_ERROR = 'IMAGE_PROCESSING_ERROR';
    const IMAGE_TOO_SMALL = 'IMAGE_TOO_SMALL';
    const INVALID_INPUT = 'INVALID_INPUT';
    const PROBLEM_READING_FILE = 'PROBLEM_READING_FILE';


}
