<?php

namespace Google\AdsApi\AdWords\v201802\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class OperationAccessDeniedReason
{
    const ACTION_NOT_PERMITTED = 'ACTION_NOT_PERMITTED';
    const ADD_OPERATION_NOT_PERMITTED = 'ADD_OPERATION_NOT_PERMITTED';
    const REMOVE_OPERATION_NOT_PERMITTED = 'REMOVE_OPERATION_NOT_PERMITTED';
    const SET_OPERATION_NOT_PERMITTED = 'SET_OPERATION_NOT_PERMITTED';
    const MUTATE_ACTION_NOT_PERMITTED_FOR_CLIENT = 'MUTATE_ACTION_NOT_PERMITTED_FOR_CLIENT';
    const OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE = 'OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE';
    const ADD_AS_REMOVED_NOT_PERMITTED = 'ADD_AS_REMOVED_NOT_PERMITTED';
    const OPERATION_NOT_PERMITTED_FOR_REMOVED_ENTITY = 'OPERATION_NOT_PERMITTED_FOR_REMOVED_ENTITY';
    const OPERATION_NOT_PERMITTED_FOR_AD_GROUP_TYPE = 'OPERATION_NOT_PERMITTED_FOR_AD_GROUP_TYPE';
    const UNKNOWN = 'UNKNOWN';


}
