<?php

namespace Google\AdsApi\AdWords\v201802\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class PerformanceTargetStatus
{
    const UNKNOWN = 'UNKNOWN';
    const ACTIVE_NEEDS_ATTENTION = 'ACTIVE_NEEDS_ATTENTION';
    const ACTIVE_ON_TRACK = 'ACTIVE_ON_TRACK';
    const ACTIVE_TARGET_MET = 'ACTIVE_TARGET_MET';
    const ACTIVE_INCONCLUSIVE = 'ACTIVE_INCONCLUSIVE';
    const ACTIVE_NO_TARGETS = 'ACTIVE_NO_TARGETS';
    const PAST_TARGET_MISSED = 'PAST_TARGET_MISSED';
    const PAST_TARGET_MET = 'PAST_TARGET_MET';
    const PAST_INCONCLUSIVE = 'PAST_INCONCLUSIVE';
    const PAST_MISSING_DATA = 'PAST_MISSING_DATA';
    const PAST_NO_TARGETS = 'PAST_NO_TARGETS';
    const NOT_YET_STARTED = 'NOT_YET_STARTED';


}
