<?php

namespace Google\AdsApi\AdWords\v201802\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class QueryErrorReason
{
    const PARSING_FAILED = 'PARSING_FAILED';
    const MISSING_QUERY = 'MISSING_QUERY';
    const MISSING_SELECT_CLAUSE = 'MISSING_SELECT_CLAUSE';
    const MISSING_FROM_CLAUSE = 'MISSING_FROM_CLAUSE';
    const INVALID_SELECT_CLAUSE = 'INVALID_SELECT_CLAUSE';
    const INVALID_FROM_CLAUSE = 'INVALID_FROM_CLAUSE';
    const INVALID_WHERE_CLAUSE = 'INVALID_WHERE_CLAUSE';
    const INVALID_ORDER_BY_CLAUSE = 'INVALID_ORDER_BY_CLAUSE';
    const INVALID_LIMIT_CLAUSE = 'INVALID_LIMIT_CLAUSE';
    const INVALID_START_INDEX_IN_LIMIT_CLAUSE = 'INVALID_START_INDEX_IN_LIMIT_CLAUSE';
    const INVALID_PAGE_SIZE_IN_LIMIT_CLAUSE = 'INVALID_PAGE_SIZE_IN_LIMIT_CLAUSE';
    const INVALID_DURING_CLAUSE = 'INVALID_DURING_CLAUSE';
    const INVALID_MIN_DATE_IN_DURING_CLAUSE = 'INVALID_MIN_DATE_IN_DURING_CLAUSE';
    const INVALID_MAX_DATE_IN_DURING_CLAUSE = 'INVALID_MAX_DATE_IN_DURING_CLAUSE';
    const MAX_LESS_THAN_MIN_IN_DURING_CLAUSE = 'MAX_LESS_THAN_MIN_IN_DURING_CLAUSE';
    const VALIDATION_FAILED = 'VALIDATION_FAILED';


}
