<?php

namespace Google\AdsApi\AdWords\v201802\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class SharedCriterionErrorReason
{
    const EXCEEDS_CRITERIA_LIMIT = 'EXCEEDS_CRITERIA_LIMIT';
    const INCORRECT_CRITERION_TYPE = 'INCORRECT_CRITERION_TYPE';
    const CANNOT_TARGET_AND_EXCLUDE = 'CANNOT_TARGET_AND_EXCLUDE';
    const NEGATIVE_CRITERION_REQUIRED = 'NEGATIVE_CRITERION_REQUIRED';
    const CONCRETE_TYPE_REQUIRED = 'CONCRETE_TYPE_REQUIRED';
    const UNKNOWN = 'UNKNOWN';


}
