<?php

namespace Google\AdsApi\AdManager\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class HtmlBundleProcessorErrorReason
{
    const CANNOT_EXTRACT_FILES_FROM_BUNDLE = 'CANNOT_EXTRACT_FILES_FROM_BUNDLE';
    const CLICK_TAG_HARD_CODED = 'CLICK_TAG_HARD_CODED';
    const CLICK_TAG_IN_GWD_UNUPPORTED = 'CLICK_TAG_IN_GWD_UNUPPORTED';
    const CLICK_TAG_NOT_IN_PRIMARY_HTML = 'CLICK_TAG_NOT_IN_PRIMARY_HTML';
    const CLICK_TAG_INVALID = 'CLICK_TAG_INVALID';
    const FILE_SIZE_TOO_LARGE = 'FILE_SIZE_TOO_LARGE';
    const FILES_TOO_MANY = 'FILES_TOO_MANY';
    const FLASH_UNSUPPORTED = 'FLASH_UNSUPPORTED';
    const GWD_COMPONENTS_UNSUPPORTED = 'GWD_COMPONENTS_UNSUPPORTED';
    const GWD_ENABLER_METHODS_UNSUPPORTED = 'GWD_ENABLER_METHODS_UNSUPPORTED';
    const GWD_PROPERTIES_INVALID = 'GWD_PROPERTIES_INVALID';
    const LINKED_FILES_NOT_FOUND = 'LINKED_FILES_NOT_FOUND';
    const PRIMARY_HTML_MISSING = 'PRIMARY_HTML_MISSING';
    const PRIMARY_HTML_UNDETERMINED = 'PRIMARY_HTML_UNDETERMINED';
    const SVG_BLOCK_INVALID = 'SVG_BLOCK_INVALID';
    const UNKNOWN = 'UNKNOWN';


}
