<?php

namespace Google\AdsApi\AdManager\v201802;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class PlacementErrorReason
{
    const INVALID_ENTITY_TYPE = 'INVALID_ENTITY_TYPE';
    const SHARED_INVENTORY_ASSIGNED = 'SHARED_INVENTORY_ASSIGNED';
    const PLACEMENTS_CANNOT_INCLUDE_INVENTORY_FROM_MULTIPLE_DISTRIBUTOR_NETWORKS = 'PLACEMENTS_CANNOT_INCLUDE_INVENTORY_FROM_MULTIPLE_DISTRIBUTOR_NETWORKS';
    const PLACEMENTS_CANNOT_INCLUDE_BOTH_LOCAL_AND_SHARED_INVENTORY = 'PLACEMENTS_CANNOT_INCLUDE_BOTH_LOCAL_AND_SHARED_INVENTORY';
    const UNKNOWN = 'UNKNOWN';


}
