<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdParamErrorReason
{
    const AD_PARAM_CANNOT_BE_SPECIFIED_MULTIPLE_TIMES = 'AD_PARAM_CANNOT_BE_SPECIFIED_MULTIPLE_TIMES';
    const AD_PARAM_DOES_NOT_EXIST = 'AD_PARAM_DOES_NOT_EXIST';
    const CRITERION_SPECIFIED_MUST_BE_KEYWORD = 'CRITERION_SPECIFIED_MUST_BE_KEYWORD';
    const INVALID_ADGROUP_CRITERION_SPECIFIED = 'INVALID_ADGROUP_CRITERION_SPECIFIED';
    const INVALID_INSERTION_TEXT_FORMAT = 'INVALID_INSERTION_TEXT_FORMAT';
    const MUST_SPECIFY_ADGROUP_ID = 'MUST_SPECIFY_ADGROUP_ID';
    const UNKNOWN = 'UNKNOWN';


}
