<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AudioErrorReason
{
    const INVALID_AUDIO = 'INVALID_AUDIO';
    const PROBLEM_READING_AUDIO_FILE = 'PROBLEM_READING_AUDIO_FILE';
    const ERROR_STORING_AUDIO = 'ERROR_STORING_AUDIO';
    const FILE_TOO_LARGE = 'FILE_TOO_LARGE';
    const UNSUPPORTED_AUDIO = 'UNSUPPORTED_AUDIO';
    const ERROR_GENERATING_STREAMING_URL = 'ERROR_GENERATING_STREAMING_URL';


}
