<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BatchJobOpsService extends \Google\AdsApi\Common\AdsSoapClient
{

    /**
     * @var array $classmap The defined classes
     */
    private static $classmap = array (
      'Ad' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Ad',
      'AdCustomizerError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdCustomizerError',
      'AdError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdError',
      'AdGroup' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroup',
      'AdGroupAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupAd',
      'AdGroupAdCountLimitExceeded' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupAdCountLimitExceeded',
      'AdGroupAdError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupAdError',
      'AdGroupAdLabel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupAdLabel',
      'AdGroupAdLabelOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupAdLabelOperation',
      'AdGroupAdOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupAdOperation',
      'AdGroupAdPolicySummary' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupAdPolicySummary',
      'AdGroupAdRotationMode' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupAdRotationMode',
      'AdGroupBidModifier' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupBidModifier',
      'AdGroupBidModifierOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupBidModifierOperation',
      'AdGroupCriterion' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupCriterion',
      'AdGroupCriterionError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupCriterionError',
      'AdGroupCriterionLabel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupCriterionLabel',
      'AdGroupCriterionLabelOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupCriterionLabelOperation',
      'AdGroupCriterionLimitExceeded' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupCriterionLimitExceeded',
      'AdGroupCriterionOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupCriterionOperation',
      'AdGroupExtensionSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupExtensionSetting',
      'AdGroupExtensionSettingOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupExtensionSettingOperation',
      'AdGroupLabel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupLabel',
      'AdGroupLabelOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupLabelOperation',
      'AdGroupOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupOperation',
      'AdGroupServiceError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdGroupServiceError',
      'AdSchedule' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdSchedule',
      'AdSharingError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdSharingError',
      'AdUnionId' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdUnionId',
      'Address' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Address',
      'AdxError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AdxError',
      'AgeRange' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AgeRange',
      'ApiError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ApiError',
      'ApiException' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ApiException',
      'AppFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AppFeedItem',
      'AppPaymentModel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AppPaymentModel',
      'AppUrl' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AppUrl',
      'AppUrlList' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AppUrlList',
      'ApplicationException' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ApplicationException',
      'LabelAttribute' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\LabelAttribute',
      'Audio' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Audio',
      'AuthenticationError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AuthenticationError',
      'AuthorizationError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\AuthorizationError',
      'Bid' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Bid',
      'BiddableAdGroupCriterion' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\BiddableAdGroupCriterion',
      'BiddingErrors' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\BiddingErrors',
      'BiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\BiddingScheme',
      'BiddingStrategyConfiguration' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\BiddingStrategyConfiguration',
      'Bids' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Bids',
      'Budget' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Budget',
      'BudgetError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\BudgetError',
      'BudgetOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\BudgetOperation',
      'CallConversionType' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CallConversionType',
      'CallFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CallFeedItem',
      'CallOnlyAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CallOnlyAd',
      'CalloutFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CalloutFeedItem',
      'Campaign' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Campaign',
      'CampaignCriterion' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignCriterion',
      'CampaignCriterionError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignCriterionError',
      'CampaignCriterionOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignCriterionOperation',
      'CampaignError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignError',
      'CampaignExtensionSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignExtensionSetting',
      'CampaignExtensionSettingOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignExtensionSettingOperation',
      'CampaignLabel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignLabel',
      'CampaignLabelOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignLabelOperation',
      'TextLabel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TextLabel',
      'DisplayAttribute' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DisplayAttribute',
      'CampaignOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignOperation',
      'CampaignSharedSet' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignSharedSet',
      'CampaignSharedSetError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignSharedSetError',
      'CampaignSharedSetOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CampaignSharedSetOperation',
      'Carrier' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Carrier',
      'ClientTermsError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ClientTermsError',
      'CollectionSizeError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CollectionSizeError',
      'ComparableValue' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ComparableValue',
      'ConstantOperand' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ConstantOperand',
      'ContentLabel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ContentLabel',
      'ConversionOptimizerEligibility' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ConversionOptimizerEligibility',
      'CountryConstraint' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CountryConstraint',
      'CpaBid' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CpaBid',
      'CpcBid' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CpcBid',
      'CpmBid' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CpmBid',
      'Criterion' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Criterion',
      'CriterionError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CriterionError',
      'CriterionParameter' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CriterionParameter',
      'CriterionPolicyError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CriterionPolicyError',
      'CustomParameter' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CustomParameter',
      'CustomParameters' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CustomParameters',
      'CustomerExtensionSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CustomerExtensionSetting',
      'CustomerExtensionSettingOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CustomerExtensionSettingOperation',
      'DatabaseError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DatabaseError',
      'DateError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DateError',
      'DateRangeError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DateRangeError',
      'DeprecatedAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DeprecatedAd',
      'Dimensions' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Dimensions',
      'DisapprovalReason' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DisapprovalReason',
      'DistinctError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DistinctError',
      'DoubleValue' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DoubleValue',
      'DynamicSearchAdsSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DynamicSearchAdsSetting',
      'DynamicSettings' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DynamicSettings',
      'EnhancedCpcBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\EnhancedCpcBiddingScheme',
      'EntityAccessDenied' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\EntityAccessDenied',
      'EntityCountLimitExceeded' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\EntityCountLimitExceeded',
      'EntityNotFound' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\EntityNotFound',
      'ErrorList' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ErrorList',
      'ExemptionRequest' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ExemptionRequest',
      'ExpandedDynamicSearchAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ExpandedDynamicSearchAd',
      'ExpandedTextAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ExpandedTextAd',
      'ExplorerAutoOptimizerSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ExplorerAutoOptimizerSetting',
      'ExtensionFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ExtensionFeedItem',
      'ExtensionSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ExtensionSetting',
      'ExtensionSettingError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ExtensionSettingError',
      'FeedAttributeReferenceError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedAttributeReferenceError',
      'FeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItem',
      'FeedItemAdGroupTargeting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemAdGroupTargeting',
      'FeedItemAttributeError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemAttributeError',
      'FeedItemAttributeValue' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemAttributeValue',
      'FeedItemCampaignTargeting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemCampaignTargeting',
      'FeedItemDevicePreference' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemDevicePreference',
      'FeedItemError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemError',
      'FeedItemGeoRestriction' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemGeoRestriction',
      'FeedItemOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemOperation',
      'FeedItemPolicyData' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemPolicyData',
      'FeedItemSchedule' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemSchedule',
      'FeedItemScheduling' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FeedItemScheduling',
      'FieldPathElement' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FieldPathElement',
      'ForwardCompatibilityError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ForwardCompatibilityError',
      'FrequencyCap' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FrequencyCap',
      'Function' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MatchingFunction',
      'FunctionError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FunctionError',
      'FunctionParsingError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FunctionParsingError',
      'Gender' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Gender',
      'GeoPoint' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\GeoPoint',
      'GeoTargetOperand' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\GeoTargetOperand',
      'GeoTargetTypeSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\GeoTargetTypeSetting',
      'IdError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\IdError',
      'Image' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Image',
      'ImageAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ImageAd',
      'ImageError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ImageError',
      'IncomeOperand' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\IncomeOperand',
      'IncomeRange' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\IncomeRange',
      'InternalApiError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\InternalApiError',
      'IpBlock' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\IpBlock',
      'Keyword' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Keyword',
      'Label' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Label',
      'Language' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Language',
      'ListError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ListError',
      'ListOperations' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ListOperations',
      'Location' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Location',
      'LocationExtensionOperand' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\LocationExtensionOperand',
      'LongValue' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\LongValue',
      'ManualCpcBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ManualCpcBiddingScheme',
      'ManualCpmBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ManualCpmBiddingScheme',
      'MaximizeConversionsBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MaximizeConversionsBiddingScheme',
      'Media' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Media',
      'MediaBundle' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MediaBundle',
      'MediaBundleError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MediaBundleError',
      'MediaError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MediaError',
      'Media_Size_DimensionsMapEntry' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Media_Size_DimensionsMapEntry',
      'Media_Size_StringMapEntry' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Media_Size_StringMapEntry',
      'MessageFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MessageFeedItem',
      'MobileAppCategory' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MobileAppCategory',
      'MobileApplication' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MobileApplication',
      'MobileDevice' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MobileDevice',
      'Money' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Money',
      'MoneyWithCurrency' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MoneyWithCurrency',
      'UniversalAppCampaignSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\UniversalAppCampaignSetting',
      'MultiplierError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MultiplierError',
      'MutateResult' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\MutateResult',
      'NegativeAdGroupCriterion' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\NegativeAdGroupCriterion',
      'NegativeCampaignCriterion' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\NegativeCampaignCriterion',
      'NetworkSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\NetworkSetting',
      'NewEntityCreationError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\NewEntityCreationError',
      'NotEmptyError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\NotEmptyError',
      'NullError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\NullError',
      'NumberValue' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\NumberValue',
      'FunctionArgumentOperand' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\FunctionArgumentOperand',
      'Operand' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Operand',
      'OperatingSystemVersion' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\OperatingSystemVersion',
      'Operation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Operation',
      'OperationAccessDenied' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\OperationAccessDenied',
      'OperatorError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\OperatorError',
      'PageFeed' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PageFeed',
      'PageOnePromotedBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PageOnePromotedBiddingScheme',
      'PagingError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PagingError',
      'Parent' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ParentCriterion',
      'Placement' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Placement',
      'PlacesOfInterestOperand' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PlacesOfInterestOperand',
      'Platform' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Platform',
      'PolicyData' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PolicyData',
      'PolicyTopicConstraint' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PolicyTopicConstraint',
      'PolicyTopicEntry' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PolicyTopicEntry',
      'PolicyTopicEvidence' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PolicyTopicEvidence',
      'PolicyViolationError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PolicyViolationError',
      'PolicyViolationError.Part' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PolicyViolationErrorPart',
      'PolicyViolationKey' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PolicyViolationKey',
      'PriceFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PriceFeedItem',
      'PriceTableRow' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PriceTableRow',
      'ProductAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductAd',
      'ProductAdwordsGrouping' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductAdwordsGrouping',
      'ProductAdwordsLabels' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductAdwordsLabels',
      'ProductBiddingCategory' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductBiddingCategory',
      'ProductBrand' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductBrand',
      'ProductCanonicalCondition' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductCanonicalCondition',
      'ProductChannel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductChannel',
      'ProductChannelExclusivity' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductChannelExclusivity',
      'ProductLegacyCondition' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductLegacyCondition',
      'ProductCustomAttribute' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductCustomAttribute',
      'ProductDimension' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductDimension',
      'ProductOfferId' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductOfferId',
      'ProductPartition' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductPartition',
      'ProductScope' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductScope',
      'ProductType' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductType',
      'ProductTypeFull' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ProductTypeFull',
      'PromotionFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\PromotionFeedItem',
      'Proximity' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Proximity',
      'QualityInfo' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\QualityInfo',
      'QueryError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\QueryError',
      'QuotaCheckError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\QuotaCheckError',
      'RangeError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\RangeError',
      'RateExceededError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\RateExceededError',
      'ReadOnlyError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ReadOnlyError',
      'RealTimeBiddingSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\RealTimeBiddingSetting',
      'RegionCodeError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\RegionCodeError',
      'RejectedError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\RejectedError',
      'RequestError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\RequestError',
      'RequiredError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\RequiredError',
      'ResponsiveDisplayAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ResponsiveDisplayAd',
      'ReviewFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ReviewFeedItem',
      'RichMediaAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\RichMediaAd',
      'SelectiveOptimization' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SelectiveOptimization',
      'SelectorError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SelectorError',
      'LocationGroups' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\LocationGroups',
      'Setting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Setting',
      'SettingError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SettingError',
      'SharedSet' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SharedSet',
      'SharedCriterion' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SharedCriterion',
      'SharedCriterionError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SharedCriterionError',
      'SharedCriterionOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SharedCriterionOperation',
      'SharedSetError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SharedSetError',
      'SharedSetOperation' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SharedSetOperation',
      'ShoppingSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ShoppingSetting',
      'ShowcaseAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ShowcaseAd',
      'SitelinkFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SitelinkFeedItem',
      'SizeLimitError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\SizeLimitError',
      'StatsQueryError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\StatsQueryError',
      'StringFormatError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\StringFormatError',
      'StringLengthError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\StringLengthError',
      'String_StringMapEntry' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\String_StringMapEntry',
      'StructuredSnippetFeedItem' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\StructuredSnippetFeedItem',
      'TargetCpaBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TargetCpaBiddingScheme',
      'TargetOutrankShareBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TargetOutrankShareBiddingScheme',
      'TargetingSettingDetail' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TargetingSettingDetail',
      'TargetRoasBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TargetRoasBiddingScheme',
      'TargetSpendBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TargetSpendBiddingScheme',
      'TargetingSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TargetingSetting',
      'TempAdUnionId' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TempAdUnionId',
      'TemplateAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TemplateAd',
      'TemplateElement' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TemplateElement',
      'TemplateElementField' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TemplateElementField',
      'TextAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TextAd',
      'ThirdPartyRedirectAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\ThirdPartyRedirectAd',
      'TrackingSetting' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\TrackingSetting',
      'UniversalAppCampaignAdsPolicyDecisions' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\UniversalAppCampaignAdsPolicyDecisions',
      'UnknownProductDimension' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\UnknownProductDimension',
      'UrlData' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\UrlData',
      'UrlError' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\UrlError',
      'UrlList' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\UrlList',
      'CriterionUserInterest' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CriterionUserInterest',
      'CriterionUserList' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\CriterionUserList',
      'VanityPharma' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\VanityPharma',
      'Vertical' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Vertical',
      'Video' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Video',
      'Webpage' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\Webpage',
      'WebpageCondition' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\WebpageCondition',
      'WebpageParameter' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\WebpageParameter',
      'DynamicSearchAd' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\DynamicSearchAd',
      'YouTubeChannel' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\YouTubeChannel',
      'YouTubeVideo' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\YouTubeVideo',
      'mutateResponse' => 'Google\\AdsApi\\AdWords\\v201710\\cm\\mutateResponse',
    );

    /**
     * @param array $options A array of config values
     * @param string $wsdl The wsdl file to use
     */
    public function __construct(array $options = array(),
                $wsdl = 'https://adwords.google.com/api/adwords/cm/v201710/BatchJobOpsService?wsdl')
    {
      foreach (self::$classmap as $key => $value) {
        if (!isset($options['classmap'][$key])) {
          $options['classmap'][$key] = $value;
        }
      }
      $options = array_merge(array (
      'features' => 1,
    ), $options);
      parent::__construct($wsdl, $options);
    }

    /**
     * @param \Google\AdsApi\AdWords\v201710\cm\Operation[] $operations
     * @return \Google\AdsApi\AdWords\v201710\cm\MutateResult[]
     * @throws \Google\AdsApi\AdWords\v201710\cm\ApiException
     */
    public function mutate(array $operations)
    {
      return $this->__soapCall('mutate', array(array('operations' => $operations)))->getRval();
    }

}
