<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BiddingErrorsReason
{
    const BIDDING_STRATEGY_TRANSITION_NOT_ALLOWED = 'BIDDING_STRATEGY_TRANSITION_NOT_ALLOWED';
    const BIDDING_STRATEGY_NOT_COMPATIBLE_WITH_ADGROUP_OVERRIDES = 'BIDDING_STRATEGY_NOT_COMPATIBLE_WITH_ADGROUP_OVERRIDES';
    const BIDDING_STRATEGY_NOT_COMPATIBLE_WITH_ADGROUP_CRITERIA_OVERRIDES = 'BIDDING_STRATEGY_NOT_COMPATIBLE_WITH_ADGROUP_CRITERIA_OVERRIDES';
    const CAMPAIGN_BIDDING_STRATEGY_CANNOT_BE_OVERRIDDEN = 'CAMPAIGN_BIDDING_STRATEGY_CANNOT_BE_OVERRIDDEN';
    const ADGROUP_BIDDING_STRATEGY_CANNOT_BE_OVERRIDDEN = 'ADGROUP_BIDDING_STRATEGY_CANNOT_BE_OVERRIDDEN';
    const CANNOT_ATTACH_BIDDING_STRATEGY_TO_CAMPAIGN = 'CANNOT_ATTACH_BIDDING_STRATEGY_TO_CAMPAIGN';
    const CANNOT_ATTACH_BIDDING_STRATEGY_TO_ADGROUP = 'CANNOT_ATTACH_BIDDING_STRATEGY_TO_ADGROUP';
    const CANNOT_ATTACH_BIDDING_STRATEGY_TO_ADGROUP_CRITERIA = 'CANNOT_ATTACH_BIDDING_STRATEGY_TO_ADGROUP_CRITERIA';
    const INVALID_ANONYMOUS_BIDDING_STRATEGY_TYPE = 'INVALID_ANONYMOUS_BIDDING_STRATEGY_TYPE';
    const BIDS_NOT_ALLLOWED = 'BIDS_NOT_ALLLOWED';
    const DUPLICATE_BIDS = 'DUPLICATE_BIDS';
    const INVALID_BIDDING_SCHEME = 'INVALID_BIDDING_SCHEME';
    const INVALID_BIDDING_STRATEGY_TYPE = 'INVALID_BIDDING_STRATEGY_TYPE';
    const MISSING_BIDDING_STRATEGY_TYPE = 'MISSING_BIDDING_STRATEGY_TYPE';
    const NULL_BID = 'NULL_BID';
    const INVALID_BID = 'INVALID_BID';
    const BIDDING_STRATEGY_NOT_AVAILABLE_FOR_ACCOUNT_TYPE = 'BIDDING_STRATEGY_NOT_AVAILABLE_FOR_ACCOUNT_TYPE';
    const CONVERSION_TRACKING_NOT_ENABLED = 'CONVERSION_TRACKING_NOT_ENABLED';
    const NOT_ENOUGH_CONVERSIONS = 'NOT_ENOUGH_CONVERSIONS';
    const CANNOT_CREATE_CAMPAIGN_WITH_BIDDING_STRATEGY = 'CANNOT_CREATE_CAMPAIGN_WITH_BIDDING_STRATEGY';
    const CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_AD_GROUP_LEVEL_POP_BIDDING_STRATEGY = 'CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_AD_GROUP_LEVEL_POP_BIDDING_STRATEGY';
    const CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CAMPAIGN_LEVEL_POP_BIDDING_STRATEGY = 'CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CAMPAIGN_LEVEL_POP_BIDDING_STRATEGY';
    const BIDDING_STRATEGY_NOT_SUPPORTED_WITH_AD_SCHEDULE = 'BIDDING_STRATEGY_NOT_SUPPORTED_WITH_AD_SCHEDULE';
    const PAY_PER_CONVERSION_NOT_AVAILABLE_FOR_CUSTOMER = 'PAY_PER_CONVERSION_NOT_AVAILABLE_FOR_CUSTOMER';
    const PAY_PER_CONVERSION_NOT_ALLOWED_WITH_TARGET_CPA = 'PAY_PER_CONVERSION_NOT_ALLOWED_WITH_TARGET_CPA';
    const BIDDING_STRATEGY_NOT_ALLOWED_FOR_SEARCH_ONLY_CAMPAIGNS = 'BIDDING_STRATEGY_NOT_ALLOWED_FOR_SEARCH_ONLY_CAMPAIGNS';
    const BIDDING_STRATEGY_NOT_SUPPORTED_IN_DRAFTS_OR_EXPERIMENTS = 'BIDDING_STRATEGY_NOT_SUPPORTED_IN_DRAFTS_OR_EXPERIMENTS';
    const BIDDING_STRATEGY_TYPE_DOES_NOT_SUPPORT_PRODUCT_TYPE_ADGROUP_CRITERION = 'BIDDING_STRATEGY_TYPE_DOES_NOT_SUPPORT_PRODUCT_TYPE_ADGROUP_CRITERION';
    const BID_TOO_SMALL = 'BID_TOO_SMALL';
    const BID_TOO_BIG = 'BID_TOO_BIG';
    const BID_TOO_MANY_FRACTIONAL_DIGITS = 'BID_TOO_MANY_FRACTIONAL_DIGITS';
    const ENHANCED_CPC_ENABLED_NOT_SUPPORTED_ON_PORTFOLIO_TARGET_SPEND_STRATEGY = 'ENHANCED_CPC_ENABLED_NOT_SUPPORTED_ON_PORTFOLIO_TARGET_SPEND_STRATEGY';
    const UNKNOWN = 'UNKNOWN';


}
