<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BiddingStrategyErrorReason
{
    const DUPLICATE_NAME = 'DUPLICATE_NAME';
    const CANNOT_CHANGE_BIDDING_STRATEGY_TYPE = 'CANNOT_CHANGE_BIDDING_STRATEGY_TYPE';
    const CANNOT_REMOVE_ASSOCIATED_STRATEGY = 'CANNOT_REMOVE_ASSOCIATED_STRATEGY';
    const BIDDING_STRATEGY_NOT_SUPPORTED = 'BIDDING_STRATEGY_NOT_SUPPORTED';
    const UNKNOWN = 'UNKNOWN';


}
