<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CampaignErrorReason
{
    const CANNOT_GO_BACK_TO_INCOMPLETE = 'CANNOT_GO_BACK_TO_INCOMPLETE';
    const CANNOT_TARGET_CONTENT_NETWORK = 'CANNOT_TARGET_CONTENT_NETWORK';
    const CANNOT_TARGET_SEARCH_NETWORK = 'CANNOT_TARGET_SEARCH_NETWORK';
    const CANNOT_TARGET_SEARCH_NETWORK_WITHOUT_GOOGLE_SEARCH = 'CANNOT_TARGET_SEARCH_NETWORK_WITHOUT_GOOGLE_SEARCH';
    const CANNOT_TARGET_GOOGLE_SEARCH_FOR_CPM_CAMPAIGN = 'CANNOT_TARGET_GOOGLE_SEARCH_FOR_CPM_CAMPAIGN';
    const CAMPAIGN_MUST_TARGET_AT_LEAST_ONE_NETWORK = 'CAMPAIGN_MUST_TARGET_AT_LEAST_ONE_NETWORK';
    const CANNOT_TARGET_PARTNER_SEARCH_NETWORK = 'CANNOT_TARGET_PARTNER_SEARCH_NETWORK';
    const CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CRITERIA_LEVEL_BIDDING_STRATEGY = 'CANNOT_TARGET_CONTENT_NETWORK_ONLY_WITH_CRITERIA_LEVEL_BIDDING_STRATEGY';
    const CAMPAIGN_DURATION_MUST_CONTAIN_ALL_RUNNABLE_TRIALS = 'CAMPAIGN_DURATION_MUST_CONTAIN_ALL_RUNNABLE_TRIALS';
    const CANNOT_MODIFY_FOR_TRIAL_CAMPAIGN = 'CANNOT_MODIFY_FOR_TRIAL_CAMPAIGN';
    const DUPLICATE_CAMPAIGN_NAME = 'DUPLICATE_CAMPAIGN_NAME';
    const INCOMPATIBLE_CAMPAIGN_FIELD = 'INCOMPATIBLE_CAMPAIGN_FIELD';
    const INVALID_CAMPAIGN_NAME = 'INVALID_CAMPAIGN_NAME';
    const INVALID_AD_SERVING_OPTIMIZATION_STATUS = 'INVALID_AD_SERVING_OPTIMIZATION_STATUS';
    const INVALID_TRACKING_URL = 'INVALID_TRACKING_URL';
    const CANNOT_SET_BOTH_TRACKING_URL_TEMPLATE_AND_TRACKING_SETTING = 'CANNOT_SET_BOTH_TRACKING_URL_TEMPLATE_AND_TRACKING_SETTING';
    const MAX_IMPRESSIONS_NOT_IN_RANGE = 'MAX_IMPRESSIONS_NOT_IN_RANGE';
    const TIME_UNIT_NOT_SUPPORTED = 'TIME_UNIT_NOT_SUPPORTED';
    const INVALID_OPERATION_IF_SERVING_STATUS_HAS_ENDED = 'INVALID_OPERATION_IF_SERVING_STATUS_HAS_ENDED';
    const BUDGET_CANNOT_BE_SHARED = 'BUDGET_CANNOT_BE_SHARED';
    const CAMPAIGN_CANNOT_USE_SHARED_BUDGET = 'CAMPAIGN_CANNOT_USE_SHARED_BUDGET';
    const CANNOT_CHANGE_BUDGET_ON_CAMPAIGN_WITH_TRIALS = 'CANNOT_CHANGE_BUDGET_ON_CAMPAIGN_WITH_TRIALS';
    const CAMPAIGN_LABEL_DOES_NOT_EXIST = 'CAMPAIGN_LABEL_DOES_NOT_EXIST';
    const CAMPAIGN_LABEL_ALREADY_EXISTS = 'CAMPAIGN_LABEL_ALREADY_EXISTS';
    const MISSING_SHOPPING_SETTING = 'MISSING_SHOPPING_SETTING';
    const INVALID_SHOPPING_SALES_COUNTRY = 'INVALID_SHOPPING_SALES_COUNTRY';
    const SHOPPING_MERCHANT_NOT_ALLOWED_FOR_PURCHASES_ON_GOOGLE = 'SHOPPING_MERCHANT_NOT_ALLOWED_FOR_PURCHASES_ON_GOOGLE';
    const PURCHASES_ON_GOOGLE_NOT_SUPPORTED_FOR_SHOPPING_SALES_COUNTRY = 'PURCHASES_ON_GOOGLE_NOT_SUPPORTED_FOR_SHOPPING_SALES_COUNTRY';
    const MISSING_UNIVERSAL_APP_CAMPAIGN_SETTING = 'MISSING_UNIVERSAL_APP_CAMPAIGN_SETTING';
    const ADVERTISING_CHANNEL_TYPE_NOT_AVAILABLE_FOR_ACCOUNT_TYPE = 'ADVERTISING_CHANNEL_TYPE_NOT_AVAILABLE_FOR_ACCOUNT_TYPE';
    const INVALID_ADVERTISING_CHANNEL_SUB_TYPE = 'INVALID_ADVERTISING_CHANNEL_SUB_TYPE';
    const AT_LEAST_ONE_CONVERSION_MUST_BE_SELECTED = 'AT_LEAST_ONE_CONVERSION_MUST_BE_SELECTED';
    const CANNOT_SET_AD_ROTATION_MODE = 'CANNOT_SET_AD_ROTATION_MODE';
    const UNKNOWN = 'UNKNOWN';


}
