<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CampaignGroupErrorReason
{
    const CANNOT_DELETE_CAMPAIGN_GROUP_WITH_ACTIVE_OR_PAUSED_CAMPAIGNS = 'CANNOT_DELETE_CAMPAIGN_GROUP_WITH_ACTIVE_OR_PAUSED_CAMPAIGNS';
    const CANNOT_MODIFY_DELETED_CAMPAIGN_GROUP = 'CANNOT_MODIFY_DELETED_CAMPAIGN_GROUP';
    const DUPLICATE_NAME = 'DUPLICATE_NAME';
    const UNKNOWN = 'UNKNOWN';


}
