<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class FunctionErrorReason
{
    const INVALID_FUNCTION_FORMAT = 'INVALID_FUNCTION_FORMAT';
    const DATA_TYPE_MISMATCH = 'DATA_TYPE_MISMATCH';
    const INVALID_CONJUNCTION_OPERANDS = 'INVALID_CONJUNCTION_OPERANDS';
    const INVALID_NUMBER_OF_OPERANDS = 'INVALID_NUMBER_OF_OPERANDS';
    const INVALID_OPERAND_TYPE = 'INVALID_OPERAND_TYPE';
    const INVALID_OPERATOR = 'INVALID_OPERATOR';
    const INVALID_REQUEST_CONTEXT_TYPE = 'INVALID_REQUEST_CONTEXT_TYPE';
    const INVALID_FUNCTION_FOR_CALL_PLACEHOLDER = 'INVALID_FUNCTION_FOR_CALL_PLACEHOLDER';
    const INVALID_FUNCTION_FOR_PLACEHOLDER = 'INVALID_FUNCTION_FOR_PLACEHOLDER';
    const INVALID_OPERAND = 'INVALID_OPERAND';
    const MISSING_CONSTANT_OPERAND_VALUE = 'MISSING_CONSTANT_OPERAND_VALUE';
    const INVALID_CONSTANT_OPERAND_VALUE = 'INVALID_CONSTANT_OPERAND_VALUE';
    const INVALID_NESTING = 'INVALID_NESTING';
    const MULTIPLE_FEED_IDS_NOT_SUPPORTED = 'MULTIPLE_FEED_IDS_NOT_SUPPORTED';
    const INVALID_FUNCTION_FOR_FEED_WITH_FIXED_SCHEMA = 'INVALID_FUNCTION_FOR_FEED_WITH_FIXED_SCHEMA';
    const INVALID_ATTRIBUTE_NAME = 'INVALID_ATTRIBUTE_NAME';
    const UNKNOWN = 'UNKNOWN';


}
