<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class MediaBundleErrorReason
{
    const ENTRY_POINT_CANNOT_BE_SET_USING_MEDIA_SERVICE = 'ENTRY_POINT_CANNOT_BE_SET_USING_MEDIA_SERVICE';
    const BAD_REQUEST = 'BAD_REQUEST';
    const DOUBLECLICK_BUNDLE_NOT_ALLOWED = 'DOUBLECLICK_BUNDLE_NOT_ALLOWED';
    const EXTERNAL_URL_NOT_ALLOWED = 'EXTERNAL_URL_NOT_ALLOWED';
    const FILE_TOO_LARGE = 'FILE_TOO_LARGE';
    const GOOGLE_WEB_DESIGNER_ZIP_FILE_NOT_PUBLISHED = 'GOOGLE_WEB_DESIGNER_ZIP_FILE_NOT_PUBLISHED';
    const INVALID_INPUT = 'INVALID_INPUT';
    const INVALID_MEDIA_BUNDLE = 'INVALID_MEDIA_BUNDLE';
    const INVALID_MEDIA_BUNDLE_ENTRY = 'INVALID_MEDIA_BUNDLE_ENTRY';
    const INVALID_MIME_TYPE = 'INVALID_MIME_TYPE';
    const INVALID_PATH = 'INVALID_PATH';
    const INVALID_URL_REFERENCE = 'INVALID_URL_REFERENCE';
    const MEDIA_DATA_TOO_LARGE = 'MEDIA_DATA_TOO_LARGE';
    const MISSING_PRIMARY_MEDIA_BUNDLE_ENTRY = 'MISSING_PRIMARY_MEDIA_BUNDLE_ENTRY';
    const SERVER_ERROR = 'SERVER_ERROR';
    const STORAGE_ERROR = 'STORAGE_ERROR';
    const SWIFFY_BUNDLE_NOT_ALLOWED = 'SWIFFY_BUNDLE_NOT_ALLOWED';
    const TOO_MANY_FILES = 'TOO_MANY_FILES';
    const UNEXPECTED_SIZE = 'UNEXPECTED_SIZE';
    const UNSUPPORTED_GOOGLE_WEB_DESIGNER_ENVIRONMENT = 'UNSUPPORTED_GOOGLE_WEB_DESIGNER_ENVIRONMENT';
    const UNSUPPORTED_HTML5_FEATURE = 'UNSUPPORTED_HTML5_FEATURE';
    const URL_IN_MEDIA_BUNDLE_NOT_SSL_COMPLIANT = 'URL_IN_MEDIA_BUNDLE_NOT_SSL_COMPLIANT';


}
