<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class MultiplierErrorReason
{
    const MULTIPLIER_TOO_HIGH = 'MULTIPLIER_TOO_HIGH';
    const MULTIPLIER_TOO_LOW = 'MULTIPLIER_TOO_LOW';
    const TOO_MANY_FRACTIONAL_DIGITS = 'TOO_MANY_FRACTIONAL_DIGITS';
    const MULTIPLIER_NOT_ALLOWED_FOR_BIDDING_STRATEGY = 'MULTIPLIER_NOT_ALLOWED_FOR_BIDDING_STRATEGY';
    const MULTIPLIER_NOT_ALLOWED_WHEN_BASE_BID_IS_MISSING = 'MULTIPLIER_NOT_ALLOWED_WHEN_BASE_BID_IS_MISSING';
    const NO_MULTIPLIER_SPECIFIED = 'NO_MULTIPLIER_SPECIFIED';
    const MULTIPLIER_CAUSES_BID_TO_EXCEED_DAILY_BUDGET = 'MULTIPLIER_CAUSES_BID_TO_EXCEED_DAILY_BUDGET';
    const MULTIPLIER_CAUSES_BID_TO_EXCEED_MONTHLY_BUDGET = 'MULTIPLIER_CAUSES_BID_TO_EXCEED_MONTHLY_BUDGET';
    const MULTIPLIER_CAUSES_BID_TO_EXCEED_CUSTOM_BUDGET = 'MULTIPLIER_CAUSES_BID_TO_EXCEED_CUSTOM_BUDGET';
    const MULTIPLIER_CAUSES_BID_TO_EXCEED_MAX_ALLOWED_BID = 'MULTIPLIER_CAUSES_BID_TO_EXCEED_MAX_ALLOWED_BID';
    const BID_LESS_THAN_MIN_ALLOWED_BID_WITH_MULTIPLIER = 'BID_LESS_THAN_MIN_ALLOWED_BID_WITH_MULTIPLIER';
    const MULTIPLIER_AND_BIDDING_STRATEGY_TYPE_MISMATCH = 'MULTIPLIER_AND_BIDDING_STRATEGY_TYPE_MISMATCH';
    const MULTIPLIER_ERROR = 'MULTIPLIER_ERROR';


}
