<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ReportDefinitionReportType
{
    const KEYWORDS_PERFORMANCE_REPORT = 'KEYWORDS_PERFORMANCE_REPORT';
    const AD_PERFORMANCE_REPORT = 'AD_PERFORMANCE_REPORT';
    const URL_PERFORMANCE_REPORT = 'URL_PERFORMANCE_REPORT';
    const ADGROUP_PERFORMANCE_REPORT = 'ADGROUP_PERFORMANCE_REPORT';
    const CAMPAIGN_PERFORMANCE_REPORT = 'CAMPAIGN_PERFORMANCE_REPORT';
    const ACCOUNT_PERFORMANCE_REPORT = 'ACCOUNT_PERFORMANCE_REPORT';
    const GEO_PERFORMANCE_REPORT = 'GEO_PERFORMANCE_REPORT';
    const SEARCH_QUERY_PERFORMANCE_REPORT = 'SEARCH_QUERY_PERFORMANCE_REPORT';
    const AUTOMATIC_PLACEMENTS_PERFORMANCE_REPORT = 'AUTOMATIC_PLACEMENTS_PERFORMANCE_REPORT';
    const CAMPAIGN_NEGATIVE_KEYWORDS_PERFORMANCE_REPORT = 'CAMPAIGN_NEGATIVE_KEYWORDS_PERFORMANCE_REPORT';
    const CAMPAIGN_NEGATIVE_PLACEMENTS_PERFORMANCE_REPORT = 'CAMPAIGN_NEGATIVE_PLACEMENTS_PERFORMANCE_REPORT';
    const DESTINATION_URL_REPORT = 'DESTINATION_URL_REPORT';
    const SHARED_SET_REPORT = 'SHARED_SET_REPORT';
    const CAMPAIGN_SHARED_SET_REPORT = 'CAMPAIGN_SHARED_SET_REPORT';
    const SHARED_SET_CRITERIA_REPORT = 'SHARED_SET_CRITERIA_REPORT';
    const CREATIVE_CONVERSION_REPORT = 'CREATIVE_CONVERSION_REPORT';
    const CALL_METRICS_CALL_DETAILS_REPORT = 'CALL_METRICS_CALL_DETAILS_REPORT';
    const KEYWORDLESS_QUERY_REPORT = 'KEYWORDLESS_QUERY_REPORT';
    const KEYWORDLESS_CATEGORY_REPORT = 'KEYWORDLESS_CATEGORY_REPORT';
    const CRITERIA_PERFORMANCE_REPORT = 'CRITERIA_PERFORMANCE_REPORT';
    const CLICK_PERFORMANCE_REPORT = 'CLICK_PERFORMANCE_REPORT';
    const BUDGET_PERFORMANCE_REPORT = 'BUDGET_PERFORMANCE_REPORT';
    const BID_GOAL_PERFORMANCE_REPORT = 'BID_GOAL_PERFORMANCE_REPORT';
    const DISPLAY_KEYWORD_PERFORMANCE_REPORT = 'DISPLAY_KEYWORD_PERFORMANCE_REPORT';
    const PLACEHOLDER_FEED_ITEM_REPORT = 'PLACEHOLDER_FEED_ITEM_REPORT';
    const PLACEMENT_PERFORMANCE_REPORT = 'PLACEMENT_PERFORMANCE_REPORT';
    const CAMPAIGN_NEGATIVE_LOCATIONS_REPORT = 'CAMPAIGN_NEGATIVE_LOCATIONS_REPORT';
    const GENDER_PERFORMANCE_REPORT = 'GENDER_PERFORMANCE_REPORT';
    const AGE_RANGE_PERFORMANCE_REPORT = 'AGE_RANGE_PERFORMANCE_REPORT';
    const CAMPAIGN_LOCATION_TARGET_REPORT = 'CAMPAIGN_LOCATION_TARGET_REPORT';
    const CAMPAIGN_AD_SCHEDULE_TARGET_REPORT = 'CAMPAIGN_AD_SCHEDULE_TARGET_REPORT';
    const PAID_ORGANIC_QUERY_REPORT = 'PAID_ORGANIC_QUERY_REPORT';
    const AUDIENCE_PERFORMANCE_REPORT = 'AUDIENCE_PERFORMANCE_REPORT';
    const DISPLAY_TOPICS_PERFORMANCE_REPORT = 'DISPLAY_TOPICS_PERFORMANCE_REPORT';
    const USER_AD_DISTANCE_REPORT = 'USER_AD_DISTANCE_REPORT';
    const SHOPPING_PERFORMANCE_REPORT = 'SHOPPING_PERFORMANCE_REPORT';
    const PRODUCT_PARTITION_REPORT = 'PRODUCT_PARTITION_REPORT';
    const PARENTAL_STATUS_PERFORMANCE_REPORT = 'PARENTAL_STATUS_PERFORMANCE_REPORT';
    const PLACEHOLDER_REPORT = 'PLACEHOLDER_REPORT';
    const AD_CUSTOMIZERS_FEED_ITEM_REPORT = 'AD_CUSTOMIZERS_FEED_ITEM_REPORT';
    const LABEL_REPORT = 'LABEL_REPORT';
    const FINAL_URL_REPORT = 'FINAL_URL_REPORT';
    const VIDEO_PERFORMANCE_REPORT = 'VIDEO_PERFORMANCE_REPORT';
    const TOP_CONTENT_PERFORMANCE_REPORT = 'TOP_CONTENT_PERFORMANCE_REPORT';
    const CAMPAIGN_CRITERIA_REPORT = 'CAMPAIGN_CRITERIA_REPORT';
    const CAMPAIGN_GROUP_PERFORMANCE_REPORT = 'CAMPAIGN_GROUP_PERFORMANCE_REPORT';
    const UNKNOWN = 'UNKNOWN';


}
