<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class UniversalAppBiddingStrategyGoalType
{
    const UNKNOWN = 'UNKNOWN';
    const OPTIMIZE_FOR_INSTALL_CONVERSION_VOLUME = 'OPTIMIZE_FOR_INSTALL_CONVERSION_VOLUME';
    const OPTIMIZE_FOR_IN_APP_CONVERSION_VOLUME = 'OPTIMIZE_FOR_IN_APP_CONVERSION_VOLUME';
    const OPTIMIZE_FOR_TOTAL_CONVERSION_VALUE = 'OPTIMIZE_FOR_TOTAL_CONVERSION_VALUE';


}
