<?php

namespace Google\AdsApi\AdWords\v201710\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class VanityPharmaText
{
    const UNKNOWN = 'UNKNOWN';
    const PRESCRIPTION_TREATMENT_WEBSITE_EN = 'PRESCRIPTION_TREATMENT_WEBSITE_EN';
    const PRESCRIPTION_TREATMENT_WEBSITE_ES = 'PRESCRIPTION_TREATMENT_WEBSITE_ES';
    const PRESCRIPTION_DEVICE_WEBSITE_EN = 'PRESCRIPTION_DEVICE_WEBSITE_EN';
    const PRESCRIPTION_DEVICE_WEBSITE_ES = 'PRESCRIPTION_DEVICE_WEBSITE_ES';
    const MEDICAL_DEVICE_WEBSITE_EN = 'MEDICAL_DEVICE_WEBSITE_EN';
    const MEDICAL_DEVICE_WEBSITE_ES = 'MEDICAL_DEVICE_WEBSITE_ES';
    const PREVENTATIVE_TREATMENT_WEBSITE_EN = 'PREVENTATIVE_TREATMENT_WEBSITE_EN';
    const PREVENTATIVE_TREATMENT_WEBSITE_ES = 'PREVENTATIVE_TREATMENT_WEBSITE_ES';
    const PRESCRIPTION_CONTRACEPTION_WEBSITE_EN = 'PRESCRIPTION_CONTRACEPTION_WEBSITE_EN';
    const PRESCRIPTION_CONTRACEPTION_WEBSITE_ES = 'PRESCRIPTION_CONTRACEPTION_WEBSITE_ES';
    const PRESCRIPTION_VACCINE_WEBSITE_EN = 'PRESCRIPTION_VACCINE_WEBSITE_EN';
    const PRESCRIPTION_VACCINE_WEBSITE_ES = 'PRESCRIPTION_VACCINE_WEBSITE_ES';


}
