<?php

namespace Google\AdsApi\AdWords\v201802\rm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class MutateMembersErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const UNSUPPORTED_METHOD = 'UNSUPPORTED_METHOD';
    const INVALID_USER_LIST_ID = 'INVALID_USER_LIST_ID';
    const INVALID_USER_LIST_TYPE = 'INVALID_USER_LIST_TYPE';
    const INVALID_DATA_TYPE = 'INVALID_DATA_TYPE';
    const INVALID_SHA256_FORMAT = 'INVALID_SHA256_FORMAT';
    const OPERATOR_CONFLICT_FOR_SAME_USER_LIST_ID = 'OPERATOR_CONFLICT_FOR_SAME_USER_LIST_ID';
    const INVALID_REMOVEALL_OPERATION = 'INVALID_REMOVEALL_OPERATION';
    const INVALID_OPERATION_ORDER = 'INVALID_OPERATION_ORDER';
    const MISSING_MEMBER_IDENTIFIER = 'MISSING_MEMBER_IDENTIFIER';
    const INCOMPATIBLE_UPLOAD_KEY_TYPE = 'INCOMPATIBLE_UPLOAD_KEY_TYPE';


}
