<?php

namespace Google\AdsApi\AdWords\v201809\o;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class TrafficEstimatorErrorReason
{
    const NO_CAMPAIGN_FOR_AD_GROUP_ESTIMATE_REQUEST = 'NO_CAMPAIGN_FOR_AD_GROUP_ESTIMATE_REQUEST';
    const NO_AD_GROUP_FOR_KEYWORD_ESTIMATE_REQUEST = 'NO_AD_GROUP_FOR_KEYWORD_ESTIMATE_REQUEST';
    const NO_MAX_CPC_FOR_KEYWORD_ESTIMATE_REQUEST = 'NO_MAX_CPC_FOR_KEYWORD_ESTIMATE_REQUEST';
    const TOO_MANY_KEYWORD_ESTIMATE_REQUESTS = 'TOO_MANY_KEYWORD_ESTIMATE_REQUESTS';
    const TOO_MANY_CAMPAIGN_ESTIMATE_REQUESTS = 'TOO_MANY_CAMPAIGN_ESTIMATE_REQUESTS';
    const TOO_MANY_ADGROUP_ESTIMATE_REQUESTS = 'TOO_MANY_ADGROUP_ESTIMATE_REQUESTS';
    const TOO_MANY_TARGETS = 'TOO_MANY_TARGETS';
    const KEYWORD_TOO_LONG = 'KEYWORD_TOO_LONG';
    const KEYWORD_CONTAINS_BROAD_MATCH_MODIFIERS = 'KEYWORD_CONTAINS_BROAD_MATCH_MODIFIERS';
    const INVALID_INPUT = 'INVALID_INPUT';
    const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';


}
