<?php

namespace Google\AdsApi\AdManager\v202011;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class SiteErrorReason
{
    const INVALID_CHILD_NETWORK_CODE = 'INVALID_CHILD_NETWORK_CODE';
    const INVALID_URL_FOR_SITE = 'INVALID_URL_FOR_SITE';
    const TOO_MANY_SITES_PER_REVIEW_REQUEST = 'TOO_MANY_SITES_PER_REVIEW_REQUEST';
    const TOO_MANY_REVIEW_REQUESTS_FOR_SITE = 'TOO_MANY_REVIEW_REQUESTS_FOR_SITE';
    const INVALID_APPROVAL_STATUS_FOR_REVIEW = 'INVALID_APPROVAL_STATUS_FOR_REVIEW';
    const UNKNOWN = 'UNKNOWN';


}
