<?php

namespace Google\AdsApi\AdManager\v202505;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CreativePreviewErrorReason
{
    const CANNOT_GENERATE_PREVIEW_URL = 'CANNOT_GENERATE_PREVIEW_URL';
    const CANNOT_GENERATE_PREVIEW_URL_FOR_NATIVE_CREATIVES = 'CANNOT_GENERATE_PREVIEW_URL_FOR_NATIVE_CREATIVES';
    const HTML_SNIPPET_REQUIRED_FOR_THIRD_PARTY_CREATIVE = 'HTML_SNIPPET_REQUIRED_FOR_THIRD_PARTY_CREATIVE';
    const UNKNOWN = 'UNKNOWN';


}
