<?php

namespace Google\AdsApi\AdManager\v202505;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CreativeErrorReason
{
    const FLASH_AND_FALLBACK_URL_ARE_SAME = 'FLASH_AND_FALLBACK_URL_ARE_SAME';
    const DESTINATION_URL_NOT_EMPTY = 'DESTINATION_URL_NOT_EMPTY';
    const DESTINATION_URL_TYPE_NOT_SUPPORTED = 'DESTINATION_URL_TYPE_NOT_SUPPORTED';
    const CANNOT_CREATE_OR_UPDATE_LEGACY_DFP_CREATIVE = 'CANNOT_CREATE_OR_UPDATE_LEGACY_DFP_CREATIVE';
    const CANNOT_CREATE_OR_UPDATE_LEGACY_DFP_MOBILE_CREATIVE = 'CANNOT_CREATE_OR_UPDATE_LEGACY_DFP_MOBILE_CREATIVE';
    const INVALID_COMPANY_TYPE = 'INVALID_COMPANY_TYPE';
    const DUPLICATE_ASSET_IN_CREATIVE = 'DUPLICATE_ASSET_IN_CREATIVE';
    const CREATIVE_ASSET_CANNOT_HAVE_ID_AND_BYTE_ARRAY = 'CREATIVE_ASSET_CANNOT_HAVE_ID_AND_BYTE_ARRAY';
    const CANNOT_CREATE_OR_UPDATE_UNSUPPORTED_CREATIVE = 'CANNOT_CREATE_OR_UPDATE_UNSUPPORTED_CREATIVE';
    const CANNOT_CREATE_PROGRAMMATIC_CREATIVES = 'CANNOT_CREATE_PROGRAMMATIC_CREATIVES';
    const INVALID_SIZE_FOR_THIRD_PARTY_IMPRESSION_TRACKER = 'INVALID_SIZE_FOR_THIRD_PARTY_IMPRESSION_TRACKER';
    const CANNOT_DEACTIVATE_CREATIVES_IN_CREATIVE_SETS = 'CANNOT_DEACTIVATE_CREATIVES_IN_CREATIVE_SETS';
    const HOSTED_VIDEO_CREATIVE_REQUIRES_VIDEO_ASSET = 'HOSTED_VIDEO_CREATIVE_REQUIRES_VIDEO_ASSET';
    const UNKNOWN = 'UNKNOWN';


}
