<?php

namespace Google\AdsApi\Dfp\v201511;

class ActivityType
{
    const __default = 'PAGE_VIEWS';
    const PAGE_VIEWS = 'PAGE_VIEWS';
    const DAILY_VISITS = 'DAILY_VISITS';
    const CUSTOM = 'CUSTOM';
    const ITEMS_PURCHASED = 'ITEMS_PURCHASED';
    const TRANSACTIONS = 'TRANSACTIONS';
    const IOS_APPLICATION_DOWNLOADS = 'IOS_APPLICATION_DOWNLOADS';
    const ANDROID_APPLICATION_DOWNLOADS = 'ANDROID_APPLICATION_DOWNLOADS';
    const UNKNOWN = 'UNKNOWN';


}
