<?php

namespace Google\AdsApi\Dfp\v201511;

class AdRuleDateErrorReason
{
    const __default = 'START_DATE_TIME_IS_IN_PAST';
    const START_DATE_TIME_IS_IN_PAST = 'START_DATE_TIME_IS_IN_PAST';
    const END_DATE_TIME_IS_IN_PAST = 'END_DATE_TIME_IS_IN_PAST';
    const END_DATE_TIME_NOT_AFTER_START_TIME = 'END_DATE_TIME_NOT_AFTER_START_TIME';
    const END_DATE_TIME_TOO_LATE = 'END_DATE_TIME_TOO_LATE';
    const UNKNOWN = 'UNKNOWN';


}
