<?php

namespace Google\AdsApi\Dfp\v201511;

class AdUnitCodeErrorReason
{
    const __default = 'INVALID_CHARACTERS';
    const INVALID_CHARACTERS = 'INVALID_CHARACTERS';
    const INVALID_CHARACTERS_WHEN_UTF_CHARACTERS_ARE_ALLOWED = 'INVALID_CHARACTERS_WHEN_UTF_CHARACTERS_ARE_ALLOWED';
    const LEADING_FORWARD_SLASH = 'LEADING_FORWARD_SLASH';
    const UNKNOWN = 'UNKNOWN';


}
