<?php

namespace Google\AdsApi\Dfp\v201511;

class BaseRateErrorReason
{
    const __default = 'CANNOT_QUERY_BOTH_PRODUCT_TEMPLATE_ID_AND_PRODUCT_ID';
    const CANNOT_QUERY_BOTH_PRODUCT_TEMPLATE_ID_AND_PRODUCT_ID = 'CANNOT_QUERY_BOTH_PRODUCT_TEMPLATE_ID_AND_PRODUCT_ID';
    const INVALID_CURRENCY_CODE = 'INVALID_CURRENCY_CODE';
    const PRODUCT_TEMPLATE_ARCHIVED = 'PRODUCT_TEMPLATE_ARCHIVED';
    const UNSUPPORTED_OPERATION = 'UNSUPPORTED_OPERATION';
    const PRODUCT_TEMPLATE_BASE_RATE_NOT_FOUND = 'PRODUCT_TEMPLATE_BASE_RATE_NOT_FOUND';
    const PRODUCT_BASE_RATE_EXISTS = 'PRODUCT_BASE_RATE_EXISTS';
    const UNKNOWN = 'UNKNOWN';


}
