<?php

namespace Google\AdsApi\Dfp\v201511;

class CompanyErrorReason
{
    const __default = 'CANNOT_SET_THIRD_PARTY_COMPANY_DUE_TO_TYPE';
    const CANNOT_SET_THIRD_PARTY_COMPANY_DUE_TO_TYPE = 'CANNOT_SET_THIRD_PARTY_COMPANY_DUE_TO_TYPE';
    const CANNOT_UPDATE_COMPANY_TYPE = 'CANNOT_UPDATE_COMPANY_TYPE';
    const INVALID_COMPANY_TYPE = 'INVALID_COMPANY_TYPE';
    const PRIMARY_CONTACT_DOES_NOT_BELONG_TO_THIS_COMPANY = 'PRIMARY_CONTACT_DOES_NOT_BELONG_TO_THIS_COMPANY';
    const THIRD_PARTY_STATS_PROVIDER_IS_WRONG_ROLE_TYPE = 'THIRD_PARTY_STATS_PROVIDER_IS_WRONG_ROLE_TYPE';
    const INVALID_LABEL_ASSOCIATION = 'INVALID_LABEL_ASSOCIATION';
    const INVALID_COMPANY_TYPE_FOR_DEFAULT_BILLING_SETTING = 'INVALID_COMPANY_TYPE_FOR_DEFAULT_BILLING_SETTING';
    const INVALID_DEFAULT_BILLING_SETTING = 'INVALID_DEFAULT_BILLING_SETTING';
    const UNKNOWN = 'UNKNOWN';


}
