<?php

namespace Google\AdsApi\Dfp\v201511;

class CreativeErrorReason
{
    const __default = 'FLASH_AND_FALLBACK_URL_ARE_SAME';
    const FLASH_AND_FALLBACK_URL_ARE_SAME = 'FLASH_AND_FALLBACK_URL_ARE_SAME';
    const INVALID_INTERNAL_REDIRECT_URL = 'INVALID_INTERNAL_REDIRECT_URL';
    const DESTINATION_URL_REQUIRED = 'DESTINATION_URL_REQUIRED';
    const CANNOT_CREATE_OR_UPDATE_LEGACY_DFP_CREATIVE = 'CANNOT_CREATE_OR_UPDATE_LEGACY_DFP_CREATIVE';
    const CANNOT_CREATE_OR_UPDATE_LEGACY_DFP_MOBILE_CREATIVE = 'CANNOT_CREATE_OR_UPDATE_LEGACY_DFP_MOBILE_CREATIVE';
    const MISSING_FEATURE = 'MISSING_FEATURE';
    const INVALID_COMPANY_TYPE = 'INVALID_COMPANY_TYPE';
    const INVALID_ADSENSE_CREATIVE_SIZE = 'INVALID_ADSENSE_CREATIVE_SIZE';
    const INVALID_AD_EXCHANGE_CREATIVE_SIZE = 'INVALID_AD_EXCHANGE_CREATIVE_SIZE';
    const DUPLICATE_ASSET_IN_CREATIVE = 'DUPLICATE_ASSET_IN_CREATIVE';
    const CREATIVE_ASSET_CANNOT_HAVE_ID_AND_BYTE_ARRAY = 'CREATIVE_ASSET_CANNOT_HAVE_ID_AND_BYTE_ARRAY';
    const CANNOT_CREATE_OR_UPDATE_UNSUPPORTED_CREATIVE = 'CANNOT_CREATE_OR_UPDATE_UNSUPPORTED_CREATIVE';
    const CANNOT_CREATE_PROGRAMMATIC_CREATIVES = 'CANNOT_CREATE_PROGRAMMATIC_CREATIVES';
    const UNKNOWN = 'UNKNOWN';


}
