<?php

namespace Google\AdsApi\Dfp\v201511;

class CreativePersistenceType
{
    const __default = 'NOT_PERSISTENT';
    const NOT_PERSISTENT = 'NOT_PERSISTENT';
    const PERSISTENT_AND_EXCLUDE_NONE = 'PERSISTENT_AND_EXCLUDE_NONE';
    const PERSISTENT_AND_EXCLUDE_DISPLAY = 'PERSISTENT_AND_EXCLUDE_DISPLAY';
    const PERSISTENT_AND_EXCLUDE_VIDEO = 'PERSISTENT_AND_EXCLUDE_VIDEO';
    const PERSISTENT_AND_EXCLUDE_ALL = 'PERSISTENT_AND_EXCLUDE_ALL';


}
