<?php

namespace Google\AdsApi\Dfp\v201511;

class CreativeSetErrorReason
{
    const __default = 'VIDEO_FEATURE_REQUIRED';
    const VIDEO_FEATURE_REQUIRED = 'VIDEO_FEATURE_REQUIRED';
    const CANNOT_CREATE_OR_UPDATE_VIDEO_CREATIVES = 'CANNOT_CREATE_OR_UPDATE_VIDEO_CREATIVES';
    const ROADBLOCK_FEATURE_REQUIRED = 'ROADBLOCK_FEATURE_REQUIRED';
    const MASTER_CREATIVE_CANNOT_BE_COMPANION = 'MASTER_CREATIVE_CANNOT_BE_COMPANION';
    const INVALID_ADVERTISER = 'INVALID_ADVERTISER';
    const UPDATE_MASTER_CREATIVE_NOT_ALLOWED = 'UPDATE_MASTER_CREATIVE_NOT_ALLOWED';
    const UNKNOWN = 'UNKNOWN';


}
