<?php

namespace Google\AdsApi\Dfp\v201511;

class InventoryUnitErrorReason
{
    const __default = 'EXPLICIT_TARGETING_NOT_ALLOWED';
    const EXPLICIT_TARGETING_NOT_ALLOWED = 'EXPLICIT_TARGETING_NOT_ALLOWED';
    const TARGET_PLATFORM_NOT_APPLICABLE = 'TARGET_PLATFORM_NOT_APPLICABLE';
    const ADSENSE_CANNOT_BE_ENABLED = 'ADSENSE_CANNOT_BE_ENABLED';
    const ROOT_UNIT_CANNOT_BE_DEACTIVATED = 'ROOT_UNIT_CANNOT_BE_DEACTIVATED';
    const UNKNOWN = 'UNKNOWN';


}
