<?php

namespace Google\AdsApi\Dfp\v201511;

class ProductPackageItemErrorReason
{
    const __default = 'ARCHIVED_PRODUCT_NOT_ALLOWED';
    const ARCHIVED_PRODUCT_NOT_ALLOWED = 'ARCHIVED_PRODUCT_NOT_ALLOWED';
    const INACTIVE_MANDATORY_PRODUCT_NOT_ALLOWED = 'INACTIVE_MANDATORY_PRODUCT_NOT_ALLOWED';
    const UNKNOWN = 'UNKNOWN';


}
