<?php

namespace Google\AdsApi\Dfp\v201511;

class RateCardErrorReason
{
    const __default = 'INVALID_CURRENCY_CODE';
    const INVALID_CURRENCY_CODE = 'INVALID_CURRENCY_CODE';
    const UNSUPPORTED_CURRENCY_CODE = 'UNSUPPORTED_CURRENCY_CODE';
    const UNCHANGEABLE_CURRENCY_CODE = 'UNCHANGEABLE_CURRENCY_CODE';
    const UNKNOWN = 'UNKNOWN';


}
