<?php

namespace Google\AdsApi\Dfp\v201511;

class ReconciliationImportErrorReason
{
    const __default = 'MISSING_EDITABLE_COLUMN';
    const MISSING_EDITABLE_COLUMN = 'MISSING_EDITABLE_COLUMN';
    const INCONSISTENT_IMPORT_COLUMNS = 'INCONSISTENT_IMPORT_COLUMNS';
    const COLUMN_CONVERSION_TYPE_ERROR = 'COLUMN_CONVERSION_TYPE_ERROR';
    const INCONSISTENT_COLUMNS_COUNT = 'INCONSISTENT_COLUMNS_COUNT';
    const IMPORT_INTERNAL_ERROR = 'IMPORT_INTERNAL_ERROR';
    const UNKNOWN = 'UNKNOWN';


}
