<?php

namespace Google\AdsApi\Dfp\v201511;

class RichMediaStudioCreativeErrorReason
{
    const __default = 'CREATION_NOT_ALLOWED';
    const CREATION_NOT_ALLOWED = 'CREATION_NOT_ALLOWED';
    const UKNOWN_ERROR = 'UKNOWN_ERROR';
    const INVALID_CODE_GENERATION_REQUEST = 'INVALID_CODE_GENERATION_REQUEST';
    const INVALID_CREATIVE_OBJECT = 'INVALID_CREATIVE_OBJECT';
    const STUDIO_CONNECTION_ERROR = 'STUDIO_CONNECTION_ERROR';
    const PUSHDOWN_DURATION_NOT_ALLOWED = 'PUSHDOWN_DURATION_NOT_ALLOWED';
    const INVALID_POSITION = 'INVALID_POSITION';
    const INVALID_Z_INDEX = 'INVALID_Z_INDEX';
    const INVALID_PUSHDOWN_DURATION = 'INVALID_PUSHDOWN_DURATION';
    const UNKNOWN = 'UNKNOWN';


}
