<?php

namespace Google\AdsApi\Dfp\v201511;

class TeamErrorReason
{
    const __default = 'ENTITY_NOT_ON_USERS_TEAMS';
    const ENTITY_NOT_ON_USERS_TEAMS = 'ENTITY_NOT_ON_USERS_TEAMS';
    const AD_UNITS_NOT_ON_ORDER_TEAMS = 'AD_UNITS_NOT_ON_ORDER_TEAMS';
    const PLACEMENTS_NOT_ON_ORDER_TEAMS = 'PLACEMENTS_NOT_ON_ORDER_TEAMS';
    const MISSING_USERS_TEAM = 'MISSING_USERS_TEAM';
    const ALL_TEAM_ASSOCIATION_NOT_ALLOWED = 'ALL_TEAM_ASSOCIATION_NOT_ALLOWED';
    const ALL_TEAM_ACCESS_OVERRIDE_NOT_ALLOWED = 'ALL_TEAM_ACCESS_OVERRIDE_NOT_ALLOWED';
    const UNKNOWN = 'UNKNOWN';


}
