<?php

namespace Google\AdsApi\Dfp\v201511;

class VideoPositionTargetingErrorReason
{
    const __default = 'CANNOT_MIX_BUMPER_AND_NON_BUMPER_TARGETING';
    const CANNOT_MIX_BUMPER_AND_NON_BUMPER_TARGETING = 'CANNOT_MIX_BUMPER_AND_NON_BUMPER_TARGETING';
    const INVALID_BUMPER_TARGETING = 'INVALID_BUMPER_TARGETING';
    const UNKNOWN = 'UNKNOWN';


}
