<?php

namespace Google\AdsApi\Dfp\v201511;

class WorkflowRequestErrorReason
{
    const __default = 'REQUEST_ALREADY_PROCESSED';
    const REQUEST_ALREADY_PROCESSED = 'REQUEST_ALREADY_PROCESSED';
    const WORKFLOW_NOT_IN_PROGRESS = 'WORKFLOW_NOT_IN_PROGRESS';
    const INVALID_REQUEST_ID = 'INVALID_REQUEST_ID';
    const INVALID_ACTION = 'INVALID_ACTION';
    const TYPE_REQUIRED = 'TYPE_REQUIRED';
    const UNKNOWN = 'UNKNOWN';


}
