<?php

namespace Google\AdsApi\AdWords\v201710\billing;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BudgetOrderErrorReason
{
    const BUDGET_APPROVAL_IN_PROGRESS = 'BUDGET_APPROVAL_IN_PROGRESS';
    const SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';
    const INVALID_BILLING_ACCOUNT = 'INVALID_BILLING_ACCOUNT';
    const GENERIC_BILLING_ERROR = 'GENERIC_BILLING_ERROR';
    const INVALID_BILLING_ACCOUNT_ID_FORMAT = 'INVALID_BILLING_ACCOUNT_ID_FORMAT';
    const INVALID_BUDGET_DATE_RANGE = 'INVALID_BUDGET_DATE_RANGE';
    const BUDGET_UPDATE_DENIED = 'BUDGET_UPDATE_DENIED';
    const BUDGET_ALREADY_STARTED = 'BUDGET_ALREADY_STARTED';
    const BUDGET_ALREADY_ENDED = 'BUDGET_ALREADY_ENDED';
    const INVALID_CONSTRAINT = 'INVALID_CONSTRAINT';
    const INVALID_BID_TOO_LARGE = 'INVALID_BID_TOO_LARGE';
    const NO_SUCH_BUDGET_FOUND = 'NO_SUCH_BUDGET_FOUND';
    const INVALID_BUDGET_ALREADY_SPENT = 'INVALID_BUDGET_ALREADY_SPENT';
    const INVALID_TIMEZONE_IN_DATE = 'INVALID_TIMEZONE_IN_DATE';
    const ACCOUNT_BUDGET_ID_SET_IN_ADD = 'ACCOUNT_BUDGET_ID_SET_IN_ADD';
    const MORE_THAN_ONE_OPERATIONS = 'MORE_THAN_ONE_OPERATIONS';
    const INVALID_MANAGER_ACCOUNT = 'INVALID_MANAGER_ACCOUNT';
    const UNKNOWN = 'UNKNOWN';


}
