<?php

namespace Google\AdsApi\AdWords\v201609\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BiddingStrategySystemStatus
{
    const UNKNOWN = 'UNKNOWN';
    const UNCONSTRAINED = 'UNCONSTRAINED';
    const LEARNING_NEW = 'LEARNING_NEW';
    const LEARNING_SETTING_CHANGE = 'LEARNING_SETTING_CHANGE';
    const LEARNING_BUDGET_CHANGE = 'LEARNING_BUDGET_CHANGE';
    const LEARNING_COMPOSITION_CHANGE = 'LEARNING_COMPOSITION_CHANGE';
    const LEARNING_CONVERSION_TYPE_CHANGE = 'LEARNING_CONVERSION_TYPE_CHANGE';
    const LEARNING_CONVERSION_SETTING_CHANGE = 'LEARNING_CONVERSION_SETTING_CHANGE';
    const LIMITED_BY_BID_CONSTRAINTS = 'LIMITED_BY_BID_CONSTRAINTS';
    const LIMITED_BY_MAX_BID_LIMIT = 'LIMITED_BY_MAX_BID_LIMIT';
    const LIMITED_BY_MIN_BID_LIMIT = 'LIMITED_BY_MIN_BID_LIMIT';
    const LIMITED_BY_MIN_ROAS_LIMIT = 'LIMITED_BY_MIN_ROAS_LIMIT';
    const LIMITED_BY_DATA = 'LIMITED_BY_DATA';
    const LIMITED_BY_BUDGET = 'LIMITED_BY_BUDGET';
    const LIMITED_BY_LOW_PRIORITY_SPEND = 'LIMITED_BY_LOW_PRIORITY_SPEND';
    const LIMITED_BY_LOW_QUALITY = 'LIMITED_BY_LOW_QUALITY';
    const MISCONFIGURED_CONVERSION_TYPES = 'MISCONFIGURED_CONVERSION_TYPES';
    const MISCONFIGURED_CONVERSION_SETTINGS = 'MISCONFIGURED_CONVERSION_SETTINGS';
    const INACTIVE = 'INACTIVE';
    const UNAVAILABLE = 'UNAVAILABLE';
    const MULTIPLE_LEARNING = 'MULTIPLE_LEARNING';
    const MULTIPLE_LIMITED = 'MULTIPLE_LIMITED';
    const MULTIPLE_MISCONFIGURED = 'MULTIPLE_MISCONFIGURED';
    const MULTIPLE = 'MULTIPLE';


}
