<?php

namespace Google\AdsApi\AdManager\v202008;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class VolumeTimeSeriesRequestErrorReason
{
    const HISTORICAL_BASIS_DATE_RANGE_TOO_SHORT = 'HISTORICAL_BASIS_DATE_RANGE_TOO_SHORT';
    const NO_VOLUME_SETTINGS_PROVIDED = 'NO_VOLUME_SETTINGS_PROVIDED';
    const MULTIPLE_VOLUME_SETTINGS_PROVIDED = 'MULTIPLE_VOLUME_SETTINGS_PROVIDED';
    const PARENT_SEGMENT_TARGETING_OPTION_USED_OUTSIDE_OF_ADJUSTMENT_CONTEXT = 'PARENT_SEGMENT_TARGETING_OPTION_USED_OUTSIDE_OF_ADJUSTMENT_CONTEXT';
    const UNKNOWN = 'UNKNOWN';


}
