<?php

namespace Google\AdsApi\AdWords\v201806\rm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class OfflineDataUploadErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const INCOMPATIBLE_USERIDENTIFIER_TYPE = 'INCOMPATIBLE_USERIDENTIFIER_TYPE';
    const INVALID_UPLOAD_TYPE = 'INVALID_UPLOAD_TYPE';
    const MISSING_UPLOAD_METADATA = 'MISSING_UPLOAD_METADATA';
    const INVALID_UPLOAD_METADATA = 'INVALID_UPLOAD_METADATA';
    const INVALID_PARTNER_ID = 'INVALID_PARTNER_ID';
    const MISSING_TRANSACTION_INFO = 'MISSING_TRANSACTION_INFO';
    const INVALID_CONVERSION_TYPE = 'INVALID_CONVERSION_TYPE';
    const FUTURE_TRANSACTION_TIME = 'FUTURE_TRANSACTION_TIME';
    const NEGATIVE_TRANSACTION_AMOUNT = 'NEGATIVE_TRANSACTION_AMOUNT';
    const COUNTRY_CODE_HASHED = 'COUNTRY_CODE_HASHED';
    const ZIPCODE_HASHED = 'ZIPCODE_HASHED';
    const EMAIL_NOT_HASHED = 'EMAIL_NOT_HASHED';
    const FIRST_NAME_NOT_HASHED = 'FIRST_NAME_NOT_HASHED';
    const LAST_NAME_NOT_HASHED = 'LAST_NAME_NOT_HASHED';
    const PHONE_NOT_HASHED = 'PHONE_NOT_HASHED';


}
