<?php

namespace Google\AdsApi\AdWords\v201809\billing;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CustomerOrderLineErrorReason
{
    const INVALID_ORDER_LINE_ID = 'INVALID_ORDER_LINE_ID';
    const END_DATE_BEFORE_START_DATE = 'END_DATE_BEFORE_START_DATE';
    const CREATE_IN_PAST = 'CREATE_IN_PAST';
    const ALREADY_STARTED = 'ALREADY_STARTED';
    const ALREADY_SPENT = 'ALREADY_SPENT';
    const FINISHED_IN_THE_PAST = 'FINISHED_IN_THE_PAST';
    const OVERLAP_DATE_RANGE = 'OVERLAP_DATE_RANGE';
    const END_DATE_PAST_MAX = 'END_DATE_PAST_MAX';
    const PARENT_IS_SELF = 'PARENT_IS_SELF';
    const CANNOT_CANCEL_STARTED = 'CANNOT_CANCEL_STARTED';
    const ORDERLINE_BEING_MODIFIED_IS_NOT_NORMAL_OR_PENDING = 'ORDERLINE_BEING_MODIFIED_IS_NOT_NORMAL_OR_PENDING';
    const MORE_THAN_ONE_OPERATION_NOT_PERMITTED = 'MORE_THAN_ONE_OPERATION_NOT_PERMITTED';
    const INVALID_TIMEZONE_IN_DATE_RANGES = 'INVALID_TIMEZONE_IN_DATE_RANGES';
    const UNKNOWN = 'UNKNOWN';


}
