<?php

namespace Google\AdsApi\AdManager\v202308;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class YieldErrorReason
{
    const INVALID_BACKEND_DATA = 'INVALID_BACKEND_DATA';
    const INVALID_REQUEST_DATA = 'INVALID_REQUEST_DATA';
    const AD_SOURCE_COMPANY_CHANGE = 'AD_SOURCE_COMPANY_CHANGE';
    const UNSUPPORTED_COMPANY_INTEGRATION_TYPE = 'UNSUPPORTED_COMPANY_INTEGRATION_TYPE';
    const UNSUPPORTED_BUYER_SETTINGS = 'UNSUPPORTED_BUYER_SETTINGS';
    const DEPRECATED_AD_NETWORK_ADAPTER = 'DEPRECATED_AD_NETWORK_ADAPTER';
    const TOO_MANY_UPDATES = 'TOO_MANY_UPDATES';
    const DUPLICATE_YIELD_PARTNER = 'DUPLICATE_YIELD_PARTNER';
    const DUPLICATE_HEADER_BIDDER = 'DUPLICATE_HEADER_BIDDER';
    const INTERNAL_ERROR = 'INTERNAL_ERROR';
    const INVALID_EXCHANGE_STATUS = 'INVALID_EXCHANGE_STATUS';
    const INVALID_AD_SOURCE_STATUS = 'INVALID_AD_SOURCE_STATUS';
    const INVALID_SDK_ADAPTER_KEY_NAME = 'INVALID_SDK_ADAPTER_KEY_NAME';
    const INVENTORY_UNIT_MAPPING_NOT_FOUND = 'INVENTORY_UNIT_MAPPING_NOT_FOUND';
    const NO_COMPANIES_PERMISSION = 'NO_COMPANIES_PERMISSION';
    const INVENTORY_UNIT_MAPPING_INVALID_PARAMETER = 'INVENTORY_UNIT_MAPPING_INVALID_PARAMETER';
    const UNKNOWN = 'UNKNOWN';


}
