<?php

namespace Google\AdsApi\AdManager\v202302;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdBreakMarkupType
{
    const AD_BREAK_MARKUP_HLS_EXT_CUE = 'AD_BREAK_MARKUP_HLS_EXT_CUE';
    const AD_BREAK_MARKUP_HLS_PRIMETIME_SPLICE = 'AD_BREAK_MARKUP_HLS_PRIMETIME_SPLICE';
    const AD_BREAK_MARKUP_HLS_DATERANGE_SPLICE = 'AD_BREAK_MARKUP_HLS_DATERANGE_SPLICE';
    const AD_BREAK_MARKUP_SCTE35_XML_SPLICE_INSERT = 'AD_BREAK_MARKUP_SCTE35_XML_SPLICE_INSERT';
    const AD_BREAK_MARKUP_SCTE35_BINARY_SPLICE_INSERT = 'AD_BREAK_MARKUP_SCTE35_BINARY_SPLICE_INSERT';
    const AD_BREAK_MARKUP_SCTE35_BINARY_PROVIDER_AD_START_END = 'AD_BREAK_MARKUP_SCTE35_BINARY_PROVIDER_AD_START_END';
    const AD_BREAK_MARKUP_SCTE35_BINARY_PROVIDER_PLACEMENT_OP_START_END = 'AD_BREAK_MARKUP_SCTE35_BINARY_PROVIDER_PLACEMENT_OP_START_END';
    const AD_BREAK_MARKUP_SCTE35_BINARY_BREAK_START_END = 'AD_BREAK_MARKUP_SCTE35_BINARY_BREAK_START_END';
    const UNKNOWN = 'UNKNOWN';


}
