<?php

namespace Google\AdsApi\AdWords\v201809\rm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CustomAffinityErrorReason
{
    const NAME_ALREADY_USED = 'NAME_ALREADY_USED';
    const CUSTOM_AFFINITY_TOKEN_ID_AND_TYPE_PARAMETER_NOT_PRESENT_IN_REMOVE = 'CUSTOM_AFFINITY_TOKEN_ID_AND_TYPE_PARAMETER_NOT_PRESENT_IN_REMOVE';
    const TYPE_AND_PARAMETER_NOT_FOUND = 'TYPE_AND_PARAMETER_NOT_FOUND';
    const TYPE_AND_PARAMETER_ALREADY_EXISTED = 'TYPE_AND_PARAMETER_ALREADY_EXISTED';
    const INVALID_CUSTOM_AFFINITY_TOKEN_TYPE = 'INVALID_CUSTOM_AFFINITY_TOKEN_TYPE';
    const CANNOT_REMOVE_WHILE_IN_USE = 'CANNOT_REMOVE_WHILE_IN_USE';
    const FIELD_MUTATE_OPERATOR_FOR_TOKENS_IS_NOT_SUPPORTED = 'FIELD_MUTATE_OPERATOR_FOR_TOKENS_IS_NOT_SUPPORTED';
    const READ_ONLY_ENTITY = 'READ_ONLY_ENTITY';
    const CANNOT_CHANGE_TYPE = 'CANNOT_CHANGE_TYPE';
    const CUSTOM_AFFINITY_SERVICE_ERROR = 'CUSTOM_AFFINITY_SERVICE_ERROR';


}
