<?php

namespace Google\AdsApi\AdWords\v201809\rm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class SizeRange
{
    const LESS_THAN_FIVE_HUNDRED = 'LESS_THAN_FIVE_HUNDRED';
    const LESS_THAN_ONE_THOUSAND = 'LESS_THAN_ONE_THOUSAND';
    const ONE_THOUSAND_TO_TEN_THOUSAND = 'ONE_THOUSAND_TO_TEN_THOUSAND';
    const TEN_THOUSAND_TO_FIFTY_THOUSAND = 'TEN_THOUSAND_TO_FIFTY_THOUSAND';
    const FIFTY_THOUSAND_TO_ONE_HUNDRED_THOUSAND = 'FIFTY_THOUSAND_TO_ONE_HUNDRED_THOUSAND';
    const ONE_HUNDRED_THOUSAND_TO_THREE_HUNDRED_THOUSAND = 'ONE_HUNDRED_THOUSAND_TO_THREE_HUNDRED_THOUSAND';
    const THREE_HUNDRED_THOUSAND_TO_FIVE_HUNDRED_THOUSAND = 'THREE_HUNDRED_THOUSAND_TO_FIVE_HUNDRED_THOUSAND';
    const FIVE_HUNDRED_THOUSAND_TO_ONE_MILLION = 'FIVE_HUNDRED_THOUSAND_TO_ONE_MILLION';
    const ONE_MILLION_TO_TWO_MILLION = 'ONE_MILLION_TO_TWO_MILLION';
    const TWO_MILLION_TO_THREE_MILLION = 'TWO_MILLION_TO_THREE_MILLION';
    const THREE_MILLION_TO_FIVE_MILLION = 'THREE_MILLION_TO_FIVE_MILLION';
    const FIVE_MILLION_TO_TEN_MILLION = 'FIVE_MILLION_TO_TEN_MILLION';
    const TEN_MILLION_TO_TWENTY_MILLION = 'TEN_MILLION_TO_TWENTY_MILLION';
    const TWENTY_MILLION_TO_THIRTY_MILLION = 'TWENTY_MILLION_TO_THIRTY_MILLION';
    const THIRTY_MILLION_TO_FIFTY_MILLION = 'THIRTY_MILLION_TO_FIFTY_MILLION';
    const OVER_FIFTY_MILLION = 'OVER_FIFTY_MILLION';


}
