<?php

namespace Google\AdsApi\AdManager\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AudienceExtensionErrorReason
{
    const FREQUENCY_CAPS_NOT_SUPPORTED = 'FREQUENCY_CAPS_NOT_SUPPORTED';
    const INVALID_TARGETING = 'INVALID_TARGETING';
    const INVENTORY_UNIT_TARGETING_INVALID = 'INVENTORY_UNIT_TARGETING_INVALID';
    const INVALID_CREATIVE_ROTATION = 'INVALID_CREATIVE_ROTATION';
    const INVALID_EXTERNAL_ENTITY_ID = 'INVALID_EXTERNAL_ENTITY_ID';
    const INVALID_LINE_ITEM_TYPE = 'INVALID_LINE_ITEM_TYPE';
    const INVALID_MAX_BID = 'INVALID_MAX_BID';
    const AUDIENCE_EXTENSION_BULK_UPDATE_NOT_ALLOWED = 'AUDIENCE_EXTENSION_BULK_UPDATE_NOT_ALLOWED';
    const UNEXPECTED_AUDIENCE_EXTENSION_ERROR = 'UNEXPECTED_AUDIENCE_EXTENSION_ERROR';
    const MAX_DAILY_BUDGET_AMOUNT_EXCEEDED = 'MAX_DAILY_BUDGET_AMOUNT_EXCEEDED';
    const EXTERNAL_CAMPAIGN_ALREADY_EXISTS = 'EXTERNAL_CAMPAIGN_ALREADY_EXISTS';
    const AUDIENCE_EXTENSION_WITHOUT_FEATURE = 'AUDIENCE_EXTENSION_WITHOUT_FEATURE';
    const AUDIENCE_EXTENSION_WITHOUT_LINKED_ACCOUNT = 'AUDIENCE_EXTENSION_WITHOUT_LINKED_ACCOUNT';
    const CANNOT_OVERRIDE_CREATIVE_SIZE_WITH_AUDIENCE_EXTENSION = 'CANNOT_OVERRIDE_CREATIVE_SIZE_WITH_AUDIENCE_EXTENSION';
    const CANNOT_OVERRIDE_FIELD_WITH_AUDIENCE_EXTENSION = 'CANNOT_OVERRIDE_FIELD_WITH_AUDIENCE_EXTENSION';
    const ONLY_ONE_CREATIVE_PLACEHOLDER_ALLOWED = 'ONLY_ONE_CREATIVE_PLACEHOLDER_ALLOWED';
    const MULTIPLE_AUDIENCE_EXTENSION_LINE_ITEMS_ON_ORDER = 'MULTIPLE_AUDIENCE_EXTENSION_LINE_ITEMS_ON_ORDER';
    const CANNOT_COPY_AUDIENCE_EXTENSION_LINE_ITEMS_AND_CREATIVES_TOGETHER = 'CANNOT_COPY_AUDIENCE_EXTENSION_LINE_ITEMS_AND_CREATIVES_TOGETHER';
    const FEATURE_DEPRECATED = 'FEATURE_DEPRECATED';
    const UNKNOWN = 'UNKNOWN';


}
