<?php

namespace Google\AdsApi\AdManager\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CreativeSetErrorReason
{
    const VIDEO_FEATURE_REQUIRED = 'VIDEO_FEATURE_REQUIRED';
    const CANNOT_CREATE_OR_UPDATE_VIDEO_CREATIVES = 'CANNOT_CREATE_OR_UPDATE_VIDEO_CREATIVES';
    const ROADBLOCK_FEATURE_REQUIRED = 'ROADBLOCK_FEATURE_REQUIRED';
    const MASTER_CREATIVE_CANNOT_BE_COMPANION = 'MASTER_CREATIVE_CANNOT_BE_COMPANION';
    const INVALID_ADVERTISER = 'INVALID_ADVERTISER';
    const UPDATE_MASTER_CREATIVE_NOT_ALLOWED = 'UPDATE_MASTER_CREATIVE_NOT_ALLOWED';
    const MASTER_CREATIVE_CANNOT_BELONG_TO_MULTIPLE_VIDEO_CREATIVE_SETS = 'MASTER_CREATIVE_CANNOT_BELONG_TO_MULTIPLE_VIDEO_CREATIVE_SETS';
    const UNKNOWN = 'UNKNOWN';


}
