<?php

namespace Google\AdsApi\AdManager\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CustomCreativeErrorReason
{
    const DUPLICATE_MACRO_NAME_FOR_CREATIVE = 'DUPLICATE_MACRO_NAME_FOR_CREATIVE';
    const SNIPPET_REFERENCES_MISSING_MACRO = 'SNIPPET_REFERENCES_MISSING_MACRO';
    const UNRECOGNIZED_MACRO = 'UNRECOGNIZED_MACRO';
    const CUSTOM_CREATIVE_NOT_ALLOWED = 'CUSTOM_CREATIVE_NOT_ALLOWED';
    const MISSING_INTERSTITIAL_MACRO = 'MISSING_INTERSTITIAL_MACRO';
    const DUPLICATE_ASSET_IN_MACROS = 'DUPLICATE_ASSET_IN_MACROS';
    const UNKNOWN = 'UNKNOWN';


}
