<?php

namespace Google\AdsApi\AdManager\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class EntityChildrenLimitReachedErrorReason
{
    const LINE_ITEM_LIMIT_FOR_ORDER_REACHED = 'LINE_ITEM_LIMIT_FOR_ORDER_REACHED';
    const CREATIVE_ASSOCIATION_LIMIT_FOR_LINE_ITEM_REACHED = 'CREATIVE_ASSOCIATION_LIMIT_FOR_LINE_ITEM_REACHED';
    const AD_UNIT_LIMIT_FOR_PLACEMENT_REACHED = 'AD_UNIT_LIMIT_FOR_PLACEMENT_REACHED';
    const TARGETING_EXPRESSION_LIMIT_FOR_LINE_ITEM_REACHED = 'TARGETING_EXPRESSION_LIMIT_FOR_LINE_ITEM_REACHED';
    const CUSTOM_TARGETING_VALUES_FOR_KEY_LIMIT_REACHED = 'CUSTOM_TARGETING_VALUES_FOR_KEY_LIMIT_REACHED';
    const TARGETING_EXPRESSION_LIMIT_FOR_CREATIVES_ON_LINE_ITEM_REACHED = 'TARGETING_EXPRESSION_LIMIT_FOR_CREATIVES_ON_LINE_ITEM_REACHED';
    const ATTACHMENT_LIMIT_FOR_PROPOSAL_REACHED = 'ATTACHMENT_LIMIT_FOR_PROPOSAL_REACHED';
    const PROPOSAL_LINE_ITEM_LIMIT_FOR_PROPOSAL_REACHED = 'PROPOSAL_LINE_ITEM_LIMIT_FOR_PROPOSAL_REACHED';
    const PRODUCT_LIMIT_FOR_PRODUCT_PACKAGE_REACHED = 'PRODUCT_LIMIT_FOR_PRODUCT_PACKAGE_REACHED';
    const PRODUCT_TEMPLATE_AND_PRODUCT_BASE_RATE_LIMIT_FOR_RATE_CARD_REACHED = 'PRODUCT_TEMPLATE_AND_PRODUCT_BASE_RATE_LIMIT_FOR_RATE_CARD_REACHED';
    const PRODUCT_PACKAGE_ITEM_BASE_RATE_LIMIT_FOR_RATE_CARD_REACHED = 'PRODUCT_PACKAGE_ITEM_BASE_RATE_LIMIT_FOR_RATE_CARD_REACHED';
    const PREMIUM_LIMIT_FOR_RATE_CARD_REACHED = 'PREMIUM_LIMIT_FOR_RATE_CARD_REACHED';
    const AD_UNIT_LIMIT_FOR_AD_EXCLUSION_RULE_TARGETING_REACHED = 'AD_UNIT_LIMIT_FOR_AD_EXCLUSION_RULE_TARGETING_REACHED';
    const NATIVE_STYLE_LIMIT_FOR_NATIVE_AD_FORMAT_REACHED = 'NATIVE_STYLE_LIMIT_FOR_NATIVE_AD_FORMAT_REACHED';
    const UNKNOWN = 'UNKNOWN';


}
