<?php

namespace Google\AdsApi\AdManager\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class OrderActionErrorReason
{
    const PERMISSION_DENIED = 'PERMISSION_DENIED';
    const NOT_APPLICABLE = 'NOT_APPLICABLE';
    const IS_ARCHIVED = 'IS_ARCHIVED';
    const HAS_ENDED = 'HAS_ENDED';
    const CANNOT_APPROVE_WITH_UNRESERVED_LINE_ITEMS = 'CANNOT_APPROVE_WITH_UNRESERVED_LINE_ITEMS';
    const CANNOT_DELETE_ORDER_WITH_DELIVERED_LINEITEMS = 'CANNOT_DELETE_ORDER_WITH_DELIVERED_LINEITEMS';
    const CANNOT_APPROVE_COMPANY_CREDIT_STATUS_NOT_ACTIVE = 'CANNOT_APPROVE_COMPANY_CREDIT_STATUS_NOT_ACTIVE';
    const UNKNOWN = 'UNKNOWN';


}
