<?php

namespace Google\AdsApi\AdManager\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class TeamErrorReason
{
    const ENTITY_NOT_ON_USERS_TEAMS = 'ENTITY_NOT_ON_USERS_TEAMS';
    const AD_UNITS_NOT_ON_ORDER_TEAMS = 'AD_UNITS_NOT_ON_ORDER_TEAMS';
    const PLACEMENTS_NOT_ON_ORDER_TEAMS = 'PLACEMENTS_NOT_ON_ORDER_TEAMS';
    const MISSING_USERS_TEAM = 'MISSING_USERS_TEAM';
    const ALL_TEAM_ASSOCIATION_NOT_ALLOWED = 'ALL_TEAM_ASSOCIATION_NOT_ALLOWED';
    const INVALID_TEAM_ASSIGNMENT = 'INVALID_TEAM_ASSIGNMENT';
    const ALL_TEAM_ACCESS_OVERRIDE_NOT_ALLOWED = 'ALL_TEAM_ACCESS_OVERRIDE_NOT_ALLOWED';
    const CANNOT_UPDATE_INACTIVE_TEAM = 'CANNOT_UPDATE_INACTIVE_TEAM';
    const UNKNOWN = 'UNKNOWN';


}
