<?php

namespace Google\AdsApi\AdManager\v202211;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ExchangeSignupApiErrorReason
{
    const ADSENSE_ACCOUNT_CREATION_ERROR = 'ADSENSE_ACCOUNT_CREATION_ERROR';
    const ADSENSE_ACCOUNT_ALREADY_HAS_EXCHANGE = 'ADSENSE_ACCOUNT_ALREADY_HAS_EXCHANGE';
    const FAILED_TO_ADD_WEBSITE_TO_PROPERTY = 'FAILED_TO_ADD_WEBSITE_TO_PROPERTY';
    const FAILED_TO_CREATE_LINK_FOR_NEW_ACCOUNT = 'FAILED_TO_CREATE_LINK_FOR_NEW_ACCOUNT';
    const CANNOT_CREATE_NEW_ACCOUNT_FOR_MAPPED_CUSTOMER = 'CANNOT_CREATE_NEW_ACCOUNT_FOR_MAPPED_CUSTOMER';
    const FAILED_TO_CREATE_EXCHANGE_SETTINGS = 'FAILED_TO_CREATE_EXCHANGE_SETTINGS';
    const DUPLICATE_PRODUCT_TYPE = 'DUPLICATE_PRODUCT_TYPE';
    const INVALID_SIGNUP_PRODUCT = 'INVALID_SIGNUP_PRODUCT';
    const UNKNOWN_PRODUCT = 'UNKNOWN_PRODUCT';
    const BAD_SITE_VERIFICATION_UPDATE_REQUEST = 'BAD_SITE_VERIFICATION_UPDATE_REQUEST';
    const NO_EXCHANGE_ACCOUNT = 'NO_EXCHANGE_ACCOUNT';
    const SINGLE_SYNDICATION_PRODUCT = 'SINGLE_SYNDICATION_PRODUCT';
    const ACCOUNT_NOT_YET_READY = 'ACCOUNT_NOT_YET_READY';
    const MULTIPLE_ADSENSE_ACCOUNTS_NOT_ALLOWED = 'MULTIPLE_ADSENSE_ACCOUNTS_NOT_ALLOWED';
    const MISSING_LEGAL_ENTITY_NAME = 'MISSING_LEGAL_ENTITY_NAME';
    const MISSING_ACTIVE_BILLING_PROFILE = 'MISSING_ACTIVE_BILLING_PROFILE';
    const UNKNOWN = 'UNKNOWN';


}
