<?php

namespace Google\AdsApi\AdManager\v202608;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdProductBookingErrorReason
{
    const AD_PRODUCT_NOT_FOUND = 'AD_PRODUCT_NOT_FOUND';
    const AD_PRODUCT_NOT_ACTIVE = 'AD_PRODUCT_NOT_ACTIVE';
    const AD_PRODUCT_PRICING_NOT_FOUND = 'AD_PRODUCT_PRICING_NOT_FOUND';
    const AD_PRODUCT_PRICING_MISMATCH = 'AD_PRODUCT_PRICING_MISMATCH';
    const AD_PRODUCT_ADD_ON_PRICING_NOT_FOUND = 'AD_PRODUCT_ADD_ON_PRICING_NOT_FOUND';
    const AD_PRODUCT_ADD_ON_PRICING_RATE_CARD_MISMATCH = 'AD_PRODUCT_ADD_ON_PRICING_RATE_CARD_MISMATCH';
    const UNKNOWN = 'UNKNOWN';


}
