<?php

namespace Google\AdsApi\AdManager\v202002;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class NetworkErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const MULTI_CURRENCY_NOT_SUPPORTED = 'MULTI_CURRENCY_NOT_SUPPORTED';
    const UNSUPPORTED_CURRENCY = 'UNSUPPORTED_CURRENCY';
    const NETWORK_CURRENCY_CANNOT_BE_SAME_AS_SECONDARY = 'NETWORK_CURRENCY_CANNOT_BE_SAME_AS_SECONDARY';
    const CANNOT_DELETE_CURRENCY_WITH_ACTIVE_RATE_CARDS = 'CANNOT_DELETE_CURRENCY_WITH_ACTIVE_RATE_CARDS';
    const DELEGATION_CHILD_NETWORK_CANNOT_BECOME_A_PARENT = 'DELEGATION_CHILD_NETWORK_CANNOT_BECOME_A_PARENT';
    const DELEGATION_PARENT_NETWORK_CANNOT_BECOME_A_CHILD = 'DELEGATION_PARENT_NETWORK_CANNOT_BECOME_A_CHILD';
    const CANNOT_ADD_SAME_NETWORK_AS_DELEGATION_CHILD = 'CANNOT_ADD_SAME_NETWORK_AS_DELEGATION_CHILD';
    const MAX_APPROVED_DELEGATION_CHILD_NETWORKS_EXCEEDED = 'MAX_APPROVED_DELEGATION_CHILD_NETWORKS_EXCEEDED';
    const CHILD_NETWORK_ALREADY_EXISTS = 'CHILD_NETWORK_ALREADY_EXISTS';
    const IN_PARENT_DELEGATION_UNSUPPORTED_FOR_NETWORK = 'IN_PARENT_DELEGATION_UNSUPPORTED_FOR_NETWORK';


}
