<?php

namespace Google\AdsApi\AdWords\v201607\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BatchJobOpsService extends \Google\AdsApi\Common\AdsSoapClient
{

    /**
     * @var array $classmap The defined classes
     */
    private static $classmap = array (
      'Ad' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Ad',
      'AdCustomizerError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdCustomizerError',
      'AdError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdError',
      'AdGroup' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroup',
      'AdGroupAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupAd',
      'AdGroupAdCountLimitExceeded' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupAdCountLimitExceeded',
      'AdGroupAdError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupAdError',
      'AdGroupAdExperimentData' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupAdExperimentData',
      'AdGroupAdLabel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupAdLabel',
      'AdGroupAdLabelOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupAdLabelOperation',
      'AdGroupAdOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupAdOperation',
      'AdGroupBidModifier' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupBidModifier',
      'AdGroupBidModifierOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupBidModifierOperation',
      'AdGroupCriterion' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupCriterion',
      'AdGroupCriterionError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupCriterionError',
      'AdGroupCriterionExperimentBidMultiplier' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupCriterionExperimentBidMultiplier',
      'AdGroupCriterionLabel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupCriterionLabel',
      'AdGroupCriterionLabelOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupCriterionLabelOperation',
      'AdGroupCriterionLimitExceeded' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupCriterionLimitExceeded',
      'AdGroupCriterionOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupCriterionOperation',
      'AdGroupExperimentBidMultipliers' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupExperimentBidMultipliers',
      'AdGroupExperimentData' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupExperimentData',
      'AdGroupExtensionSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupExtensionSetting',
      'AdGroupExtensionSettingOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupExtensionSettingOperation',
      'AdGroupLabel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupLabel',
      'AdGroupLabelOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupLabelOperation',
      'AdGroupOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupOperation',
      'AdGroupServiceError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdGroupServiceError',
      'AdSchedule' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdSchedule',
      'AdUnionId' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdUnionId',
      'Address' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Address',
      'AdxError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AdxError',
      'AgeRange' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AgeRange',
      'ApiError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ApiError',
      'ApiException' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ApiException',
      'AppFeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AppFeedItem',
      'AppPaymentModel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AppPaymentModel',
      'AppUrl' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AppUrl',
      'AppUrlList' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AppUrlList',
      'ApplicationException' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ApplicationException',
      'LabelAttribute' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\LabelAttribute',
      'Audio' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Audio',
      'AuthenticationError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AuthenticationError',
      'AuthorizationError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\AuthorizationError',
      'Bid' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Bid',
      'BidMultiplier' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BidMultiplier',
      'BiddableAdGroupCriterion' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BiddableAdGroupCriterion',
      'BiddableAdGroupCriterionExperimentData' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BiddableAdGroupCriterionExperimentData',
      'BiddingErrors' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BiddingErrors',
      'BiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BiddingScheme',
      'BiddingStrategyConfiguration' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BiddingStrategyConfiguration',
      'Bids' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Bids',
      'Budget' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Budget',
      'BudgetError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BudgetError',
      'BudgetOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BudgetOperation',
      'BudgetOptimizerBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\BudgetOptimizerBiddingScheme',
      'CallConversionType' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CallConversionType',
      'CallFeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CallFeedItem',
      'CallOnlyAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CallOnlyAd',
      'CalloutFeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CalloutFeedItem',
      'Campaign' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Campaign',
      'CampaignCriterion' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignCriterion',
      'CampaignCriterionError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignCriterionError',
      'CampaignCriterionOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignCriterionOperation',
      'CampaignError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignError',
      'CampaignExtensionSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignExtensionSetting',
      'CampaignExtensionSettingOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignExtensionSettingOperation',
      'CampaignLabel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignLabel',
      'CampaignLabelOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignLabelOperation',
      'TextLabel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TextLabel',
      'DisplayAttribute' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DisplayAttribute',
      'CampaignOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CampaignOperation',
      'Carrier' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Carrier',
      'ClientTermsError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ClientTermsError',
      'CollectionSizeError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CollectionSizeError',
      'ComparableValue' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ComparableValue',
      'ConstantOperand' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ConstantOperand',
      'ContentLabel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ContentLabel',
      'ConversionOptimizerBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ConversionOptimizerBiddingScheme',
      'ConversionOptimizerEligibility' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ConversionOptimizerEligibility',
      'CpaBid' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CpaBid',
      'CpcBid' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CpcBid',
      'CpmBid' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CpmBid',
      'Criterion' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Criterion',
      'CriterionError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CriterionError',
      'CriterionParameter' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CriterionParameter',
      'CriterionPolicyError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CriterionPolicyError',
      'CustomParameter' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CustomParameter',
      'CustomParameters' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CustomParameters',
      'CustomerExtensionSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CustomerExtensionSetting',
      'CustomerExtensionSettingOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CustomerExtensionSettingOperation',
      'DatabaseError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DatabaseError',
      'DateError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DateError',
      'DateRangeError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DateRangeError',
      'DeprecatedAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DeprecatedAd',
      'Dimensions' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Dimensions',
      'DisapprovalReason' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DisapprovalReason',
      'DistinctError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DistinctError',
      'DoubleValue' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DoubleValue',
      'DynamicSearchAdsSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DynamicSearchAdsSetting',
      'EnhancedCpcBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\EnhancedCpcBiddingScheme',
      'EntityAccessDenied' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\EntityAccessDenied',
      'EntityCountLimitExceeded' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\EntityCountLimitExceeded',
      'EntityNotFound' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\EntityNotFound',
      'ErrorList' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ErrorList',
      'ExemptionRequest' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ExemptionRequest',
      'ExpandedTextAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ExpandedTextAd',
      'ExperimentError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ExperimentError',
      'ExplorerAutoOptimizerSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ExplorerAutoOptimizerSetting',
      'ExtensionFeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ExtensionFeedItem',
      'ExtensionSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ExtensionSetting',
      'ExtensionSettingError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ExtensionSettingError',
      'FeedAttributeReferenceError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedAttributeReferenceError',
      'FeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItem',
      'FeedItemAdGroupTargeting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemAdGroupTargeting',
      'FeedItemAttributeError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemAttributeError',
      'FeedItemAttributeValue' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemAttributeValue',
      'FeedItemCampaignTargeting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemCampaignTargeting',
      'FeedItemDevicePreference' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemDevicePreference',
      'FeedItemError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemError',
      'FeedItemGeoRestriction' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemGeoRestriction',
      'FeedItemOperation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemOperation',
      'FeedItemPolicyData' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemPolicyData',
      'FeedItemSchedule' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemSchedule',
      'FeedItemScheduling' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FeedItemScheduling',
      'ForwardCompatibilityError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ForwardCompatibilityError',
      'FrequencyCap' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FrequencyCap',
      'Function' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MatchingFunction',
      'FunctionError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FunctionError',
      'FunctionParsingError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FunctionParsingError',
      'Gender' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Gender',
      'GeoPoint' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\GeoPoint',
      'GeoTargetOperand' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\GeoTargetOperand',
      'GeoTargetTypeSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\GeoTargetTypeSetting',
      'IdError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\IdError',
      'Image' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Image',
      'ImageAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ImageAd',
      'ImageError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ImageError',
      'IncomeOperand' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\IncomeOperand',
      'InternalApiError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\InternalApiError',
      'IpBlock' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\IpBlock',
      'Keyword' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Keyword',
      'Label' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Label',
      'Language' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Language',
      'Location' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Location',
      'LocationExtensionOperand' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\LocationExtensionOperand',
      'LongValue' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\LongValue',
      'ManualCPCAdGroupCriterionExperimentBidMultiplier' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ManualCPCAdGroupCriterionExperimentBidMultiplier',
      'ManualCPCAdGroupExperimentBidMultipliers' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ManualCPCAdGroupExperimentBidMultipliers',
      'ManualCPMAdGroupExperimentBidMultipliers' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ManualCPMAdGroupExperimentBidMultipliers',
      'ManualCpcBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ManualCpcBiddingScheme',
      'ManualCpmBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ManualCpmBiddingScheme',
      'Media' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Media',
      'MediaBundle' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MediaBundle',
      'MediaBundleError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MediaBundleError',
      'MediaError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MediaError',
      'Media_Size_DimensionsMapEntry' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Media_Size_DimensionsMapEntry',
      'Media_Size_StringMapEntry' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Media_Size_StringMapEntry',
      'MobileAppCategory' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MobileAppCategory',
      'MobileApplication' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MobileApplication',
      'MobileDevice' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MobileDevice',
      'Money' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Money',
      'MoneyWithCurrency' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MoneyWithCurrency',
      'MultiplierError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MultiplierError',
      'MutateResult' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\MutateResult',
      'NegativeAdGroupCriterion' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\NegativeAdGroupCriterion',
      'NegativeCampaignCriterion' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\NegativeCampaignCriterion',
      'NetworkSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\NetworkSetting',
      'NewEntityCreationError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\NewEntityCreationError',
      'NotEmptyError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\NotEmptyError',
      'NullError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\NullError',
      'NumberValue' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\NumberValue',
      'FunctionArgumentOperand' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\FunctionArgumentOperand',
      'Operand' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Operand',
      'OperatingSystemVersion' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\OperatingSystemVersion',
      'Operation' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Operation',
      'OperationAccessDenied' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\OperationAccessDenied',
      'OperatorError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\OperatorError',
      'PageOnePromotedBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PageOnePromotedBiddingScheme',
      'PagingError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PagingError',
      'Parent' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ParentCriterion',
      'Placement' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Placement',
      'PlacesOfInterestOperand' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PlacesOfInterestOperand',
      'Platform' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Platform',
      'PolicyData' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PolicyData',
      'PolicyViolationError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PolicyViolationError',
      'PolicyViolationError.Part' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PolicyViolationErrorPart',
      'PolicyViolationKey' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PolicyViolationKey',
      'PriceFeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PriceFeedItem',
      'PriceTableRow' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\PriceTableRow',
      'ProductAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductAd',
      'ProductAdwordsGrouping' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductAdwordsGrouping',
      'ProductAdwordsLabels' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductAdwordsLabels',
      'ProductBiddingCategory' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductBiddingCategory',
      'ProductBrand' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductBrand',
      'ProductCanonicalCondition' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductCanonicalCondition',
      'ProductChannel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductChannel',
      'ProductChannelExclusivity' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductChannelExclusivity',
      'ProductLegacyCondition' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductLegacyCondition',
      'ProductCustomAttribute' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductCustomAttribute',
      'ProductDimension' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductDimension',
      'ProductOfferId' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductOfferId',
      'ProductPartition' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductPartition',
      'ProductScope' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductScope',
      'ProductType' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductType',
      'ProductTypeFull' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ProductTypeFull',
      'Proximity' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Proximity',
      'QualityInfo' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\QualityInfo',
      'QueryError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\QueryError',
      'QuotaCheckError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\QuotaCheckError',
      'RangeError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\RangeError',
      'RateExceededError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\RateExceededError',
      'ReadOnlyError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ReadOnlyError',
      'RealTimeBiddingSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\RealTimeBiddingSetting',
      'RegionCodeError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\RegionCodeError',
      'RejectedError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\RejectedError',
      'RequestError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\RequestError',
      'RequiredError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\RequiredError',
      'ResponsiveDisplayAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ResponsiveDisplayAd',
      'ReviewFeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ReviewFeedItem',
      'RichMediaAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\RichMediaAd',
      'SelectorError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\SelectorError',
      'LocationGroups' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\LocationGroups',
      'Setting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Setting',
      'SettingError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\SettingError',
      'ShoppingSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ShoppingSetting',
      'SitelinkFeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\SitelinkFeedItem',
      'SizeLimitError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\SizeLimitError',
      'StatsQueryError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\StatsQueryError',
      'StringFormatError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\StringFormatError',
      'StringLengthError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\StringLengthError',
      'String_StringMapEntry' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\String_StringMapEntry',
      'StructuredSnippetFeedItem' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\StructuredSnippetFeedItem',
      'TargetCpaBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TargetCpaBiddingScheme',
      'TargetOutrankShareBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TargetOutrankShareBiddingScheme',
      'TargetingSettingDetail' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TargetingSettingDetail',
      'TargetRoasBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TargetRoasBiddingScheme',
      'TargetSpendBiddingScheme' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TargetSpendBiddingScheme',
      'TargetingSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TargetingSetting',
      'TempAdUnionId' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TempAdUnionId',
      'TemplateAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TemplateAd',
      'TemplateElement' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TemplateElement',
      'TemplateElementField' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TemplateElementField',
      'TextAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TextAd',
      'ThirdPartyRedirectAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\ThirdPartyRedirectAd',
      'TrackingSetting' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\TrackingSetting',
      'UnknownProductDimension' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\UnknownProductDimension',
      'UrlError' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\UrlError',
      'UrlList' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\UrlList',
      'CriterionUserInterest' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CriterionUserInterest',
      'CriterionUserList' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\CriterionUserList',
      'VanityPharma' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\VanityPharma',
      'Vertical' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Vertical',
      'Video' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Video',
      'Webpage' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\Webpage',
      'WebpageCondition' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\WebpageCondition',
      'WebpageParameter' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\WebpageParameter',
      'DynamicSearchAd' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\DynamicSearchAd',
      'YouTubeChannel' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\YouTubeChannel',
      'YouTubeVideo' => 'Google\\AdsApi\\AdWords\\v201607\\cm\\YouTubeVideo',
    );

    /**
     * @param array $options A array of config values
     * @param string $wsdl The wsdl file to use
     */
    public function __construct(array $options = array(),
                $wsdl = 'https://adwords.google.com/api/adwords/cm/v201607/BatchJobOpsService?wsdl')
    {
      foreach (self::$classmap as $key => $value) {
        if (!isset($options['classmap'][$key])) {
          $options['classmap'][$key] = $value;
        }
      }
      $options = array_merge(array (
      'features' => 1,
    ), $options);
      parent::__construct($wsdl, $options);
    }

    /**
     * @param \Google\AdsApi\AdWords\v201607\cm\Operation[] $operations
     * @return \Google\AdsApi\AdWords\v201607\cm\MutateResult[]
     * @throws \Google\AdsApi\AdWords\v201607\cm\ApiException
     */
    public function mutate(array $operations)
    {
      return $this->__soapCall('mutate', array(array('operations' => $operations)))->rval;
    }

}
