<?php

namespace Google\AdsApi\AdWords\v201607\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class FeedItemQualityDisapprovalReasons
{
    const __default = 'UNKNOWN';
    const UNKNOWN = 'UNKNOWN';
    const TABLE_REPETITIVE_HEADERS = 'TABLE_REPETITIVE_HEADERS';
    const TABLE_REPETITIVE_DESCRIPTION = 'TABLE_REPETITIVE_DESCRIPTION';
    const TABLE_INCONSISTENT_ROWS = 'TABLE_INCONSISTENT_ROWS';
    const TABLE_ROW_HEADER_TABLE_TYPE_MISMATCH = 'TABLE_ROW_HEADER_TABLE_TYPE_MISMATCH';
    const TABLE_ROW_HEADER_HAS_PROMOTIONAL_TEXT = 'TABLE_ROW_HEADER_HAS_PROMOTIONAL_TEXT';
    const TABLE_ROW_DESCRIPTION_NOT_RELEVANT = 'TABLE_ROW_DESCRIPTION_NOT_RELEVANT';
    const TABLE_ROW_DESCRIPTION_HAS_PROMOTIONAL_TEXT = 'TABLE_ROW_DESCRIPTION_HAS_PROMOTIONAL_TEXT';
    const TABLE_ROW_HEADER_DESCRIPTION_REPETITIVE = 'TABLE_ROW_HEADER_DESCRIPTION_REPETITIVE';
    const TABLE_ROW_UNRATEABLE = 'TABLE_ROW_UNRATEABLE';
    const TABLE_ROW_PRICE_INVALID = 'TABLE_ROW_PRICE_INVALID';
    const TABLE_ROW_URL_INVALID = 'TABLE_ROW_URL_INVALID';
    const STRUCTURED_SNIPPETS_HEADER_POLICY_VIOLATED = 'STRUCTURED_SNIPPETS_HEADER_POLICY_VIOLATED';
    const STRUCTURED_SNIPPETS_REPEATED_VALUES = 'STRUCTURED_SNIPPETS_REPEATED_VALUES';
    const STRUCTURED_SNIPPETS_EDITORIAL_GUIDELINES = 'STRUCTURED_SNIPPETS_EDITORIAL_GUIDELINES';
    const STRUCTURED_SNIPPETS_HAS_PROMOTIONAL_TEXT = 'STRUCTURED_SNIPPETS_HAS_PROMOTIONAL_TEXT';


}
