<?php

namespace Google\AdsApi\AdWords\v201609\billing;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CustomerOrderLineErrorReason
{
    const INVALID_ORDER_LINE_ID = 'INVALID_ORDER_LINE_ID';
    const END_DATE_BEFORE_START_DATE = 'END_DATE_BEFORE_START_DATE';
    const NEGATIVE_SPEND = 'NEGATIVE_SPEND';
    const CREATE_IN_PAST = 'CREATE_IN_PAST';
    const ALREADY_STARTED = 'ALREADY_STARTED';
    const ALREADY_SPENT = 'ALREADY_SPENT';
    const FINISHED_IN_THE_PAST = 'FINISHED_IN_THE_PAST';
    const CANCEL_ACTIVE = 'CANCEL_ACTIVE';
    const OVERLAP_DATE_RANGE = 'OVERLAP_DATE_RANGE';
    const COS_CHANGE = 'COS_CHANGE';
    const NON_ADWORDS = 'NON_ADWORDS';
    const START_DATE_AFTER_ACTUAL = 'START_DATE_AFTER_ACTUAL';
    const END_DATE_PAST_MAX = 'END_DATE_PAST_MAX';
    const PARENT_IS_SELF = 'PARENT_IS_SELF';
    const CANNOT_CANCEL_NEW = 'CANNOT_CANCEL_NEW';
    const CANNOT_CANCEL_STARTED = 'CANNOT_CANCEL_STARTED';
    const CANNOT_PROMOTE_NON_PENDING_ORDERLINE = 'CANNOT_PROMOTE_NON_PENDING_ORDERLINE';
    const UPDATE_ORDERLINE_WILL_SHIFT_CURRENT = 'UPDATE_ORDERLINE_WILL_SHIFT_CURRENT';
    const ORDERLINE_BEING_MODIFIED_IS_NOT_NORMAL_OR_PENDING = 'ORDERLINE_BEING_MODIFIED_IS_NOT_NORMAL_OR_PENDING';
    const INVALID_STATUS_CHANGE = 'INVALID_STATUS_CHANGE';
    const MORE_THAN_ONE_OPERATION_NOT_PERMITTED = 'MORE_THAN_ONE_OPERATION_NOT_PERMITTED';
    const INVALID_TIMEZONE_IN_DATE_RANGES = 'INVALID_TIMEZONE_IN_DATE_RANGES';
    const UNKNOWN = 'UNKNOWN';


}
