<?php

namespace Google\AdsApi\AdManager\v201911;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class MetadataMergeSpecErrorReason
{
    const INPUT_ID_ALREADY_USED = 'INPUT_ID_ALREADY_USED';
    const BOUND_SPECIFIED_WITHOUT_VALUE = 'BOUND_SPECIFIED_WITHOUT_VALUE';
    const VALUE_SPECIFIED_WITHOUT_BOUND = 'VALUE_SPECIFIED_WITHOUT_BOUND';
    const MIN_EXCEEDS_MAX = 'MIN_EXCEEDS_MAX';
    const MORE_THAN_ONE_INPUT_KEY_HAS_VALUE_RULES = 'MORE_THAN_ONE_INPUT_KEY_HAS_VALUE_RULES';
    const VALUE_SPECIFIED_DOES_NOT_MATCH_OUTPUT_KEY = 'VALUE_SPECIFIED_DOES_NOT_MATCH_OUTPUT_KEY';
    const CANNOT_MERGE_VALUES_WHERE_VALUE_BUCKET_EXISTS = 'CANNOT_MERGE_VALUES_WHERE_VALUE_BUCKET_EXISTS';
    const CANNOT_MODIFY_RESERVED_KEY = 'CANNOT_MODIFY_RESERVED_KEY';
    const UNKNOWN = 'UNKNOWN';


}
