<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdCustomizerFeedErrorReason
{
    const CANNOT_ADD_KEY_ATTRIBUTE = 'CANNOT_ADD_KEY_ATTRIBUTE';
    const NOT_AD_CUSTOMIZER_FEED = 'NOT_AD_CUSTOMIZER_FEED';
    const INVALID_FEED_NAME = 'INVALID_FEED_NAME';
    const TOO_MANY_FEED_ATTRIBUTES_FOR_FEED = 'TOO_MANY_FEED_ATTRIBUTES_FOR_FEED';
    const ATTRIBUTE_NAMES_NOT_UNIQUE = 'ATTRIBUTE_NAMES_NOT_UNIQUE';
    const FEED_DELETED = 'FEED_DELETED';
    const DUPLICATE_FEED_NAME = 'DUPLICATE_FEED_NAME';
    const UNKNOWN = 'UNKNOWN';


}
