<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdGroupCriterionErrorReason
{
    const AD_GROUP_CRITERION_LABEL_DOES_NOT_EXIST = 'AD_GROUP_CRITERION_LABEL_DOES_NOT_EXIST';
    const AD_GROUP_CRITERION_LABEL_ALREADY_EXISTS = 'AD_GROUP_CRITERION_LABEL_ALREADY_EXISTS';
    const CANNOT_ADD_LABEL_TO_NEGATIVE_CRITERION = 'CANNOT_ADD_LABEL_TO_NEGATIVE_CRITERION';
    const TOO_MANY_OPERATIONS = 'TOO_MANY_OPERATIONS';
    const CANT_UPDATE_NEGATIVE = 'CANT_UPDATE_NEGATIVE';
    const CONCRETE_TYPE_REQUIRED = 'CONCRETE_TYPE_REQUIRED';
    const BID_INCOMPATIBLE_WITH_ADGROUP = 'BID_INCOMPATIBLE_WITH_ADGROUP';
    const CANNOT_TARGET_AND_EXCLUDE = 'CANNOT_TARGET_AND_EXCLUDE';
    const ILLEGAL_URL = 'ILLEGAL_URL';
    const INVALID_KEYWORD_TEXT = 'INVALID_KEYWORD_TEXT';
    const INVALID_DESTINATION_URL = 'INVALID_DESTINATION_URL';
    const MISSING_DESTINATION_URL_TAG = 'MISSING_DESTINATION_URL_TAG';
    const KEYWORD_LEVEL_BID_NOT_SUPPORTED_FOR_MANUALCPM = 'KEYWORD_LEVEL_BID_NOT_SUPPORTED_FOR_MANUALCPM';
    const INVALID_USER_STATUS = 'INVALID_USER_STATUS';
    const CANNOT_ADD_CRITERIA_TYPE = 'CANNOT_ADD_CRITERIA_TYPE';
    const CANNOT_EXCLUDE_CRITERIA_TYPE = 'CANNOT_EXCLUDE_CRITERIA_TYPE';
    const INVALID_PRODUCT_PARTITION_HIERARCHY = 'INVALID_PRODUCT_PARTITION_HIERARCHY';
    const PRODUCT_PARTITION_UNIT_CANNOT_HAVE_CHILDREN = 'PRODUCT_PARTITION_UNIT_CANNOT_HAVE_CHILDREN';
    const PRODUCT_PARTITION_SUBDIVISION_REQUIRES_OTHERS_CASE = 'PRODUCT_PARTITION_SUBDIVISION_REQUIRES_OTHERS_CASE';
    const PRODUCT_PARTITION_REQUIRES_SAME_DIMENSION_TYPE_AS_SIBLINGS = 'PRODUCT_PARTITION_REQUIRES_SAME_DIMENSION_TYPE_AS_SIBLINGS';
    const PRODUCT_PARTITION_ALREADY_EXISTS = 'PRODUCT_PARTITION_ALREADY_EXISTS';
    const PRODUCT_PARTITION_DOES_NOT_EXIST = 'PRODUCT_PARTITION_DOES_NOT_EXIST';
    const PRODUCT_PARTITION_CANNOT_BE_REMOVED = 'PRODUCT_PARTITION_CANNOT_BE_REMOVED';
    const INVALID_PRODUCT_PARTITION_TYPE = 'INVALID_PRODUCT_PARTITION_TYPE';
    const PRODUCT_PARTITION_ADD_MAY_ONLY_USE_TEMP_ID = 'PRODUCT_PARTITION_ADD_MAY_ONLY_USE_TEMP_ID';
    const CAMPAIGN_TYPE_NOT_COMPATIBLE_WITH_PARTIAL_FAILURE = 'CAMPAIGN_TYPE_NOT_COMPATIBLE_WITH_PARTIAL_FAILURE';
    const OPERATIONS_FOR_TOO_MANY_SHOPPING_ADGROUPS = 'OPERATIONS_FOR_TOO_MANY_SHOPPING_ADGROUPS';
    const CANNOT_MODIFY_URL_FIELDS_WITH_DUPLICATE_ELEMENTS = 'CANNOT_MODIFY_URL_FIELDS_WITH_DUPLICATE_ELEMENTS';
    const CANNOT_SET_WITHOUT_FINAL_URLS = 'CANNOT_SET_WITHOUT_FINAL_URLS';
    const CANNOT_CLEAR_FINAL_URLS_IF_FINAL_MOBILE_URLS_EXIST = 'CANNOT_CLEAR_FINAL_URLS_IF_FINAL_MOBILE_URLS_EXIST';
    const CANNOT_CLEAR_FINAL_URLS_IF_FINAL_APP_URLS_EXIST = 'CANNOT_CLEAR_FINAL_URLS_IF_FINAL_APP_URLS_EXIST';
    const CANNOT_CLEAR_FINAL_URLS_IF_TRACKING_URL_TEMPLATE_EXISTS = 'CANNOT_CLEAR_FINAL_URLS_IF_TRACKING_URL_TEMPLATE_EXISTS';
    const CANNOT_CLEAR_FINAL_URLS_IF_URL_CUSTOM_PARAMETERS_EXIST = 'CANNOT_CLEAR_FINAL_URLS_IF_URL_CUSTOM_PARAMETERS_EXIST';
    const CANNOT_SET_BOTH_DESTINATION_URL_AND_FINAL_URLS = 'CANNOT_SET_BOTH_DESTINATION_URL_AND_FINAL_URLS';
    const CANNOT_SET_BOTH_DESTINATION_URL_AND_TRACKING_URL_TEMPLATE = 'CANNOT_SET_BOTH_DESTINATION_URL_AND_TRACKING_URL_TEMPLATE';
    const FINAL_URLS_NOT_SUPPORTED_FOR_CRITERION_TYPE = 'FINAL_URLS_NOT_SUPPORTED_FOR_CRITERION_TYPE';
    const FINAL_MOBILE_URLS_NOT_SUPPORTED_FOR_CRITERION_TYPE = 'FINAL_MOBILE_URLS_NOT_SUPPORTED_FOR_CRITERION_TYPE';
    const UNKNOWN = 'UNKNOWN';


}
