<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdType
{
    const DEPRECATED_AD = 'DEPRECATED_AD';
    const IMAGE_AD = 'IMAGE_AD';
    const PRODUCT_AD = 'PRODUCT_AD';
    const TEMPLATE_AD = 'TEMPLATE_AD';
    const TEXT_AD = 'TEXT_AD';
    const THIRD_PARTY_REDIRECT_AD = 'THIRD_PARTY_REDIRECT_AD';
    const DYNAMIC_SEARCH_AD = 'DYNAMIC_SEARCH_AD';
    const CALL_ONLY_AD = 'CALL_ONLY_AD';
    const EXPANDED_TEXT_AD = 'EXPANDED_TEXT_AD';
    const RESPONSIVE_DISPLAY_AD = 'RESPONSIVE_DISPLAY_AD';
    const SHOWCASE_AD = 'SHOWCASE_AD';
    const GOAL_OPTIMIZED_SHOPPING_AD = 'GOAL_OPTIMIZED_SHOPPING_AD';
    const EXPANDED_DYNAMIC_SEARCH_AD = 'EXPANDED_DYNAMIC_SEARCH_AD';
    const GMAIL_AD = 'GMAIL_AD';
    const RESPONSIVE_SEARCH_AD = 'RESPONSIVE_SEARCH_AD';
    const MULTI_ASSET_RESPONSIVE_DISPLAY_AD = 'MULTI_ASSET_RESPONSIVE_DISPLAY_AD';
    const UNKNOWN = 'UNKNOWN';


}
