<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AssetErrorReason
{
    const UNKNOWN = 'UNKNOWN';
    const ASSET_TYPE_NOT_SUPPORTED = 'ASSET_TYPE_NOT_SUPPORTED';
    const CANNOT_REMOVE_ASSET_WITH_REMOVED_STATUS = 'CANNOT_REMOVE_ASSET_WITH_REMOVED_STATUS';
    const CANNOT_MODIFY_ASSET_NAME = 'CANNOT_MODIFY_ASSET_NAME';
    const DUPLICATE_ASSET = 'DUPLICATE_ASSET';
    const DUPLICATE_ASSET_NAME = 'DUPLICATE_ASSET_NAME';
    const ASSET_DATA_IS_MISSING = 'ASSET_DATA_IS_MISSING';


}
