<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AuthenticationErrorReason
{
    const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
    const CLIENT_CUSTOMER_ID_IS_REQUIRED = 'CLIENT_CUSTOMER_ID_IS_REQUIRED';
    const CLIENT_EMAIL_REQUIRED = 'CLIENT_EMAIL_REQUIRED';
    const CLIENT_CUSTOMER_ID_INVALID = 'CLIENT_CUSTOMER_ID_INVALID';
    const CLIENT_EMAIL_INVALID = 'CLIENT_EMAIL_INVALID';
    const CLIENT_EMAIL_FAILED_TO_AUTHENTICATE = 'CLIENT_EMAIL_FAILED_TO_AUTHENTICATE';
    const CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND';
    const GOOGLE_ACCOUNT_DELETED = 'GOOGLE_ACCOUNT_DELETED';
    const GOOGLE_ACCOUNT_COOKIE_INVALID = 'GOOGLE_ACCOUNT_COOKIE_INVALID';
    const FAILED_TO_AUTHENTICATE_GOOGLE_ACCOUNT = 'FAILED_TO_AUTHENTICATE_GOOGLE_ACCOUNT';
    const GOOGLE_ACCOUNT_USER_AND_ADS_USER_MISMATCH = 'GOOGLE_ACCOUNT_USER_AND_ADS_USER_MISMATCH';
    const LOGIN_COOKIE_REQUIRED = 'LOGIN_COOKIE_REQUIRED';
    const NOT_ADS_USER = 'NOT_ADS_USER';
    const OAUTH_TOKEN_INVALID = 'OAUTH_TOKEN_INVALID';
    const OAUTH_TOKEN_EXPIRED = 'OAUTH_TOKEN_EXPIRED';
    const OAUTH_TOKEN_DISABLED = 'OAUTH_TOKEN_DISABLED';
    const OAUTH_TOKEN_REVOKED = 'OAUTH_TOKEN_REVOKED';
    const OAUTH_TOKEN_HEADER_INVALID = 'OAUTH_TOKEN_HEADER_INVALID';
    const LOGIN_COOKIE_INVALID = 'LOGIN_COOKIE_INVALID';
    const FAILED_TO_RETRIEVE_LOGIN_COOKIE = 'FAILED_TO_RETRIEVE_LOGIN_COOKIE';
    const USER_ID_INVALID = 'USER_ID_INVALID';


}
