<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AuthorizationErrorReason
{
    const UNABLE_TO_AUTHORIZE = 'UNABLE_TO_AUTHORIZE';
    const NO_ADWORDS_ACCOUNT_FOR_CUSTOMER = 'NO_ADWORDS_ACCOUNT_FOR_CUSTOMER';
    const USER_PERMISSION_DENIED = 'USER_PERMISSION_DENIED';
    const EFFECTIVE_USER_PERMISSION_DENIED = 'EFFECTIVE_USER_PERMISSION_DENIED';
    const CUSTOMER_NOT_ACTIVE = 'CUSTOMER_NOT_ACTIVE';
    const USER_HAS_READONLY_PERMISSION = 'USER_HAS_READONLY_PERMISSION';
    const NO_CUSTOMER_FOUND = 'NO_CUSTOMER_FOUND';
    const SERVICE_ACCESS_DENIED = 'SERVICE_ACCESS_DENIED';
    const TWO_STEP_VERIFICATION_NOT_ENROLLED = 'TWO_STEP_VERIFICATION_NOT_ENROLLED';
    const ADVANCED_PROTECTION_NOT_ENROLLED = 'ADVANCED_PROTECTION_NOT_ENROLLED';


}
