<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ConversionTrackingErrorReason
{
    const ALREADY_CREATED_CUSTOM_CONVERSION_TYPE = 'ALREADY_CREATED_CUSTOM_CONVERSION_TYPE';
    const ANALYTICS_NOT_ALLOWED = 'ANALYTICS_NOT_ALLOWED';
    const CANNOT_ADD_CONVERSION_TYPE_SUBCLASS = 'CANNOT_ADD_CONVERSION_TYPE_SUBCLASS';
    const CANNOT_ADD_EXTERNALLY_ATTRIBUTED_SALESFORCE_CONVERSION = 'CANNOT_ADD_EXTERNALLY_ATTRIBUTED_SALESFORCE_CONVERSION';
    const CANNOT_CHANGE_APP_CONVERSION_TYPE = 'CANNOT_CHANGE_APP_CONVERSION_TYPE';
    const CANNOT_CHANGE_APP_PLATFORM = 'CANNOT_CHANGE_APP_PLATFORM';
    const CANNNOT_CHANGE_CONVERSION_SUBCLASS = 'CANNNOT_CHANGE_CONVERSION_SUBCLASS';
    const CANNOT_SET_HIDDEN_STATUS = 'CANNOT_SET_HIDDEN_STATUS';
    const CATEGORY_IS_UNEDITABLE = 'CATEGORY_IS_UNEDITABLE';
    const ATTRIBUTION_MODEL_IS_UNEDITABLE = 'ATTRIBUTION_MODEL_IS_UNEDITABLE';
    const ATTRIBUTION_MODEL_CANNOT_BE_UNKNOWN = 'ATTRIBUTION_MODEL_CANNOT_BE_UNKNOWN';
    const DATA_DRIVEN_MODEL_WAS_NEVER_GENERATED = 'DATA_DRIVEN_MODEL_WAS_NEVER_GENERATED';
    const DATA_DRIVEN_MODEL_IS_EXPIRED = 'DATA_DRIVEN_MODEL_IS_EXPIRED';
    const DATA_DRIVEN_MODEL_IS_STALE = 'DATA_DRIVEN_MODEL_IS_STALE';
    const DATA_DRIVEN_MODEL_IS_UNKNOWN = 'DATA_DRIVEN_MODEL_IS_UNKNOWN';
    const CONVERSION_TYPE_NOT_FOUND = 'CONVERSION_TYPE_NOT_FOUND';
    const CTC_LOOKBACK_WINDOW_IS_UNEDITABLE = 'CTC_LOOKBACK_WINDOW_IS_UNEDITABLE';
    const DOMAIN_EXCEPTION = 'DOMAIN_EXCEPTION';
    const INCONSISTENT_COUNTING_TYPE = 'INCONSISTENT_COUNTING_TYPE';
    const DUPLICATE_APP_ID = 'DUPLICATE_APP_ID';
    const TWO_CONVERSION_TYPES_BIDDING_ON_SAME_APP_DOWNLOAD = 'TWO_CONVERSION_TYPES_BIDDING_ON_SAME_APP_DOWNLOAD';
    const CONVERSION_TYPE_BIDDING_ON_SAME_APP_DOWNLOAD_AS_GLOBAL_TYPE = 'CONVERSION_TYPE_BIDDING_ON_SAME_APP_DOWNLOAD_AS_GLOBAL_TYPE';
    const DUPLICATE_NAME = 'DUPLICATE_NAME';
    const EMAIL_FAILED = 'EMAIL_FAILED';
    const EXCEEDED_CONVERSION_TYPE_LIMIT = 'EXCEEDED_CONVERSION_TYPE_LIMIT';
    const ID_IS_NULL = 'ID_IS_NULL';
    const INVALID_APP_ID = 'INVALID_APP_ID';
    const CANNOT_SET_APP_ID = 'CANNOT_SET_APP_ID';
    const INVALID_CATEGORY = 'INVALID_CATEGORY';
    const INVALID_COLOR = 'INVALID_COLOR';
    const INVALID_DATE_RANGE = 'INVALID_DATE_RANGE';
    const INVALID_EMAIL_ADDRESS = 'INVALID_EMAIL_ADDRESS';
    const INVALID_ORIGINAL_CONVERSION_TYPE_ID = 'INVALID_ORIGINAL_CONVERSION_TYPE_ID';
    const MUST_SET_APP_PLATFORM_AND_APP_CONVERSION_TYPE_TOGETHER = 'MUST_SET_APP_PLATFORM_AND_APP_CONVERSION_TYPE_TOGETHER';
    const NAME_ALREADY_EXISTS = 'NAME_ALREADY_EXISTS';
    const NO_RECIPIENTS = 'NO_RECIPIENTS';
    const NO_SNIPPET = 'NO_SNIPPET';
    const TOO_MANY_WEBPAGES = 'TOO_MANY_WEBPAGES';
    const UNKNOWN_SORTING_TYPE = 'UNKNOWN_SORTING_TYPE';
    const UNSUPPORTED_APP_CONVERSION_TYPE = 'UNSUPPORTED_APP_CONVERSION_TYPE';


}
