<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CriterionType
{
    const CONTENT_LABEL = 'CONTENT_LABEL';
    const KEYWORD = 'KEYWORD';
    const PLACEMENT = 'PLACEMENT';
    const VERTICAL = 'VERTICAL';
    const USER_LIST = 'USER_LIST';
    const USER_INTEREST = 'USER_INTEREST';
    const MOBILE_APPLICATION = 'MOBILE_APPLICATION';
    const MOBILE_APP_CATEGORY = 'MOBILE_APP_CATEGORY';
    const PRODUCT_PARTITION = 'PRODUCT_PARTITION';
    const IP_BLOCK = 'IP_BLOCK';
    const WEBPAGE = 'WEBPAGE';
    const LANGUAGE = 'LANGUAGE';
    const LOCATION = 'LOCATION';
    const AGE_RANGE = 'AGE_RANGE';
    const CARRIER = 'CARRIER';
    const OPERATING_SYSTEM_VERSION = 'OPERATING_SYSTEM_VERSION';
    const MOBILE_DEVICE = 'MOBILE_DEVICE';
    const GENDER = 'GENDER';
    const PARENT_VALUE = 'PARENT';
    const PROXIMITY = 'PROXIMITY';
    const PLATFORM = 'PLATFORM';
    const PREFERRED_CONTENT = 'PREFERRED_CONTENT';
    const AD_SCHEDULE = 'AD_SCHEDULE';
    const LOCATION_GROUPS = 'LOCATION_GROUPS';
    const PRODUCT_SCOPE = 'PRODUCT_SCOPE';
    const CUSTOM_AFFINITY = 'CUSTOM_AFFINITY';
    const CUSTOM_INTENT = 'CUSTOM_INTENT';
    const YOUTUBE_VIDEO = 'YOUTUBE_VIDEO';
    const YOUTUBE_CHANNEL = 'YOUTUBE_CHANNEL';
    const APP_PAYMENT_MODEL = 'APP_PAYMENT_MODEL';
    const INCOME_RANGE = 'INCOME_RANGE';
    const INTERACTION_TYPE = 'INTERACTION_TYPE';
    const UNKNOWN = 'UNKNOWN';


}
