<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CustomerFeedErrorReason
{
    const FEED_ALREADY_EXISTS_FOR_PLACEHOLDER_TYPE = 'FEED_ALREADY_EXISTS_FOR_PLACEHOLDER_TYPE';
    const INVALID_ID = 'INVALID_ID';
    const CANNOT_ADD_FOR_DELETED_FEED = 'CANNOT_ADD_FOR_DELETED_FEED';
    const CANNOT_ADD_ALREADY_EXISTING_CUSTOMER_FEED = 'CANNOT_ADD_ALREADY_EXISTING_CUSTOMER_FEED';
    const CANNOT_MODIFY_REMOVED_CUSTOMER_FEED = 'CANNOT_MODIFY_REMOVED_CUSTOMER_FEED';
    const INVALID_PLACEHOLDER_TYPES = 'INVALID_PLACEHOLDER_TYPES';
    const MISSING_FEEDMAPPING_FOR_PLACEHOLDER_TYPE = 'MISSING_FEEDMAPPING_FOR_PLACEHOLDER_TYPE';
    const PLACEHOLDER_TYPE_NOT_ALLOWED_ON_CUSTOMER_FEED = 'PLACEHOLDER_TYPE_NOT_ALLOWED_ON_CUSTOMER_FEED';
    const UNKNOWN = 'UNKNOWN';


}
