<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class DateRangeErrorReason
{
    const DATE_RANGE_ERROR = 'DATE_RANGE_ERROR';
    const INVALID_DATE = 'INVALID_DATE';
    const START_DATE_AFTER_END_DATE = 'START_DATE_AFTER_END_DATE';
    const CANNOT_SET_DATE_TO_PAST = 'CANNOT_SET_DATE_TO_PAST';
    const AFTER_MAXIMUM_ALLOWABLE_DATE = 'AFTER_MAXIMUM_ALLOWABLE_DATE';
    const CANNOT_MODIFY_START_DATE_IF_ALREADY_STARTED = 'CANNOT_MODIFY_START_DATE_IF_ALREADY_STARTED';


}
