<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class DateErrorReason
{
    const INVALID_FIELD_VALUES_IN_DATE = 'INVALID_FIELD_VALUES_IN_DATE';
    const INVALID_FIELD_VALUES_IN_DATE_TIME = 'INVALID_FIELD_VALUES_IN_DATE_TIME';
    const INVALID_STRING_DATE = 'INVALID_STRING_DATE';
    const INVALID_STRING_DATE_RANGE = 'INVALID_STRING_DATE_RANGE';
    const INVALID_STRING_DATE_TIME = 'INVALID_STRING_DATE_TIME';
    const EARLIER_THAN_MINIMUM_DATE = 'EARLIER_THAN_MINIMUM_DATE';
    const LATER_THAN_MAXIMUM_DATE = 'LATER_THAN_MAXIMUM_DATE';
    const DATE_RANGE_MINIMUM_DATE_LATER_THAN_MAXIMUM_DATE = 'DATE_RANGE_MINIMUM_DATE_LATER_THAN_MAXIMUM_DATE';
    const DATE_RANGE_MINIMUM_AND_MAXIMUM_DATES_BOTH_NULL = 'DATE_RANGE_MINIMUM_AND_MAXIMUM_DATES_BOTH_NULL';


}
