<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class DraftErrorReason
{
    const CANNOT_CHANGE_ARCHIVED_DRAFT = 'CANNOT_CHANGE_ARCHIVED_DRAFT';
    const CANNOT_CHANGE_PROMOTED_DRAFT = 'CANNOT_CHANGE_PROMOTED_DRAFT';
    const CANNOT_CHANGE_PROMOTE_FAILED_DRAFT = 'CANNOT_CHANGE_PROMOTE_FAILED_DRAFT';
    const CUSTOMER_CANNOT_CREATE_DRAFT = 'CUSTOMER_CANNOT_CREATE_DRAFT';
    const CAMPAIGN_CANNOT_CREATE_DRAFT = 'CAMPAIGN_CANNOT_CREATE_DRAFT';
    const DUPLICATE_DRAFT_NAME = 'DUPLICATE_DRAFT_NAME';
    const INVALID_DRAFT_CHANGE = 'INVALID_DRAFT_CHANGE';
    const INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION';
    const MAX_NUMBER_OF_DRAFTS_PER_CAMPAIGN_REACHED = 'MAX_NUMBER_OF_DRAFTS_PER_CAMPAIGN_REACHED';
    const DRAFT_ERROR = 'DRAFT_ERROR';


}
