<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class FeedErrorReason
{
    const ATTRIBUTE_NAMES_NOT_UNIQUE = 'ATTRIBUTE_NAMES_NOT_UNIQUE';
    const ATTRIBUTES_DO_NOT_MATCH_EXISTING_ATTRIBUTES = 'ATTRIBUTES_DO_NOT_MATCH_EXISTING_ATTRIBUTES';
    const CANNOT_CHANGE_ORIGIN = 'CANNOT_CHANGE_ORIGIN';
    const CANNOT_SPECIFY_USER_ORIGIN_FOR_SYSTEM_FEED = 'CANNOT_SPECIFY_USER_ORIGIN_FOR_SYSTEM_FEED';
    const CANNOT_SPECIFY_ADWORDS_ORIGIN_FOR_NON_SYSTEM_FEED = 'CANNOT_SPECIFY_ADWORDS_ORIGIN_FOR_NON_SYSTEM_FEED';
    const CANNOT_SPECIFY_FEED_ATTRIBUTES_FOR_SYSTEM_FEED = 'CANNOT_SPECIFY_FEED_ATTRIBUTES_FOR_SYSTEM_FEED';
    const CANNOT_UPDATE_FEED_ATTRIBUTES_WITH_ORIGIN_ADWORDS = 'CANNOT_UPDATE_FEED_ATTRIBUTES_WITH_ORIGIN_ADWORDS';
    const FEED_REMOVED = 'FEED_REMOVED';
    const INVALID_ORIGIN_VALUE = 'INVALID_ORIGIN_VALUE';
    const FEED_ORIGIN_IS_NOT_USER = 'FEED_ORIGIN_IS_NOT_USER';
    const INVALID_AUTH_TOKEN_FOR_EMAIL = 'INVALID_AUTH_TOKEN_FOR_EMAIL';
    const INVALID_EMAIL = 'INVALID_EMAIL';
    const DUPLICATE_FEED_NAME = 'DUPLICATE_FEED_NAME';
    const INVALID_FEED_NAME = 'INVALID_FEED_NAME';
    const MISSING_OAUTH_INFO = 'MISSING_OAUTH_INFO';
    const NEW_ATTRIBUTE_CANNOT_BE_PART_OF_UNIQUE_KEY = 'NEW_ATTRIBUTE_CANNOT_BE_PART_OF_UNIQUE_KEY';
    const TOO_MANY_FEED_ATTRIBUTES_FOR_FEED = 'TOO_MANY_FEED_ATTRIBUTES_FOR_FEED';
    const INVALID_BUSINESS_ACCOUNT = 'INVALID_BUSINESS_ACCOUNT';
    const BUSINESS_ACCOUNT_CANNOT_ACCESS_LOCATION_ACCOUNT = 'BUSINESS_ACCOUNT_CANNOT_ACCESS_LOCATION_ACCOUNT';
    const INVALID_AFFILIATE_CHAIN_ID = 'INVALID_AFFILIATE_CHAIN_ID';
    const CANNOT_CHANGE_SYSTEM_FEED_GENERATION_DATA_TYPE = 'CANNOT_CHANGE_SYSTEM_FEED_GENERATION_DATA_TYPE';
    const UNSUPPORTED_AFFILIATE_LOCATION_RELATIONSHIP_TYPE = 'UNSUPPORTED_AFFILIATE_LOCATION_RELATIONSHIP_TYPE';
    const UNKNOWN = 'UNKNOWN';


}
