<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class OfflineCallConversionErrorReason
{
    const CONVERSION_PRECEDES_CALL = 'CONVERSION_PRECEDES_CALL';
    const FUTURE_CALL_START_TIME = 'FUTURE_CALL_START_TIME';
    const FUTURE_CONVERSION_TIME = 'FUTURE_CONVERSION_TIME';
    const EXPIRED_CALL = 'EXPIRED_CALL';
    const TOO_RECENT_CALL = 'TOO_RECENT_CALL';
    const UNPARSEABLE_CALLERS_PHONE_NUMBER = 'UNPARSEABLE_CALLERS_PHONE_NUMBER';
    const INVALID_CALL = 'INVALID_CALL';
    const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
    const INVALID_CONVERSION_TYPE = 'INVALID_CONVERSION_TYPE';
    const TOO_RECENT_CONVERSION_TYPE = 'TOO_RECENT_CONVERSION_TYPE';
    const CONVERSION_TRACKING_NOT_ENABLED_AT_CALL_TIME = 'CONVERSION_TRACKING_NOT_ENABLED_AT_CALL_TIME';
    const DESKTOP_CALL_NOT_SUPPORTED = 'DESKTOP_CALL_NOT_SUPPORTED';
    const INTERNAL_ERROR = 'INTERNAL_ERROR';
    const UNKNOWN = 'UNKNOWN';


}
