<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class OfflineConversionAdjustmentErrorReason
{
    const RETRACTION_WITH_VALUE_OR_CURRENCY = 'RETRACTION_WITH_VALUE_OR_CURRENCY';
    const RESTATEMENT_WITHOUT_VALUE = 'RESTATEMENT_WITHOUT_VALUE';
    const FUTURE_CONVERSION_TIME = 'FUTURE_CONVERSION_TIME';
    const FUTURE_ADJUSTMENT_TIME = 'FUTURE_ADJUSTMENT_TIME';
    const TOO_RECENT_CONVERSION_TYPE = 'TOO_RECENT_CONVERSION_TYPE';
    const INVALID_CONVERSION_TYPE = 'INVALID_CONVERSION_TYPE';
    const CONVERSION_ALREADY_CANCELED = 'CONVERSION_ALREADY_CANCELED';
    const CONVERSION_NOT_FOUND = 'CONVERSION_NOT_FOUND';
    const CONVERSION_EXPIRED = 'CONVERSION_EXPIRED';
    const ADJUSTMENT_PRECEDES_CONVERSION = 'ADJUSTMENT_PRECEDES_CONVERSION';
    const MORE_RECENT_RESTATEMENT_FOUND = 'MORE_RECENT_RESTATEMENT_FOUND';
    const ATTRIBUTED_CONVERSION_NOT_SUPPORTED = 'ATTRIBUTED_CONVERSION_NOT_SUPPORTED';
    const TOO_RECENT_CONVERSION = 'TOO_RECENT_CONVERSION';
    const INVALID_ORDER_ID = 'INVALID_ORDER_ID';
    const CANNOT_RESTATE_CONVERSION_ACTION_THAT_ALWAYS_USES_DEFAULT_CONVERSION_VALUE = 'CANNOT_RESTATE_CONVERSION_ACTION_THAT_ALWAYS_USES_DEFAULT_CONVERSION_VALUE';
    const UNKNOWN = 'UNKNOWN';


}
