<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class PolicyTopicConstraintPolicyTopicConstraintType
{
    const UNKNOWN = 'UNKNOWN';
    const COUNTRY = 'COUNTRY';
    const RESELLER = 'RESELLER';
    const CERTIFICATE_MISSING_IN_COUNTRY = 'CERTIFICATE_MISSING_IN_COUNTRY';
    const CERTIFICATE_DOMAIN_MISMATCH_IN_COUNTRY = 'CERTIFICATE_DOMAIN_MISMATCH_IN_COUNTRY';
    const CERTIFICATE_MISSING = 'CERTIFICATE_MISSING';
    const CERTIFICATE_DOMAIN_MISMATCH = 'CERTIFICATE_DOMAIN_MISMATCH';


}
