<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProductDimensionType
{
    const UNKNOWN = 'UNKNOWN';
    const BIDDING_CATEGORY_L1 = 'BIDDING_CATEGORY_L1';
    const BIDDING_CATEGORY_L2 = 'BIDDING_CATEGORY_L2';
    const BIDDING_CATEGORY_L3 = 'BIDDING_CATEGORY_L3';
    const BIDDING_CATEGORY_L4 = 'BIDDING_CATEGORY_L4';
    const BIDDING_CATEGORY_L5 = 'BIDDING_CATEGORY_L5';
    const BRAND = 'BRAND';
    const CANONICAL_CONDITION = 'CANONICAL_CONDITION';
    const CUSTOM_ATTRIBUTE_0 = 'CUSTOM_ATTRIBUTE_0';
    const CUSTOM_ATTRIBUTE_1 = 'CUSTOM_ATTRIBUTE_1';
    const CUSTOM_ATTRIBUTE_2 = 'CUSTOM_ATTRIBUTE_2';
    const CUSTOM_ATTRIBUTE_3 = 'CUSTOM_ATTRIBUTE_3';
    const CUSTOM_ATTRIBUTE_4 = 'CUSTOM_ATTRIBUTE_4';
    const OFFER_ID = 'OFFER_ID';
    const PRODUCT_TYPE_L1 = 'PRODUCT_TYPE_L1';
    const PRODUCT_TYPE_L2 = 'PRODUCT_TYPE_L2';
    const PRODUCT_TYPE_L3 = 'PRODUCT_TYPE_L3';
    const PRODUCT_TYPE_L4 = 'PRODUCT_TYPE_L4';
    const PRODUCT_TYPE_L5 = 'PRODUCT_TYPE_L5';
    const CHANNEL = 'CHANNEL';
    const CHANNEL_EXCLUSIVITY = 'CHANNEL_EXCLUSIVITY';


}
