<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class QuotaCheckErrorReason
{
    const INVALID_TOKEN_HEADER = 'INVALID_TOKEN_HEADER';
    const ACCOUNT_DELINQUENT = 'ACCOUNT_DELINQUENT';
    const ACCOUNT_INACCESSIBLE = 'ACCOUNT_INACCESSIBLE';
    const ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE';
    const INCOMPLETE_SIGNUP = 'INCOMPLETE_SIGNUP';
    const DEVELOPER_TOKEN_NOT_APPROVED = 'DEVELOPER_TOKEN_NOT_APPROVED';
    const TERMS_AND_CONDITIONS_NOT_SIGNED = 'TERMS_AND_CONDITIONS_NOT_SIGNED';
    const MONTHLY_BUDGET_REACHED = 'MONTHLY_BUDGET_REACHED';
    const QUOTA_EXCEEDED = 'QUOTA_EXCEEDED';


}
