<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ReportDefinitionErrorReason
{
    const INVALID_DATE_RANGE_FOR_REPORT = 'INVALID_DATE_RANGE_FOR_REPORT';
    const INVALID_FIELD_NAME_FOR_REPORT = 'INVALID_FIELD_NAME_FOR_REPORT';
    const UNABLE_TO_FIND_MAPPING_FOR_THIS_REPORT = 'UNABLE_TO_FIND_MAPPING_FOR_THIS_REPORT';
    const INVALID_COLUMN_NAME_FOR_REPORT = 'INVALID_COLUMN_NAME_FOR_REPORT';
    const INVALID_REPORT_DEFINITION_ID = 'INVALID_REPORT_DEFINITION_ID';
    const REPORT_SELECTOR_CANNOT_BE_NULL = 'REPORT_SELECTOR_CANNOT_BE_NULL';
    const NO_ENUMS_FOR_THIS_COLUMN_NAME = 'NO_ENUMS_FOR_THIS_COLUMN_NAME';
    const INVALID_VIEW = 'INVALID_VIEW';
    const SORTING_NOT_SUPPORTED = 'SORTING_NOT_SUPPORTED';
    const PAGING_NOT_SUPPORTED = 'PAGING_NOT_SUPPORTED';
    const CUSTOMER_SERVING_TYPE_REPORT_MISMATCH = 'CUSTOMER_SERVING_TYPE_REPORT_MISMATCH';
    const CLIENT_SELECTOR_NO_CUSTOMER_IDENTIFIER = 'CLIENT_SELECTOR_NO_CUSTOMER_IDENTIFIER';
    const CLIENT_SELECTOR_INVALID_CUSTOMER_ID = 'CLIENT_SELECTOR_INVALID_CUSTOMER_ID';
    const REPORT_DEFINITION_ERROR = 'REPORT_DEFINITION_ERROR';


}
