<?php

namespace Google\AdsApi\AdWords\v201806\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class UniversalAppBiddingStrategyGoalType
{
    const UNKNOWN = 'UNKNOWN';
    const OPTIMIZE_FOR_INSTALL_CONVERSION_VOLUME = 'OPTIMIZE_FOR_INSTALL_CONVERSION_VOLUME';
    const OPTIMIZE_FOR_IN_APP_CONVERSION_VOLUME = 'OPTIMIZE_FOR_IN_APP_CONVERSION_VOLUME';
    const OPTIMIZE_FOR_TOTAL_CONVERSION_VALUE = 'OPTIMIZE_FOR_TOTAL_CONVERSION_VALUE';
    const OPTIMIZE_FOR_TARGET_IN_APP_CONVERSION = 'OPTIMIZE_FOR_TARGET_IN_APP_CONVERSION';
    const OPTIMIZE_FOR_RETURN_ON_ADVERTISING_SPEND = 'OPTIMIZE_FOR_RETURN_ON_ADVERTISING_SPEND';


}
