<?php

namespace Google\AdsApi\AdWords\v201710\rm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class UserListErrorReason
{
    const EXTERNAL_REMARKETING_USER_LIST_MUTATE_NOT_SUPPORTED = 'EXTERNAL_REMARKETING_USER_LIST_MUTATE_NOT_SUPPORTED';
    const CONCRETE_TYPE_REQUIRED = 'CONCRETE_TYPE_REQUIRED';
    const CONVERSION_TYPE_ID_REQUIRED = 'CONVERSION_TYPE_ID_REQUIRED';
    const DUPLICATE_CONVERSION_TYPES = 'DUPLICATE_CONVERSION_TYPES';
    const INVALID_CONVERSION_TYPE = 'INVALID_CONVERSION_TYPE';
    const INVALID_DESCRIPTION = 'INVALID_DESCRIPTION';
    const INVALID_NAME = 'INVALID_NAME';
    const INVALID_TYPE = 'INVALID_TYPE';
    const CAN_NOT_ADD_SIMILAR_LIST_AS_LOGICAL_LIST_NONE_OPERAND = 'CAN_NOT_ADD_SIMILAR_LIST_AS_LOGICAL_LIST_NONE_OPERAND';
    const CAN_NOT_ADD_LOGICAL_LIST_AS_LOGICAL_LIST_OPERAND = 'CAN_NOT_ADD_LOGICAL_LIST_AS_LOGICAL_LIST_OPERAND';
    const INVALID_USER_LIST_LOGICAL_RULE_OPERAND = 'INVALID_USER_LIST_LOGICAL_RULE_OPERAND';
    const NAME_ALREADY_USED = 'NAME_ALREADY_USED';
    const NEW_CONVERSION_TYPE_NAME_REQUIRED = 'NEW_CONVERSION_TYPE_NAME_REQUIRED';
    const CONVERSION_TYPE_NAME_ALREADY_USED = 'CONVERSION_TYPE_NAME_ALREADY_USED';
    const OWNERSHIP_REQUIRED_FOR_SET = 'OWNERSHIP_REQUIRED_FOR_SET';
    const REMOVE_NOT_SUPPORTED = 'REMOVE_NOT_SUPPORTED';
    const USER_LIST_MUTATE_NOT_SUPPORTED = 'USER_LIST_MUTATE_NOT_SUPPORTED';
    const INVALID_RULE = 'INVALID_RULE';
    const INVALID_DATE_RANGE = 'INVALID_DATE_RANGE';
    const CAN_NOT_MUTATE_SENSITIVE_USERLIST = 'CAN_NOT_MUTATE_SENSITIVE_USERLIST';
    const MAX_NUM_RULEBASED_USERLISTS = 'MAX_NUM_RULEBASED_USERLISTS';
    const CANNOT_MODIFY_BILLABLE_RECORD_COUNT = 'CANNOT_MODIFY_BILLABLE_RECORD_COUNT';
    const USER_LIST_SERVICE_ERROR = 'USER_LIST_SERVICE_ERROR';


}
