<?php

namespace Google\AdsApi\AdManager\v202111;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ForecastAdjustmentErrorReason
{
    const AD_REQUEST_SOURCE_PLATFORMS_MUST_MATCH_SEGMENT_PLATFORMS = 'AD_REQUEST_SOURCE_PLATFORMS_MUST_MATCH_SEGMENT_PLATFORMS';
    const AD_REQUEST_HISTORICAL_BASIS_DATE_RANGE_TOO_SHORT_RELATIVE_TO_ADJUSTMENT = 'AD_REQUEST_HISTORICAL_BASIS_DATE_RANGE_TOO_SHORT_RELATIVE_TO_ADJUSTMENT';
    const ADJUSTED_VALUE_ABOVE_RECOMMENDED_RELATIVE_LIMIT = 'ADJUSTED_VALUE_ABOVE_RECOMMENDED_RELATIVE_LIMIT';
    const ADJUSTED_VALUE_TOO_HIGH_RELATIVE_TO_FORECAST = 'ADJUSTED_VALUE_TOO_HIGH_RELATIVE_TO_FORECAST';
    const ADJUSTED_VALUE_TOO_LOW = 'ADJUSTED_VALUE_TOO_LOW';
    const ADJUSTED_VALUE_TOO_LOW_RELATIVE_TO_FORECAST = 'ADJUSTED_VALUE_TOO_LOW_RELATIVE_TO_FORECAST';
    const ADJUSTS_CROSS_SELL_INVENTORY = 'ADJUSTS_CROSS_SELL_INVENTORY';
    const DATE_RANGE_OVERLAPS_ANOTHER_ADJUSTMENT = 'DATE_RANGE_OVERLAPS_ANOTHER_ADJUSTMENT';
    const END_DATE_AFTER_FURTHEST_AVAILABLE_FORECAST_DATE = 'END_DATE_AFTER_FURTHEST_AVAILABLE_FORECAST_DATE';
    const END_DATE_NOT_ON_OR_AFTER_START_DATE = 'END_DATE_NOT_ON_OR_AFTER_START_DATE';
    const HISTORICAL_BASIS_DATE_RANGE_TOO_SHORT = 'HISTORICAL_BASIS_DATE_RANGE_TOO_SHORT';
    const HISTORICAL_END_DATE_NOT_IN_PAST = 'HISTORICAL_END_DATE_NOT_IN_PAST';
    const HISTORICAL_START_DATE_TOO_FAR_BEFORE_ADJUSTMENT_END_DATE = 'HISTORICAL_START_DATE_TOO_FAR_BEFORE_ADJUSTMENT_END_DATE';
    const NO_VOLUME_SETTINGS_PROVIDED = 'NO_VOLUME_SETTINGS_PROVIDED';
    const NUMBER_OF_VALUES_DOES_NOT_MATCH_DATE_RANGE = 'NUMBER_OF_VALUES_DOES_NOT_MATCH_DATE_RANGE';
    const PARENT_SEGMENT_TARGETING_INCOMPATIBLE_WITH_HISTORICAL_BASIS_AD_REQUEST_SOURCE_SETTINGS = 'PARENT_SEGMENT_TARGETING_INCOMPATIBLE_WITH_HISTORICAL_BASIS_AD_REQUEST_SOURCE_SETTINGS';
    const UNKNOWN = 'UNKNOWN';


}
