<?php

namespace Google\AdsApi\AdManager\v202411;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class LiveStreamEventSlateErrorReason
{
    const INVALID_SLATE_CREATIVE_ID = 'INVALID_SLATE_CREATIVE_ID';
    const LIVE_STREAM_EVENT_SLATE_CREATIVE_ID_REQUIRED = 'LIVE_STREAM_EVENT_SLATE_CREATIVE_ID_REQUIRED';
    const MISSING_SOURCE_FOR_SLATE = 'MISSING_SOURCE_FOR_SLATE';
    const INVALID_SLATE_TYPE = 'INVALID_SLATE_TYPE';
    const CANNOT_CHANGE_SLATE_VIDEO_SOURCE_URL = 'CANNOT_CHANGE_SLATE_VIDEO_SOURCE_URL';
    const UNKNOWN = 'UNKNOWN';


}
