<?php

namespace Google\AdsApi\AdManager\v202402;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ForecastErrorReason
{
    const SERVER_NOT_AVAILABLE = 'SERVER_NOT_AVAILABLE';
    const INTERNAL_ERROR = 'INTERNAL_ERROR';
    const NO_FORECAST_YET = 'NO_FORECAST_YET';
    const NOT_ENOUGH_INVENTORY = 'NOT_ENOUGH_INVENTORY';
    const SUCCESS = 'SUCCESS';
    const ZERO_LENGTH_RESERVATION = 'ZERO_LENGTH_RESERVATION';
    const EXCEEDED_QUOTA = 'EXCEEDED_QUOTA';
    const OUTSIDE_AVAILABLE_DATE_RANGE = 'OUTSIDE_AVAILABLE_DATE_RANGE';
    const UNKNOWN = 'UNKNOWN';


}
