<?php

namespace Google\AdsApi\AdWords\v201601\express;

class PromotionErrorReason
{
    const __default = 'MISSING_BUSINESS_NAME';
    const MISSING_BUSINESS_NAME = 'MISSING_BUSINESS_NAME';
    const BUSINESS_DELETED = 'BUSINESS_DELETED';
    const NOT_BUSINESS_OWNER = 'NOT_BUSINESS_OWNER';
    const BUSINESS_OWNER_NOT_FOUND = 'BUSINESS_OWNER_NOT_FOUND';
    const BUSINESS_OWNER_ACCOUNT_NOT_MATCHED = 'BUSINESS_OWNER_ACCOUNT_NOT_MATCHED';
    const BUSINESS_PROMOTED_BY_ANOTHER_ACCOUNT = 'BUSINESS_PROMOTED_BY_ANOTHER_ACCOUNT';
    const BUSINESS_COUNTRY_NOT_SUPPORTED = 'BUSINESS_COUNTRY_NOT_SUPPORTED';
    const BUSINESS_LANGUAGE_NOT_SUPPORTED = 'BUSINESS_LANGUAGE_NOT_SUPPORTED';
    const CURRENCY_NOT_SUPPORTED = 'CURRENCY_NOT_SUPPORTED';
    const AOL_ACCOUNT = 'AOL_ACCOUNT';
    const MANAGER_ACCOUNT = 'MANAGER_ACCOUNT';
    const INVALID_DESTINATION_URL = 'INVALID_DESTINATION_URL';
    const CALL_TRACKING_NOT_SUPPORTED = 'CALL_TRACKING_NOT_SUPPORTED';
    const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';
    const PREMIUM_RATE_PHONE_NUMBER_NOT_ALLOWED = 'PREMIUM_RATE_PHONE_NUMBER_NOT_ALLOWED';
    const NON_LOCAL_BUSINESS = 'NON_LOCAL_BUSINESS';
    const ALREADY_MIGRATED = 'ALREADY_MIGRATED';
    const UNKNOWN = 'UNKNOWN';


}
