<?php

namespace Google\AdsApi\AdManager\v202205;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class InventoryClientApiErrorReason
{
    const ACCESS_DENIED = 'ACCESS_DENIED';
    const ADSENSE_AUTH_ERROR = 'ADSENSE_AUTH_ERROR';
    const ADSENSE_RPC_ERROR = 'ADSENSE_RPC_ERROR';
    const DOMAIN_NO_SCHEME = 'DOMAIN_NO_SCHEME';
    const DOMAIN_INVALID_HOST = 'DOMAIN_INVALID_HOST';
    const DOMAIN_INVALID_TLD = 'DOMAIN_INVALID_TLD';
    const DOMAIN_ONE_STRING_AND_PUBLIC_SUFFIX = 'DOMAIN_ONE_STRING_AND_PUBLIC_SUFFIX';
    const DOMAIN_INVALID_INPUT = 'DOMAIN_INVALID_INPUT';
    const DOMAIN_NO_PUBLIC_SUFFIX = 'DOMAIN_NO_PUBLIC_SUFFIX';
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';


}
