<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdRuleSlotErrorReason
{
    const DIFFERENT_STATUS_THAN_AD_RULE = 'DIFFERENT_STATUS_THAN_AD_RULE';
    const INVALID_VIDEO_AD_DURATION_RANGE = 'INVALID_VIDEO_AD_DURATION_RANGE';
    const INVALID_VIDEO_MIDROLL_FREQUENCY_TYPE = 'INVALID_VIDEO_MIDROLL_FREQUENCY_TYPE';
    const MALFORMED_VIDEO_MIDROLL_FREQUENCY_CSV = 'MALFORMED_VIDEO_MIDROLL_FREQUENCY_CSV';
    const MALFORMED_VIDEO_MIDROLL_FREQUENCY_SINGLE_NUMBER = 'MALFORMED_VIDEO_MIDROLL_FREQUENCY_SINGLE_NUMBER';
    const INVALID_OVERLAY_AD_DURATION_RANGE = 'INVALID_OVERLAY_AD_DURATION_RANGE';
    const INVALID_OVERLAY_MIDROLL_FREQUENCY_TYPE = 'INVALID_OVERLAY_MIDROLL_FREQUENCY_TYPE';
    const MALFORMED_OVERLAY_MIDROLL_FREQUENCY_CSV = 'MALFORMED_OVERLAY_MIDROLL_FREQUENCY_CSV';
    const MALFORMED_OVERLAY_MIDROLL_FREQUENCY_SINGLE_NUMBER = 'MALFORMED_OVERLAY_MIDROLL_FREQUENCY_SINGLE_NUMBER';
    const INVALID_BUMPER_MAX_DURATION = 'INVALID_BUMPER_MAX_DURATION';
    const UNKNOWN = 'UNKNOWN';


}
