<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class BillingErrorReason
{
    const UNSUPPORTED_BILLING_SCHEDULE = 'UNSUPPORTED_BILLING_SCHEDULE';
    const UNSUPPORTED_BILLING_CAP = 'UNSUPPORTED_BILLING_CAP';
    const MISSING_BILLING_SOURCE = 'MISSING_BILLING_SOURCE';
    const MISSING_BILLING_SCHEDULE = 'MISSING_BILLING_SCHEDULE';
    const MISSING_BILLING_CAP = 'MISSING_BILLING_CAP';
    const INVALID_BILLING_SOURCE_FOR_OFFLINE = 'INVALID_BILLING_SOURCE_FOR_OFFLINE';
    const UPDATE_BILLING_NOT_ALLOWED = 'UPDATE_BILLING_NOT_ALLOWED';
    const MISSING_BILLING_BASE = 'MISSING_BILLING_BASE';
    const INVALID_BILLING_BASE = 'INVALID_BILLING_BASE';
    const UNKNOWN = 'UNKNOWN';


}
