<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CdnConfigurationErrorReason
{
    const URL_SHOULD_NOT_CONTAIN_SCHEME = 'URL_SHOULD_NOT_CONTAIN_SCHEME';
    const INVALID_DELIVERY_LOCATION_NAMES = 'INVALID_DELIVERY_LOCATION_NAMES';
    const CANNOT_ARCHIVE_IF_USED_BY_ACTIVE_CONTENT_SOURCES = 'CANNOT_ARCHIVE_IF_USED_BY_ACTIVE_CONTENT_SOURCES';
    const CANNOT_ARCHIVE_IF_USED_BY_ACTIVE_LIVE_STREAMS = 'CANNOT_ARCHIVE_IF_USED_BY_ACTIVE_LIVE_STREAMS';
    const UNKNOWN = 'UNKNOWN';


}
