<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class DaiAuthenticationKeyActionErrorReason
{
    const INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION';
    const CANNOT_DEACTIVATE_IF_USED_BY_ACTIVE_CONTENT_SOURCES = 'CANNOT_DEACTIVATE_IF_USED_BY_ACTIVE_CONTENT_SOURCES';
    const CANNOT_DEACTIVATE_IF_USED_BY_ACTIVE_LIVE_STREAMS = 'CANNOT_DEACTIVATE_IF_USED_BY_ACTIVE_LIVE_STREAMS';
    const UNKNOWN = 'UNKNOWN';


}
