<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class DealErrorReason
{
    const CANNOT_ADD_LINE_ITEM_WHEN_SOLD = 'CANNOT_ADD_LINE_ITEM_WHEN_SOLD';
    const CANNOT_ARCHIVE_LINE_ITEM_WHEN_SOLD = 'CANNOT_ARCHIVE_LINE_ITEM_WHEN_SOLD';
    const CANNOT_ARCHIVE_PROPOSAL_WHEN_SOLD = 'CANNOT_ARCHIVE_PROPOSAL_WHEN_SOLD';
    const CANNOT_CHANGE_FIELD_REQUIRING_BUYER_APPROVAL = 'CANNOT_CHANGE_FIELD_REQUIRING_BUYER_APPROVAL';
    const CANNOT_GET_SELLER_ID = 'CANNOT_GET_SELLER_ID';
    const CAN_ONLY_EXECUTE_IF_LOCAL_EDITS = 'CAN_ONLY_EXECUTE_IF_LOCAL_EDITS';
    const MISSING_PROPOSAL_LINE_ITEMS = 'MISSING_PROPOSAL_LINE_ITEMS';
    const MISSING_ENVIRONMENT = 'MISSING_ENVIRONMENT';
    const MISSING_AD_EXCHANGE_PROPERTY = 'MISSING_AD_EXCHANGE_PROPERTY';
    const CANNOT_FIND_PROPOSAL_IN_MARKETPLACE = 'CANNOT_FIND_PROPOSAL_IN_MARKETPLACE';
    const CANNOT_GET_PRODUCT = 'CANNOT_GET_PRODUCT';
    const NEW_VERSION_FROM_BUYER = 'NEW_VERSION_FROM_BUYER';
    const PROPOSAL_OUT_OF_SYNC_WITH_MARKETPLACE = 'PROPOSAL_OUT_OF_SYNC_WITH_MARKETPLACE';
    const NO_PROPOSAL_CHANGES_FOUND = 'NO_PROPOSAL_CHANGES_FOUND';
    const UNKNOWN = 'UNKNOWN';


}
