<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class LineItemOperationErrorReason
{
    const NOT_ALLOWED = 'NOT_ALLOWED';
    const NOT_APPLICABLE = 'NOT_APPLICABLE';
    const HAS_COMPLETED = 'HAS_COMPLETED';
    const HAS_NO_ACTIVE_CREATIVES = 'HAS_NO_ACTIVE_CREATIVES';
    const CANNOT_ACTIVATE_LEGACY_DFP_LINE_ITEM = 'CANNOT_ACTIVATE_LEGACY_DFP_LINE_ITEM';
    const CANNOT_ACTIVATE_UNCONFIGURED_LINE_ITEM = 'CANNOT_ACTIVATE_UNCONFIGURED_LINE_ITEM';
    const CANNOT_DELETE_DELIVERED_LINE_ITEM = 'CANNOT_DELETE_DELIVERED_LINE_ITEM';
    const CANNOT_RESERVE_COMPANY_CREDIT_STATUS_NOT_ACTIVE = 'CANNOT_RESERVE_COMPANY_CREDIT_STATUS_NOT_ACTIVE';
    const CANNOT_ACTIVATE_INVALID_COMPANY_CREDIT_STATUS = 'CANNOT_ACTIVATE_INVALID_COMPANY_CREDIT_STATUS';
    const UNKNOWN = 'UNKNOWN';


}
