<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProductErrorReason
{
    const TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND';
    const MALFORMED_PRODUCT_ID = 'MALFORMED_PRODUCT_ID';
    const BAD_PRODUCT_ID_FEATURE = 'BAD_PRODUCT_ID_FEATURE';
    const BAD_PRODUCT_TEMPLATE_ID = 'BAD_PRODUCT_TEMPLATE_ID';
    const CANNOT_UPDATE_ARCHIVED_PRODUCT = 'CANNOT_UPDATE_ARCHIVED_PRODUCT';
    const QUERY_TOO_LARGE = 'QUERY_TOO_LARGE';
    const PRODUCT_TEMPLATE_ID_IS_NOT_ZERO = 'PRODUCT_TEMPLATE_ID_IS_NOT_ZERO';
    const INVALID_RATE = 'INVALID_RATE';
    const INVALID_CURRENCY = 'INVALID_CURRENCY';
    const UNKNOWN = 'UNKNOWN';


}
