<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProposalLineItemProgrammaticErrorReason
{
    const INVALID_PRODUCT_TYPE = 'INVALID_PRODUCT_TYPE';
    const VIDEO_NOT_SUPPORTED = 'VIDEO_NOT_SUPPORTED';
    const ROADBLOCKING_NOT_SUPPORTED = 'ROADBLOCKING_NOT_SUPPORTED';
    const INVALID_CREATIVE_ROTATION = 'INVALID_CREATIVE_ROTATION';
    const INVALID_PROPOSAL_LINE_ITEM_TYPE = 'INVALID_PROPOSAL_LINE_ITEM_TYPE';
    const INVALID_RATE_TYPE = 'INVALID_RATE_TYPE';
    const ZERO_COST_PER_UNIT_NOT_SUPPORTED = 'ZERO_COST_PER_UNIT_NOT_SUPPORTED';
    const INVALID_PROGRAMMATIC_CREATIVE_SOURCE = 'INVALID_PROGRAMMATIC_CREATIVE_SOURCE';
    const CANNOT_UPDATE_PROGRAMMATIC_CREATIVE_SOURCE = 'CANNOT_UPDATE_PROGRAMMATIC_CREATIVE_SOURCE';
    const INVALID_NUM_UNITS = 'INVALID_NUM_UNITS';
    const MIX_GUARANTEED_AND_PREFERRED_DEAL_NOT_ALLOWED = 'MIX_GUARANTEED_AND_PREFERRED_DEAL_NOT_ALLOWED';
    const MIX_NATIVE_AND_BANNER_SIZE_NOT_ALLOWED = 'MIX_NATIVE_AND_BANNER_SIZE_NOT_ALLOWED';
    const CANNOT_UPDATE_SIZES = 'CANNOT_UPDATE_SIZES';
    const INVALID_SPONSORSHIP_CONTRACTED_UNITS_BOUGHT = 'INVALID_SPONSORSHIP_CONTRACTED_UNITS_BOUGHT';
    const INVALID_PROGRAMMATIC_PRICING_MODEL = 'INVALID_PROGRAMMATIC_PRICING_MODEL';
    const UNKNOWN = 'UNKNOWN';


}
