<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProposalErrorReason
{
    const AD_SERVER_UNKNOWN_ERROR = 'AD_SERVER_UNKNOWN_ERROR';
    const AD_SERVER_API_ERROR = 'AD_SERVER_API_ERROR';
    const UPDATE_ADVERTISER_NOT_ALLOWED = 'UPDATE_ADVERTISER_NOT_ALLOWED';
    const UPDATE_PROPOSAL_NOT_ALLOWED = 'UPDATE_PROPOSAL_NOT_ALLOWED';
    const CONTACT_UNSUPPORTED_FOR_ADVERTISER = 'CONTACT_UNSUPPORTED_FOR_ADVERTISER';
    const INVALID_CONTACT = 'INVALID_CONTACT';
    const DUPLICATED_CONTACT = 'DUPLICATED_CONTACT';
    const UNACCEPTABLE_COMPANY_CREDIT_STATUS = 'UNACCEPTABLE_COMPANY_CREDIT_STATUS';
    const COMPANY_CREDIT_STATUS_NOT_ACTIVE = 'COMPANY_CREDIT_STATUS_NOT_ACTIVE';
    const PRIMARY_AGENCY_REQUIRED = 'PRIMARY_AGENCY_REQUIRED';
    const PRIMARY_AGENCY_NOT_UNIQUE = 'PRIMARY_AGENCY_NOT_UNIQUE';
    const UNSUPPORTED_COMPANY_ASSOCIATION_TYPE_FOR_PROGRAMMATIC_PROPOSAL = 'UNSUPPORTED_COMPANY_ASSOCIATION_TYPE_FOR_PROGRAMMATIC_PROPOSAL';
    const DUPLICATED_COMPANY_ASSOCIATION = 'DUPLICATED_COMPANY_ASSOCIATION';
    const DUPLICATED_SALESPERSON = 'DUPLICATED_SALESPERSON';
    const DUPLICATED_SALES_PLANNER = 'DUPLICATED_SALES_PLANNER';
    const DUPLICATED_TRAFFICKER = 'DUPLICATED_TRAFFICKER';
    const HAS_NO_UNARCHIVED_PROPOSAL_LINEITEMS = 'HAS_NO_UNARCHIVED_PROPOSAL_LINEITEMS';
    const DUPLICATE_TERMS_AND_CONDITIONS = 'DUPLICATE_TERMS_AND_CONDITIONS';
    const UNSUPPORTED_PROPOSAL_CURRENCY_CODE = 'UNSUPPORTED_PROPOSAL_CURRENCY_CODE';
    const INVALID_FIELDS_SET_FOR_NON_PROGRAMMATIC_PROPOSAL = 'INVALID_FIELDS_SET_FOR_NON_PROGRAMMATIC_PROPOSAL';
    const INVALID_POC = 'INVALID_POC';
    const UPDATE_CURRENCY_NOT_ALLOWED = 'UPDATE_CURRENCY_NOT_ALLOWED';
    const UPDATE_TIME_ZONE_NOT_ALLOWED = 'UPDATE_TIME_ZONE_NOT_ALLOWED';
    const NON_PROGRAMMATIC_PROPOSAL_NOT_ALLOWED = 'NON_PROGRAMMATIC_PROPOSAL_NOT_ALLOWED';
    const UNKNOWN = 'UNKNOWN';


}
