<?php

namespace Google\AdsApi\AdManager\v201805;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class SetTopBoxLineItemErrorReason
{
    const NON_SET_TOP_BOX_AD_UNIT_TARGETED = 'NON_SET_TOP_BOX_AD_UNIT_TARGETED';
    const AT_LEAST_ONE_AD_UNIT_MUST_BE_TARGETED = 'AT_LEAST_ONE_AD_UNIT_MUST_BE_TARGETED';
    const CANNOT_EXCLUDE_AD_UNITS = 'CANNOT_EXCLUDE_AD_UNITS';
    const POD_POSITION_OUT_OF_RANGE = 'POD_POSITION_OUT_OF_RANGE';
    const MIDROLL_POSITION_OUT_OF_RANGE = 'MIDROLL_POSITION_OUT_OF_RANGE';
    const FEATURE_NOT_ENABLED = 'FEATURE_NOT_ENABLED';
    const INVALID_ENVIRONMENT_TYPE = 'INVALID_ENVIRONMENT_TYPE';
    const COMPANIONS_NOT_SUPPORTED = 'COMPANIONS_NOT_SUPPORTED';
    const INVALID_CREATIVE_SIZE = 'INVALID_CREATIVE_SIZE';
    const INVALID_LINE_ITEM_TYPE = 'INVALID_LINE_ITEM_TYPE';
    const ORDERS_WITH_STANDARD_LINE_ITEMS_CANNOT_CONTAIN_HOUSE_OR_SPONSORSHIP_LINE_ITEMS = 'ORDERS_WITH_STANDARD_LINE_ITEMS_CANNOT_CONTAIN_HOUSE_OR_SPONSORSHIP_LINE_ITEMS';
    const INVALID_COST_TYPE = 'INVALID_COST_TYPE';
    const COST_PER_UNIT_NOT_ALLOWED = 'COST_PER_UNIT_NOT_ALLOWED';
    const DISCOUNT_NOT_ALLOWED = 'DISCOUNT_NOT_ALLOWED';
    const FRONTLOADED_DELIVERY_RATE_NOT_SUPPORTED = 'FRONTLOADED_DELIVERY_RATE_NOT_SUPPORTED';
    const INVALID_LINE_ITEM_STATUS_CHANGE = 'INVALID_LINE_ITEM_STATUS_CHANGE';
    const INVALID_LINE_ITEM_PRIORITY = 'INVALID_LINE_ITEM_PRIORITY';
    const SYNC_REVISION_NOT_INCREASING = 'SYNC_REVISION_NOT_INCREASING';
    const SYNC_REVISION_MUST_BE_GREATER_THAN_ZERO = 'SYNC_REVISION_MUST_BE_GREATER_THAN_ZERO';
    const CANNOT_UNARCHIVE_SET_TOP_BOX_LINE_ITEMS = 'CANNOT_UNARCHIVE_SET_TOP_BOX_LINE_ITEMS';
    const COPY_SET_TOP_BOX_ENABLED_LINE_ITEM_NOT_ALLOWED = 'COPY_SET_TOP_BOX_ENABLED_LINE_ITEM_NOT_ALLOWED';
    const INVALID_LINE_ITEM_TYPE_CHANGE = 'INVALID_LINE_ITEM_TYPE_CHANGE';
    const CREATIVE_ROTATION_TYPE_MUST_BE_EVENLY_OR_WEIGHTED = 'CREATIVE_ROTATION_TYPE_MUST_BE_EVENLY_OR_WEIGHTED';
    const INVALID_FREQUENCY_CAP_TIME_UNIT = 'INVALID_FREQUENCY_CAP_TIME_UNIT';
    const INVALID_FREQUENCY_CAP_TIME_RANGE = 'INVALID_FREQUENCY_CAP_TIME_RANGE';
    const INVALID_PRIMARY_GOAL_UNIT_TYPE = 'INVALID_PRIMARY_GOAL_UNIT_TYPE';
    const UNKNOWN = 'UNKNOWN';


}
