<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdSenseAccountErrorReason
{
    const ASSOCIATE_ACCOUNT_API_ERROR = 'ASSOCIATE_ACCOUNT_API_ERROR';
    const GET_AD_SLOT_API_ERROR = 'GET_AD_SLOT_API_ERROR';
    const GET_CHANNEL_API_ERROR = 'GET_CHANNEL_API_ERROR';
    const GET_BULK_ACCOUNT_STATUSES_API_ERROR = 'GET_BULK_ACCOUNT_STATUSES_API_ERROR';
    const RESEND_VERIFICATION_EMAIL_ERROR = 'RESEND_VERIFICATION_EMAIL_ERROR';
    const UNEXPECTED_API_RESPONSE_ERROR = 'UNEXPECTED_API_RESPONSE_ERROR';
    const UNKNOWN = 'UNKNOWN';


}
