<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CreativePersistenceType
{
    const NOT_PERSISTENT = 'NOT_PERSISTENT';
    const PERSISTENT_AND_EXCLUDE_NONE = 'PERSISTENT_AND_EXCLUDE_NONE';
    const PERSISTENT_AND_EXCLUDE_DISPLAY = 'PERSISTENT_AND_EXCLUDE_DISPLAY';
    const PERSISTENT_AND_EXCLUDE_VIDEO = 'PERSISTENT_AND_EXCLUDE_VIDEO';
    const PERSISTENT_AND_EXCLUDE_ALL = 'PERSISTENT_AND_EXCLUDE_ALL';


}
