<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CustomTargetingErrorReason
{
    const KEY_NOT_FOUND = 'KEY_NOT_FOUND';
    const KEY_COUNT_TOO_LARGE = 'KEY_COUNT_TOO_LARGE';
    const KEY_NAME_DUPLICATE = 'KEY_NAME_DUPLICATE';
    const KEY_NAME_EMPTY = 'KEY_NAME_EMPTY';
    const KEY_NAME_INVALID_LENGTH = 'KEY_NAME_INVALID_LENGTH';
    const KEY_NAME_INVALID_CHARS = 'KEY_NAME_INVALID_CHARS';
    const KEY_NAME_RESERVED = 'KEY_NAME_RESERVED';
    const KEY_DISPLAY_NAME_INVALID_LENGTH = 'KEY_DISPLAY_NAME_INVALID_LENGTH';
    const VALUE_NOT_FOUND = 'VALUE_NOT_FOUND';
    const GET_VALUES_BY_STATEMENT_MUST_CONTAIN_KEY_ID = 'GET_VALUES_BY_STATEMENT_MUST_CONTAIN_KEY_ID';
    const VALUE_COUNT_FOR_KEY_TOO_LARGE = 'VALUE_COUNT_FOR_KEY_TOO_LARGE';
    const VALUE_NAME_DUPLICATE = 'VALUE_NAME_DUPLICATE';
    const VALUE_NAME_EMPTY = 'VALUE_NAME_EMPTY';
    const VALUE_NAME_INVALID_LENGTH = 'VALUE_NAME_INVALID_LENGTH';
    const VALUE_NAME_INVALID_CHARS = 'VALUE_NAME_INVALID_CHARS';
    const VALUE_DISPLAY_NAME_INVALID_LENGTH = 'VALUE_DISPLAY_NAME_INVALID_LENGTH';
    const VALUE_MATCH_TYPE_NOT_ALLOWED = 'VALUE_MATCH_TYPE_NOT_ALLOWED';
    const VALUE_MATCH_TYPE_NOT_EXACT_FOR_PREDEFINED_KEY = 'VALUE_MATCH_TYPE_NOT_EXACT_FOR_PREDEFINED_KEY';
    const SUFFIX_MATCH_TYPE_NOT_ALLOWED = 'SUFFIX_MATCH_TYPE_NOT_ALLOWED';
    const CONTAINS_MATCH_TYPE_NOT_ALLOWED = 'CONTAINS_MATCH_TYPE_NOT_ALLOWED';
    const KEY_WITH_MISSING_VALUES = 'KEY_WITH_MISSING_VALUES';
    const CANNOT_OR_DIFFERENT_KEYS = 'CANNOT_OR_DIFFERENT_KEYS';
    const INVALID_TARGETING_EXPRESSION = 'INVALID_TARGETING_EXPRESSION';
    const DELETED_KEY_CANNOT_BE_USED_FOR_TARGETING = 'DELETED_KEY_CANNOT_BE_USED_FOR_TARGETING';
    const DELETED_VALUE_CANNOT_BE_USED_FOR_TARGETING = 'DELETED_VALUE_CANNOT_BE_USED_FOR_TARGETING';
    const VIDEO_BROWSE_BY_KEY_CANNOT_BE_USED_FOR_CUSTOM_TARGETING = 'VIDEO_BROWSE_BY_KEY_CANNOT_BE_USED_FOR_CUSTOM_TARGETING';
    const CANNOT_DELETE_CUSTOM_KEY_USED_IN_CONTENT_METADATA_MAPPING = 'CANNOT_DELETE_CUSTOM_KEY_USED_IN_CONTENT_METADATA_MAPPING';
    const CANNOT_DELETE_CUSTOM_VALUE_USED_IN_CONTENT_METADATA_MAPPING = 'CANNOT_DELETE_CUSTOM_VALUE_USED_IN_CONTENT_METADATA_MAPPING';
    const CANNOT_DELETE_CUSTOM_KEY_USED_IN_PARTNER_ASSIGNMENT_TARGETING = 'CANNOT_DELETE_CUSTOM_KEY_USED_IN_PARTNER_ASSIGNMENT_TARGETING';
    const CANNOT_DELETE_CUSTOM_VALUE_USED_IN_PARTNER_ASSIGNMENT_TARGETING = 'CANNOT_DELETE_CUSTOM_VALUE_USED_IN_PARTNER_ASSIGNMENT_TARGETING';
    const CANNOT_TARGET_AUDIENCE_SEGMENT = 'CANNOT_TARGET_AUDIENCE_SEGMENT';
    const CANNOT_TARGET_INACTIVE_AUDIENCE_SEGMENT = 'CANNOT_TARGET_INACTIVE_AUDIENCE_SEGMENT';
    const INVALID_AUDIENCE_SEGMENTS = 'INVALID_AUDIENCE_SEGMENTS';
    const ONLY_APPROVED_AUDIENCE_SEGMENTS_CAN_BE_TARGETED = 'ONLY_APPROVED_AUDIENCE_SEGMENTS_CAN_BE_TARGETED';
    const UNKNOWN = 'UNKNOWN';


}
