<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class EntityLimitReachedErrorReason
{
    const CUSTOM_TARGETING_VALUES_LIMIT_REACHED = 'CUSTOM_TARGETING_VALUES_LIMIT_REACHED';
    const AD_EXCLUSION_RULES_LIMIT_REACHED = 'AD_EXCLUSION_RULES_LIMIT_REACHED';
    const FIRST_PARTY_AUDIENCE_SEGMENTS_LIMIT_REACHED = 'FIRST_PARTY_AUDIENCE_SEGMENTS_LIMIT_REACHED';
    const PLACEMENTS_LIMIT_REACHED = 'PLACEMENTS_LIMIT_REACHED';
    const LINE_ITEMS_LIMIT_REACHED = 'LINE_ITEMS_LIMIT_REACHED';
    const UNKNOWN = 'UNKNOWN';


}
