<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ExchangeRateErrorReason
{
    const INVALID_CURRENCY_CODE = 'INVALID_CURRENCY_CODE';
    const UNSUPPORTED_CURRENCY_CODE = 'UNSUPPORTED_CURRENCY_CODE';
    const CURRENCY_CODE_ALREADY_EXISTS = 'CURRENCY_CODE_ALREADY_EXISTS';
    const INVALID_EXCHANGE_RATE = 'INVALID_EXCHANGE_RATE';
    const EXCHANGE_RATE_NOT_FOUND = 'EXCHANGE_RATE_NOT_FOUND';
    const CANNOT_DELETE_EXCHANGE_RATE_WITH_ACTIVE_RATE_CARDS = 'CANNOT_DELETE_EXCHANGE_RATE_WITH_ACTIVE_RATE_CARDS';
    const UNKNOWN = 'UNKNOWN';


}
