<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class InventoryUnitSizesErrorReason
{
    const INVALID_SIZES = 'INVALID_SIZES';
    const INVALID_SIZE_FOR_PLATFORM = 'INVALID_SIZE_FOR_PLATFORM';
    const VIDEO_FEATURE_MISSING = 'VIDEO_FEATURE_MISSING';
    const VIDEO_MOBILE_LINE_ITEM_FEATURE_MISSING = 'VIDEO_MOBILE_LINE_ITEM_FEATURE_MISSING';
    const INVALID_SIZE_FOR_MASTER = 'INVALID_SIZE_FOR_MASTER';
    const INVALID_SIZE_FOR_COMPANION = 'INVALID_SIZE_FOR_COMPANION';
    const DUPLICATE_MASTER_SIZES = 'DUPLICATE_MASTER_SIZES';
    const ASPECT_RATIO_NOT_SUPPORTED = 'ASPECT_RATIO_NOT_SUPPORTED';
    const VIDEO_COMPANIONS_NOT_SUPPORTED = 'VIDEO_COMPANIONS_NOT_SUPPORTED';
    const UNKNOWN = 'UNKNOWN';


}
