<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class OrderErrorReason
{
    const UPDATE_CANCELED_ORDER_NOT_ALLOWED = 'UPDATE_CANCELED_ORDER_NOT_ALLOWED';
    const UPDATE_PENDING_APPROVAL_ORDER_NOT_ALLOWED = 'UPDATE_PENDING_APPROVAL_ORDER_NOT_ALLOWED';
    const UPDATE_ARCHIVED_ORDER_NOT_ALLOWED = 'UPDATE_ARCHIVED_ORDER_NOT_ALLOWED';
    const CANNOT_MODIFY_PROPOSAL_ID = 'CANNOT_MODIFY_PROPOSAL_ID';
    const PRIMARY_USER_REQUIRED = 'PRIMARY_USER_REQUIRED';
    const PRIMARY_USER_CANNOT_BE_SECONDARY = 'PRIMARY_USER_CANNOT_BE_SECONDARY';
    const ORDER_TEAM_NOT_ASSOCIATED_WITH_ADVERTISER = 'ORDER_TEAM_NOT_ASSOCIATED_WITH_ADVERTISER';
    const USER_NOT_ON_ORDERS_TEAMS = 'USER_NOT_ON_ORDERS_TEAMS';
    const AGENCY_NOT_ON_ORDERS_TEAMS = 'AGENCY_NOT_ON_ORDERS_TEAMS';
    const INVALID_FIELDS_SET_FOR_NON_PROGRAMMATIC_ORDER = 'INVALID_FIELDS_SET_FOR_NON_PROGRAMMATIC_ORDER';
    const UNKNOWN = 'UNKNOWN';


}
