<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProgrammaticErrorReason
{
    const AUDIENCE_EXTENSION_NOT_SUPPORTED = 'AUDIENCE_EXTENSION_NOT_SUPPORTED';
    const AUTO_EXTENSION_DAYS_NOT_SUPPORTED = 'AUTO_EXTENSION_DAYS_NOT_SUPPORTED';
    const VIDEO_NOT_SUPPORTED = 'VIDEO_NOT_SUPPORTED';
    const ROADBLOCKING_NOT_SUPPORTED = 'ROADBLOCKING_NOT_SUPPORTED';
    const INVALID_CREATIVE_ROTATION = 'INVALID_CREATIVE_ROTATION';
    const INVALID_LINE_ITEM_TYPE = 'INVALID_LINE_ITEM_TYPE';
    const INVALID_COST_TYPE = 'INVALID_COST_TYPE';
    const SIZE_NOT_SUPPORTED = 'SIZE_NOT_SUPPORTED';
    const ZERO_COST_PER_UNIT_NOT_SUPPORTED = 'ZERO_COST_PER_UNIT_NOT_SUPPORTED';
    const CANNOT_UPDATE_FIELD_FOR_APPROVED_LINE_ITEMS = 'CANNOT_UPDATE_FIELD_FOR_APPROVED_LINE_ITEMS';
    const CANNOT_CREATE_LINE_ITEM_FOR_APPROVED_ORDER = 'CANNOT_CREATE_LINE_ITEM_FOR_APPROVED_ORDER';
    const CANNOT_UPDATE_BACKFILL_WEB_PROPERTY_FOR_APPROVED_LINE_ITEMS = 'CANNOT_UPDATE_BACKFILL_WEB_PROPERTY_FOR_APPROVED_LINE_ITEMS';
    const COST_PER_UNIT_TOO_LOW = 'COST_PER_UNIT_TOO_LOW';
    const UNKNOWN = 'UNKNOWN';


}
