<?php

namespace Google\AdsApi\Dfp\v201711;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ReconciliationImportErrorReason
{
    const MISSING_EDITABLE_COLUMN = 'MISSING_EDITABLE_COLUMN';
    const INCONSISTENT_IMPORT_COLUMNS = 'INCONSISTENT_IMPORT_COLUMNS';
    const COLUMN_CONVERSION_TYPE_ERROR = 'COLUMN_CONVERSION_TYPE_ERROR';
    const INCONSISTENT_COLUMNS_COUNT = 'INCONSISTENT_COLUMNS_COUNT';
    const IMPORT_INTERNAL_ERROR = 'IMPORT_INTERNAL_ERROR';
    const UNKNOWN = 'UNKNOWN';


}
