<?php

namespace Google\AdsApi\Dfp\v201602;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class GrpSettingsErrorReason
{
    const __default = 'INVALID_AGE_RANGE';
    const INVALID_AGE_RANGE = 'INVALID_AGE_RANGE';
    const LINE_ITEM_ENVIRONMENT_TYPE_NOT_SUPPORTED = 'LINE_ITEM_ENVIRONMENT_TYPE_NOT_SUPPORTED';
    const LINE_ITEM_TYPE_NOT_SUPPORTED = 'LINE_ITEM_TYPE_NOT_SUPPORTED';
    const CANNOT_SPECIFY_GENDER_FOR_GIVEN_AGE_RANGE = 'CANNOT_SPECIFY_GENDER_FOR_GIVEN_AGE_RANGE';
    const INVALID_MIN_AGE = 'INVALID_MIN_AGE';
    const INVALID_MAX_AGE = 'INVALID_MAX_AGE';
    const CANNOT_DISABLE_GRP_AFTER_ENABLING = 'CANNOT_DISABLE_GRP_AFTER_ENABLING';
    const CANNOT_CHANGE_GRP_PROVIDERS = 'CANNOT_CHANGE_GRP_PROVIDERS';
    const CANNOT_CHANGE_TARGET_DEMOG_AFTER_ACTIVATION = 'CANNOT_CHANGE_TARGET_DEMOG_AFTER_ACTIVATION';
    const DEMOG_GOAL_NOT_SUPPORTED = 'DEMOG_GOAL_NOT_SUPPORTED';
    const IMPRESSION_GOAL_NOT_ENOUGH = 'IMPRESSION_GOAL_NOT_ENOUGH';
    const CANNOT_SET_DEMOG_GOAL = 'CANNOT_SET_DEMOG_GOAL';
    const CANNOT_REMOVE_DEMOG_GOAL = 'CANNOT_REMOVE_DEMOG_GOAL';
    const UNSUPPORTED_GEO_TARGETING = 'UNSUPPORTED_GEO_TARGETING';
    const UNKNOWN = 'UNKNOWN';


}
