<?php

namespace Google\AdsApi\Dfp\v201602;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class InventoryUnitPartnerAssociationErrorReason
{
    const __default = 'ANCESTOR_AD_UNIT_HAS_PARTNER_ASSOCIATION';
    const ANCESTOR_AD_UNIT_HAS_PARTNER_ASSOCIATION = 'ANCESTOR_AD_UNIT_HAS_PARTNER_ASSOCIATION';
    const DESCENDANT_AD_UNIT_HAS_PARTNER_ASSOCIATION = 'DESCENDANT_AD_UNIT_HAS_PARTNER_ASSOCIATION';
    const NO_PARTNER_CATCH_ALL = 'NO_PARTNER_CATCH_ALL';
    const UNKNOWN = 'UNKNOWN';


}
