<?php

namespace Google\AdsApi\Dfp\v201602;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProposalLineItemActionErrorReason
{
    const __default = 'NOT_APPLICABLE';
    const NOT_APPLICABLE = 'NOT_APPLICABLE';
    const PROPOSAL_NOT_EDITABLE = 'PROPOSAL_NOT_EDITABLE';
    const CANNOT_SELECTIVELY_ARCHIVE_PROPOSAL_LINE_ITEMS_FROM_MANDATORY_PRODUCTS = 'CANNOT_SELECTIVELY_ARCHIVE_PROPOSAL_LINE_ITEMS_FROM_MANDATORY_PRODUCTS';
    const CANNOT_SELECTIVELY_UNARCHIVE_PROPOSAL_LINE_ITEMS_FROM_MANDATORY_PRODUCTS = 'CANNOT_SELECTIVELY_UNARCHIVE_PROPOSAL_LINE_ITEMS_FROM_MANDATORY_PRODUCTS';
    const UNKNOWN = 'UNKNOWN';


}
