<?php

namespace Google\AdsApi\Dfp\v201608;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class GenericTargetingErrorReason
{
    const __default = 'CONFLICTING_INCLUSION_OR_EXCLUSION_OF_SIBLINGS';
    const CONFLICTING_INCLUSION_OR_EXCLUSION_OF_SIBLINGS = 'CONFLICTING_INCLUSION_OR_EXCLUSION_OF_SIBLINGS';
    const INCLUDING_DESCENDANTS_OF_EXCLUDED_CRITERIA = 'INCLUDING_DESCENDANTS_OF_EXCLUDED_CRITERIA';
    const UNKNOWN = 'UNKNOWN';


}
