<?php

namespace Google\AdsApi\AdManager\v201908;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class AdjustmentErrorReason
{
    const START_DATE_TIME_IS_IN_PAST = 'START_DATE_TIME_IS_IN_PAST';
    const END_DATE_TIME_NOT_AFTER_START_TIME = 'END_DATE_TIME_NOT_AFTER_START_TIME';
    const END_DATE_TIME_TOO_LATE = 'END_DATE_TIME_TOO_LATE';
    const HISTORICAL_DATE_RANGE_INVALID = 'HISTORICAL_DATE_RANGE_INVALID';
    const HISTORICAL_START_DATE_TIME_IS_TOO_FAR_IN_PAST = 'HISTORICAL_START_DATE_TIME_IS_TOO_FAR_IN_PAST';
    const HISTORICAL_START_DATE_TIME_IS_BEFORE_CREATION_OF_INVENTORY_UNIT = 'HISTORICAL_START_DATE_TIME_IS_BEFORE_CREATION_OF_INVENTORY_UNIT';
    const HISTORICAL_END_DATE_TIME_IS_NOT_IN_PAST = 'HISTORICAL_END_DATE_TIME_IS_NOT_IN_PAST';
    const HISTORICAL_END_DATE_TIME_NOT_AFTER_HISTORICAL_START_TIME = 'HISTORICAL_END_DATE_TIME_NOT_AFTER_HISTORICAL_START_TIME';
    const HISTORICAL_DATE_RANGE_LENGTH_DOES_NOT_MATCH_FUTURE_DATE_RANGE_LENGTH = 'HISTORICAL_DATE_RANGE_LENGTH_DOES_NOT_MATCH_FUTURE_DATE_RANGE_LENGTH';
    const ADJUSTMENT_ALREADY_EXISTS_FOR_AD_UNIT_IN_DATE_RANGE = 'ADJUSTMENT_ALREADY_EXISTS_FOR_AD_UNIT_IN_DATE_RANGE';
    const INVALID_IMPRESSION_VOLUME = 'INVALID_IMPRESSION_VOLUME';
    const OVERRIDE_SIZE_SETS_MUST_BE_UNIQUE = 'OVERRIDE_SIZE_SETS_MUST_BE_UNIQUE';
    const OVERRIDE_SIZE_SET_SIZES_MUST_HAVE_THE_SAME_ENV_TYPE = 'OVERRIDE_SIZE_SET_SIZES_MUST_HAVE_THE_SAME_ENV_TYPE';
    const OVERRIDE_SIZE_SET_SIZES_MUST_MATCH_INVENTORY = 'OVERRIDE_SIZE_SET_SIZES_MUST_MATCH_INVENTORY';
    const INVALID_INVENTORY_UNIT_ID = 'INVALID_INVENTORY_UNIT_ID';
    const VIOLATES_CONSTRAINTS_OF_OVERLAPPING_ENTRIES = 'VIOLATES_CONSTRAINTS_OF_OVERLAPPING_ENTRIES';
    const INVALID_ADJUSTMENT_UPLOAD = 'INVALID_ADJUSTMENT_UPLOAD';
    const FUTURE_DATE_RANGE_MUST_BE_IN_WEEK_INCREMENTS = 'FUTURE_DATE_RANGE_MUST_BE_IN_WEEK_INCREMENTS';
    const BULK_UPLOAD_ADJUSTMENT_LIMIT_REACHED = 'BULK_UPLOAD_ADJUSTMENT_LIMIT_REACHED';
    const WEEKLY_MANUAL_ADJUSTMENTS_NOT_ALLOWED = 'WEEKLY_MANUAL_ADJUSTMENTS_NOT_ALLOWED';
    const TARGETING_OR_INVENTORY_UNIT_REQUIRED = 'TARGETING_OR_INVENTORY_UNIT_REQUIRED';
    const CANNOT_CHANGE_ADJUSTMENT_TARGET_TYPE = 'CANNOT_CHANGE_ADJUSTMENT_TARGET_TYPE';
    const OVERRIDES_NOT_ALLOWED_WITH_TARGETING = 'OVERRIDES_NOT_ALLOWED_WITH_TARGETING';
    const INVALID_TARGETING_EXPRESSION = 'INVALID_TARGETING_EXPRESSION';
    const ADJUSTMENT_NAME_MUST_BE_UNIQUE = 'ADJUSTMENT_NAME_MUST_BE_UNIQUE';
    const END_DATE_TIME_IS_IN_PAST = 'END_DATE_TIME_IS_IN_PAST';
    const HISTORICAL_TARGETING_REQUIRED = 'HISTORICAL_TARGETING_REQUIRED';
    const INVALID_HISTORICAL_TARGETING = 'INVALID_HISTORICAL_TARGETING';
    const AD_UNIT_REQUIRED = 'AD_UNIT_REQUIRED';
    const TARGETING_REQUIRED = 'TARGETING_REQUIRED';
    const UNKNOWN = 'UNKNOWN';


}
