<?php

namespace Google\AdsApi\AdManager\v201908;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class LiveStreamEventActionErrorReason
{
    const INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION';
    const IS_ARCHIVED = 'IS_ARCHIVED';
    const INVALID_SLATE_SETTING = 'INVALID_SLATE_SETTING';
    const SLATE_CREATIVE_NOT_TRANSCODED = 'SLATE_CREATIVE_NOT_TRANSCODED';
    const SLATE_CREATIVE_ARCHIVED = 'SLATE_CREATIVE_ARCHIVED';
    const CANNOT_ACTIVATE_IF_USING_INACTIVE_DAI_AUTHENTICATION_KEYS = 'CANNOT_ACTIVATE_IF_USING_INACTIVE_DAI_AUTHENTICATION_KEYS';
    const UNKNOWN = 'UNKNOWN';


}
