<?php

namespace Google\AdsApi\AdManager\v201908;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class PackageErrorReason
{
    const INVAILD_PRODUCT_PACKAGE = 'INVAILD_PRODUCT_PACKAGE';
    const INACTIVE_RATE_CARD = 'INACTIVE_RATE_CARD';
    const PRODUCT_PACKAGE_NOT_IN_RATE_CARD = 'PRODUCT_PACKAGE_NOT_IN_RATE_CARD';
    const HAS_NO_UNARCHIVED_PRODUCT_PACKAGE_ITEM = 'HAS_NO_UNARCHIVED_PRODUCT_PACKAGE_ITEM';
    const NOT_SAME_RATE_CARD = 'NOT_SAME_RATE_CARD';
    const UNKNOWN = 'UNKNOWN';


}
