<?php

namespace Google\AdsApi\AdManager\v202005;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CreativePolicyViolation
{
    const MALWARE_IN_CREATIVE = 'MALWARE_IN_CREATIVE';
    const MALWARE_IN_LANDING_PAGE = 'MALWARE_IN_LANDING_PAGE';
    const LEGALLY_BLOCKED_REDIRECT_URL = 'LEGALLY_BLOCKED_REDIRECT_URL';
    const MISREPRESENTATION_OF_PRODUCT = 'MISREPRESENTATION_OF_PRODUCT';
    const SELF_CLICKING_CREATIVE = 'SELF_CLICKING_CREATIVE';
    const GAMING_GOOGLE_NETWORK = 'GAMING_GOOGLE_NETWORK';
    const DYNAMIC_DNS = 'DYNAMIC_DNS';
    const CIRCUMVENTING_SYSTEMS = 'CIRCUMVENTING_SYSTEMS';
    const PHISHING = 'PHISHING';
    const DOWNLOAD_PROMPT_IN_CREATIVE = 'DOWNLOAD_PROMPT_IN_CREATIVE';
    const UNAUTHORIZED_COOKIE_DETECTED = 'UNAUTHORIZED_COOKIE_DETECTED';
    const TEMPORARY_PAUSE_FOR_VENDOR_INVESTIGATION = 'TEMPORARY_PAUSE_FOR_VENDOR_INVESTIGATION';
    const ABUSIVE_EXPERIENCE = 'ABUSIVE_EXPERIENCE';
    const TRICK_TO_CLICK = 'TRICK_TO_CLICK';
    const USE_OF_NON_WHITELISTED_OMID_VERIFICATION_SCRIPT = 'USE_OF_NON_WHITELISTED_OMID_VERIFICATION_SCRIPT';
    const MISUSE_OF_OMID_API = 'MISUSE_OF_OMID_API';
    const UNACCEPTABLE_HTML_AD = 'UNACCEPTABLE_HTML_AD';
    const UNKNOWN = 'UNKNOWN';


}
