<?php

namespace Google\AdsApi\AdManager\v202005;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class DimensionAttribute
{
    const LINE_ITEM_LABELS = 'LINE_ITEM_LABELS';
    const LINE_ITEM_LABEL_IDS = 'LINE_ITEM_LABEL_IDS';
    const LINE_ITEM_OPTIMIZABLE = 'LINE_ITEM_OPTIMIZABLE';
    const LINE_ITEM_DELIVERY_INDICATOR = 'LINE_ITEM_DELIVERY_INDICATOR';
    const LINE_ITEM_DELIVERY_PACING = 'LINE_ITEM_DELIVERY_PACING';
    const LINE_ITEM_FREQUENCY_CAP = 'LINE_ITEM_FREQUENCY_CAP';
    const LINE_ITEM_RECONCILIATION_STATUS = 'LINE_ITEM_RECONCILIATION_STATUS';
    const LINE_ITEM_LAST_RECONCILIATION_DATE_TIME = 'LINE_ITEM_LAST_RECONCILIATION_DATE_TIME';
    const ADVERTISER_EXTERNAL_ID = 'ADVERTISER_EXTERNAL_ID';
    const ADVERTISER_TYPE = 'ADVERTISER_TYPE';
    const ADVERTISER_CREDIT_STATUS = 'ADVERTISER_CREDIT_STATUS';
    const ADVERTISER_PRIMARY_CONTACT = 'ADVERTISER_PRIMARY_CONTACT';
    const ORDER_START_DATE_TIME = 'ORDER_START_DATE_TIME';
    const ORDER_END_DATE_TIME = 'ORDER_END_DATE_TIME';
    const ORDER_EXTERNAL_ID = 'ORDER_EXTERNAL_ID';
    const ORDER_PO_NUMBER = 'ORDER_PO_NUMBER';
    const ORDER_IS_PROGRAMMATIC = 'ORDER_IS_PROGRAMMATIC';
    const ORDER_AGENCY = 'ORDER_AGENCY';
    const ORDER_AGENCY_ID = 'ORDER_AGENCY_ID';
    const ORDER_LABELS = 'ORDER_LABELS';
    const ORDER_LABEL_IDS = 'ORDER_LABEL_IDS';
    const ORDER_TRAFFICKER = 'ORDER_TRAFFICKER';
    const ORDER_TRAFFICKER_ID = 'ORDER_TRAFFICKER_ID';
    const ORDER_SECONDARY_TRAFFICKERS = 'ORDER_SECONDARY_TRAFFICKERS';
    const ORDER_SALESPERSON = 'ORDER_SALESPERSON';
    const ORDER_SECONDARY_SALESPEOPLE = 'ORDER_SECONDARY_SALESPEOPLE';
    const ORDER_LIFETIME_IMPRESSIONS = 'ORDER_LIFETIME_IMPRESSIONS';
    const ORDER_LIFETIME_CLICKS = 'ORDER_LIFETIME_CLICKS';
    const ORDER_BOOKED_CPM = 'ORDER_BOOKED_CPM';
    const ORDER_BOOKED_CPC = 'ORDER_BOOKED_CPC';
    const LINE_ITEM_START_DATE_TIME = 'LINE_ITEM_START_DATE_TIME';
    const LINE_ITEM_END_DATE_TIME = 'LINE_ITEM_END_DATE_TIME';
    const LINE_ITEM_EXTERNAL_ID = 'LINE_ITEM_EXTERNAL_ID';
    const LINE_ITEM_COST_TYPE = 'LINE_ITEM_COST_TYPE';
    const LINE_ITEM_COST_PER_UNIT = 'LINE_ITEM_COST_PER_UNIT';
    const LINE_ITEM_CURRENCY_CODE = 'LINE_ITEM_CURRENCY_CODE';
    const LINE_ITEM_GOAL_QUANTITY = 'LINE_ITEM_GOAL_QUANTITY';
    const LINE_ITEM_SPONSORSHIP_GOAL_PERCENTAGE = 'LINE_ITEM_SPONSORSHIP_GOAL_PERCENTAGE';
    const LINE_ITEM_LIFETIME_IMPRESSIONS = 'LINE_ITEM_LIFETIME_IMPRESSIONS';
    const LINE_ITEM_LIFETIME_CLICKS = 'LINE_ITEM_LIFETIME_CLICKS';
    const LINE_ITEM_PRIORITY = 'LINE_ITEM_PRIORITY';
    const CREATIVE_OR_CREATIVE_SET = 'CREATIVE_OR_CREATIVE_SET';
    const MASTER_COMPANION_TYPE = 'MASTER_COMPANION_TYPE';
    const LINE_ITEM_CONTRACTED_QUANTITY = 'LINE_ITEM_CONTRACTED_QUANTITY';
    const LINE_ITEM_DISCOUNT = 'LINE_ITEM_DISCOUNT';
    const LINE_ITEM_NON_CPD_BOOKED_REVENUE = 'LINE_ITEM_NON_CPD_BOOKED_REVENUE';
    const ADVERTISER_LABELS = 'ADVERTISER_LABELS';
    const ADVERTISER_LABEL_IDS = 'ADVERTISER_LABEL_IDS';
    const CREATIVE_CLICK_THROUGH_URL = 'CREATIVE_CLICK_THROUGH_URL';
    const CREATIVE_SSL_SCAN_RESULT = 'CREATIVE_SSL_SCAN_RESULT';
    const CREATIVE_SSL_COMPLIANCE_OVERRIDE = 'CREATIVE_SSL_COMPLIANCE_OVERRIDE';
    const LINE_ITEM_CREATIVE_START_DATE = 'LINE_ITEM_CREATIVE_START_DATE';
    const LINE_ITEM_CREATIVE_END_DATE = 'LINE_ITEM_CREATIVE_END_DATE';
    const CONTENT_CMS_NAME = 'CONTENT_CMS_NAME';
    const CONTENT_CMS_VIDEO_ID = 'CONTENT_CMS_VIDEO_ID';
    const AD_UNIT_CODE = 'AD_UNIT_CODE';


}
