<?php

namespace Google\AdsApi\AdManager\v202005;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ProposalLineItemMakegoodErrorReason
{
    const ORIGINAL_ALREADY_HAS_MAKEGOOD = 'ORIGINAL_ALREADY_HAS_MAKEGOOD';
    const ORIGINAL_IS_MAKEGOOD = 'ORIGINAL_IS_MAKEGOOD';
    const ORIGINAL_NOT_YET_SOLD = 'ORIGINAL_NOT_YET_SOLD';
    const LINE_ITEM_IS_NOT_STANDARD = 'LINE_ITEM_IS_NOT_STANDARD';
    const LINE_ITEM_IS_NOT_CPM = 'LINE_ITEM_IS_NOT_CPM';
    const ORIGINAL_TOO_FAR_IN_PAST = 'ORIGINAL_TOO_FAR_IN_PAST';
    const RATE_DIFFERENT_THAN_ORIGINAL = 'RATE_DIFFERENT_THAN_ORIGINAL';
    const UNITS_MORE_THAN_ORIGINAL = 'UNITS_MORE_THAN_ORIGINAL';
    const MAKEGOODS_NOT_SUPPORTED_FOR_NON_DV360_BUYERS = 'MAKEGOODS_NOT_SUPPORTED_FOR_NON_DV360_BUYERS';
    const UNKNOWN = 'UNKNOWN';


}
