<?php

namespace Google\AdsApi\AdManager\v202005;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class SamErrorType
{
    const INTERNAL_ERROR = 'INTERNAL_ERROR';
    const AD_REQUEST_ERROR = 'AD_REQUEST_ERROR';
    const VAST_PARSE_ERROR = 'VAST_PARSE_ERROR';
    const UNSUPPORTED_AD_SYSTEM = 'UNSUPPORTED_AD_SYSTEM';
    const CANNOT_FIND_UNIQUE_TRANSCODE_ID = 'CANNOT_FIND_UNIQUE_TRANSCODE_ID';
    const CANNOT_FIND_MEDIA_FILE_PATH = 'CANNOT_FIND_MEDIA_FILE_PATH';
    const MISSING_INLINE_ELEMENTS = 'MISSING_INLINE_ELEMENTS';
    const MAX_WRAPPER_DEPTH_REACHED = 'MAX_WRAPPER_DEPTH_REACHED';
    const INVALID_AD_SEQUENCE_NUMBER = 'INVALID_AD_SEQUENCE_NUMBER';
    const FAILED_PING = 'FAILED_PING';
    const AD_TAG_PARSE_ERROR = 'AD_TAG_PARSE_ERROR';
    const VMAP_PARSE_ERROR = 'VMAP_PARSE_ERROR';
    const INVALID_VMAP_RESPONSE = 'INVALID_VMAP_RESPONSE';
    const NO_AD_BREAKS_IN_VMAP = 'NO_AD_BREAKS_IN_VMAP';
    const CUSTOM_AD_SOURCE_IN_VMAP = 'CUSTOM_AD_SOURCE_IN_VMAP';
    const AD_BREAK_TYPE_NOT_SUPPORTED = 'AD_BREAK_TYPE_NOT_SUPPORTED';
    const NEITHER_AD_SOURCE_NOR_TRACKING = 'NEITHER_AD_SOURCE_NOR_TRACKING';
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    const AD_POD_DROPPED_TO_MANY_AD_PODS = 'AD_POD_DROPPED_TO_MANY_AD_PODS';
    const AD_POD_DROPPED_EMPTY_ADS = 'AD_POD_DROPPED_EMPTY_ADS';
    const AD_BREAK_WITHOUT_AD_POD = 'AD_BREAK_WITHOUT_AD_POD';
    const TRANSCODING_IN_PROGRESS = 'TRANSCODING_IN_PROGRESS';
    const UNSUPPORTED_VAST_VERSION = 'UNSUPPORTED_VAST_VERSION';
    const AD_POD_DROPPED_BUMPER_ERROR = 'AD_POD_DROPPED_BUMPER_ERROR';
    const NO_VALID_MEDIAFILES_FOUND = 'NO_VALID_MEDIAFILES_FOUND';
    const EXCEEDS_MAX_FILLER = 'EXCEEDS_MAX_FILLER';
    const SKIPPABLE_AD_NOT_SUPPORTED = 'SKIPPABLE_AD_NOT_SUPPORTED';
    const AD_REQUEST_TIMEOUT = 'AD_REQUEST_TIMEOUT';
    const UNKNOWN = 'UNKNOWN';


}
