<?php

namespace Google\AdsApi\AdManager\v202005;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class VolumeTimeSeriesRequestErrorReason
{
    const NO_VOLUME_SETTINGS_PROVIDED = 'NO_VOLUME_SETTINGS_PROVIDED';
    const MULTIPLE_VOLUME_SETTINGS_PROVIDED = 'MULTIPLE_VOLUME_SETTINGS_PROVIDED';
    const PARENT_SEGMENT_TARGETING_OPTION_USED_OUTSIDE_OF_ADJUSTMENT_CONTEXT = 'PARENT_SEGMENT_TARGETING_OPTION_USED_OUTSIDE_OF_ADJUSTMENT_CONTEXT';
    const UNKNOWN = 'UNKNOWN';


}
