<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class AdCustomizerErrorReason
{
    const __default = 'COUNTDOWN_INVALID_DATE_FORMAT';
    const COUNTDOWN_INVALID_DATE_FORMAT = 'COUNTDOWN_INVALID_DATE_FORMAT';
    const COUNTDOWN_DATE_IN_PAST = 'COUNTDOWN_DATE_IN_PAST';
    const COUNTDOWN_INVALID_LOCALE = 'COUNTDOWN_INVALID_LOCALE';
    const COUNTDOWN_INVALID_START_DAYS_BEFORE = 'COUNTDOWN_INVALID_START_DAYS_BEFORE';


}
