<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class AdExtensionErrorReason
{
    const __default = 'ACCOUNT_DELETED';
    const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
    const AD_EXTENSION_NO_LONGER_ACTIVE = 'AD_EXTENSION_NO_LONGER_ACTIVE';
    const CANNOT_HAVE_MULTIPLE_LOCATION_SYNC_EXTENSIONS_PER_CAMPAIGN = 'CANNOT_HAVE_MULTIPLE_LOCATION_SYNC_EXTENSIONS_PER_CAMPAIGN';
    const CANNOT_HAVE_MULTIPLE_MOBILE_EXTENSIONS_PER_CAMPAIGN = 'CANNOT_HAVE_MULTIPLE_MOBILE_EXTENSIONS_PER_CAMPAIGN';
    const CANNOT_HAVE_MULTIPLE_PRODUCT_EXTENSIONS_PER_CAMPAIGN = 'CANNOT_HAVE_MULTIPLE_PRODUCT_EXTENSIONS_PER_CAMPAIGN';
    const CANNOT_HAVE_MULTIPLE_SITELINKS_EXTENSIONS_PER_CAMPAIGN = 'CANNOT_HAVE_MULTIPLE_SITELINKS_EXTENSIONS_PER_CAMPAIGN';
    const CANNOT_HAVE_MULTIPLE_IN_APP_LINK_EXTENSIONS_PER_CAMPAIGN_PER_APPSTORE = 'CANNOT_HAVE_MULTIPLE_IN_APP_LINK_EXTENSIONS_PER_CAMPAIGN_PER_APPSTORE';
    const INVALID_ADEXTENSION_TYPE = 'INVALID_ADEXTENSION_TYPE';
    const INVALID_AUTH_TOKEN_FOR_EMAIL = 'INVALID_AUTH_TOKEN_FOR_EMAIL';
    const INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE';
    const INVALID_DOMESTIC_PHONE_NUMBER_FORMAT = 'INVALID_DOMESTIC_PHONE_NUMBER_FORMAT';
    const INVALID_DESTINATION_URL = 'INVALID_DESTINATION_URL';
    const INVALID_EMAIL = 'INVALID_EMAIL';
    const INVALID_ENCODED_LOCATION = 'INVALID_ENCODED_LOCATION';
    const INVALID_ENUM_CONDITION_OPERATOR = 'INVALID_ENUM_CONDITION_OPERATOR';
    const INVALID_ICON_DIMENSIONS = 'INVALID_ICON_DIMENSIONS';
    const INVALID_ID = 'INVALID_ID';
    const INVALID_IMAGE_DIMENSIONS = 'INVALID_IMAGE_DIMENSIONS';
    const INVALID_INPUT = 'INVALID_INPUT';
    const INVALID_LATITUDE = 'INVALID_LATITUDE';
    const INVALID_LONGITUDE = 'INVALID_LONGITUDE';
    const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';
    const INVALID_STRING_CONDITION_OPERATOR = 'INVALID_STRING_CONDITION_OPERATOR';
    const INVALID_TOLL_PHONE_NUMBER_FORMAT = 'INVALID_TOLL_PHONE_NUMBER_FORMAT';
    const MEDIA_DOES_NOT_BELONG_TO_ACCOUNT = 'MEDIA_DOES_NOT_BELONG_TO_ACCOUNT';
    const MEDIA_NOT_ICON_TYPE = 'MEDIA_NOT_ICON_TYPE';
    const MEDIA_NOT_IMAGE_TYPE = 'MEDIA_NOT_IMAGE_TYPE';
    const MISSING_ADVERTISER_NAME = 'MISSING_ADVERTISER_NAME';
    const MISSING_AUTH_TOKEN = 'MISSING_AUTH_TOKEN';
    const MISSING_COUNTRY_CODE = 'MISSING_COUNTRY_CODE';
    const MISSING_CITY_NAME = 'MISSING_CITY_NAME';
    const MISSING_EMAIL = 'MISSING_EMAIL';
    const MISSING_ENCODED_LOCATION = 'MISSING_ENCODED_LOCATION';
    const MISSING_CONDITION_OPERAND = 'MISSING_CONDITION_OPERAND';
    const MISSING_CONDITION_STRING_VALUE = 'MISSING_CONDITION_STRING_VALUE';
    const MISSING_POSTAL_CODE = 'MISSING_POSTAL_CODE';
    const MISSING_STREET_ADDRESS = 'MISSING_STREET_ADDRESS';
    const NUM_AND_GROUPS_OVER_LIMIT = 'NUM_AND_GROUPS_OVER_LIMIT';
    const NUM_CONDITIONS_OVER_LIMIT = 'NUM_CONDITIONS_OVER_LIMIT';
    const NUM_LOCATION_EXTENSIONS_OVER_LIMIT = 'NUM_LOCATION_EXTENSIONS_OVER_LIMIT';
    const NOT_AUTHORIZED_TO_CREATE_EXTENSION = 'NOT_AUTHORIZED_TO_CREATE_EXTENSION';
    const PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY = 'PHONE_NUMBER_NOT_SUPPORTED_FOR_COUNTRY';
    const DISALLOWED_NUMBER_TYPE = 'DISALLOWED_NUMBER_TYPE';
    const PREMIUM_RATE_NUMBER_NOT_ALLOWED = 'PREMIUM_RATE_NUMBER_NOT_ALLOWED';
    const TOO_LONG = 'TOO_LONG';
    const USER_NOT_PERMITTED_TO_CREATE_LBC_SYNC_LOCATION_EXTENSION = 'USER_NOT_PERMITTED_TO_CREATE_LBC_SYNC_LOCATION_EXTENSION';


}
