<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class BiddingTransitionErrorReason
{
    const __default = 'BID_TO_POSITION_ENABLED';
    const BID_TO_POSITION_ENABLED = 'BID_TO_POSITION_ENABLED';
    const BIDDING_STRATEGY_NOT_AVAILABLE_FOR_ACCOUNT_TYPE = 'BIDDING_STRATEGY_NOT_AVAILABLE_FOR_ACCOUNT_TYPE';
    const BUDGET_OPTIMIZER_IS_ENABLED = 'BUDGET_OPTIMIZER_IS_ENABLED';
    const CONVERSION_OPTIMIZER_IS_ENABLED = 'CONVERSION_OPTIMIZER_IS_ENABLED';
    const CONVERSION_TRACKING_NOT_ENABLED = 'CONVERSION_TRACKING_NOT_ENABLED';
    const CONVERSION_TRACKING_NOT_AVAILABLE_FOR_ACCOUNT_TYPE = 'CONVERSION_TRACKING_NOT_AVAILABLE_FOR_ACCOUNT_TYPE';
    const USE_POSITION_PREFERENCE_IN_MANUALCPC_INSTEAD_TO_DISABLE_POSITION_PREFERENCE = 'USE_POSITION_PREFERENCE_IN_MANUALCPC_INSTEAD_TO_DISABLE_POSITION_PREFERENCE';
    const INVALID_BID = 'INVALID_BID';
    const CANNOT_SET_EXPLICIT_BID = 'CANNOT_SET_EXPLICIT_BID';
    const EXPLICIT_BID_REQUIRED_FOR_TRANSITION = 'EXPLICIT_BID_REQUIRED_FOR_TRANSITION';
    const EXPLICIT_BID_TYPE_DOES_NOT_MATCH_CAMPAIGN_BIDDING_STRATEGY = 'EXPLICIT_BID_TYPE_DOES_NOT_MATCH_CAMPAIGN_BIDDING_STRATEGY';
    const MISSING_REQUIRED_BID = 'MISSING_REQUIRED_BID';
    const INVALID_STATUS = 'INVALID_STATUS';
    const IS_CPM_CAMPAIGN = 'IS_CPM_CAMPAIGN';
    const IS_PERCENT_CPA_CAMPAIGN = 'IS_PERCENT_CPA_CAMPAIGN';
    const NOT_THE_PREVIOUS_BIDDING_STRATEGY = 'NOT_THE_PREVIOUS_BIDDING_STRATEGY';
    const NOT_ENOUGH_CONVERSION_DATA = 'NOT_ENOUGH_CONVERSION_DATA';
    const NOT_ENOUGH_CONVERSIONS = 'NOT_ENOUGH_CONVERSIONS';
    const OPTED_IN_SEARCH = 'OPTED_IN_SEARCH';
    const PROXY_BIDDING_ON = 'PROXY_BIDDING_ON';
    const SITE_REMNANT_RESERVATION_ALLOWED = 'SITE_REMNANT_RESERVATION_ALLOWED';
    const TRANSITION_TO_ITSELF = 'TRANSITION_TO_ITSELF';
    const UNKNOWN_BIDDING_STRATEGY = 'UNKNOWN_BIDDING_STRATEGY';
    const UNSUPPORTED_TRANSITION = 'UNSUPPORTED_TRANSITION';
    const VCG_ENABLED = 'VCG_ENABLED';
    const BIDDING_TRANSITION_FAILED = 'BIDDING_TRANSITION_FAILED';
    const ACCELERATED_DELIVERY_NOT_SUPPORTED_FOR_BUDGET_OPTIMIZER = 'ACCELERATED_DELIVERY_NOT_SUPPORTED_FOR_BUDGET_OPTIMIZER';
    const HAS_ACTIVE_EXPERIMENT = 'HAS_ACTIVE_EXPERIMENT';
    const INCOMPATIBLE_WITH_CAMPAIGN_SETTING = 'INCOMPATIBLE_WITH_CAMPAIGN_SETTING';


}
