<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class BiddingStrategyErrorReason
{
    const __default = 'DUPLICATE_NAME';
    const DUPLICATE_NAME = 'DUPLICATE_NAME';
    const CANNOT_CHANGE_BIDDING_STRATEGY_TYPE = 'CANNOT_CHANGE_BIDDING_STRATEGY_TYPE';
    const CANNOT_REMOVE_ASSOCIATED_STRATEGY = 'CANNOT_REMOVE_ASSOCIATED_STRATEGY';
    const BIDDING_STRATEGY_NOT_SUPPORTED = 'BIDDING_STRATEGY_NOT_SUPPORTED';
    const UNKNOWN = 'UNKNOWN';


}
