<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class BulkMutateJobErrorReason
{
    const __default = 'CAN_RETURN_RESULT_FOR_ONLY_COMPLETED_JOBS';
    const CAN_RETURN_RESULT_FOR_ONLY_COMPLETED_JOBS = 'CAN_RETURN_RESULT_FOR_ONLY_COMPLETED_JOBS';
    const CAN_RETURN_RESULT_FOR_ONLY_ONE_JOB = 'CAN_RETURN_RESULT_FOR_ONLY_ONE_JOB';
    const CANNOT_UPDATE_JOB_ONCE_ALL_REQUEST_PARTS_ARE_RECEIVED = 'CANNOT_UPDATE_JOB_ONCE_ALL_REQUEST_PARTS_ARE_RECEIVED';
    const INVALID_SCOPING_ENTITY_TYPE = 'INVALID_SCOPING_ENTITY_TYPE';
    const MISSING_SCOPING_ENTITY_FOR_OPERATION_STREAM = 'MISSING_SCOPING_ENTITY_FOR_OPERATION_STREAM';
    const MORE_THAN_ONE_SCOPING_ENTITY_TYPE = 'MORE_THAN_ONE_SCOPING_ENTITY_TYPE';
    const PAYLOAD_STORE_UNAVAILABLE = 'PAYLOAD_STORE_UNAVAILABLE';
    const REQUEST_PART_IS_OUT_OF_ORDER = 'REQUEST_PART_IS_OUT_OF_ORDER';
    const TOO_MANY_OPERATION_STREAMS_IN_REQUEST_PART = 'TOO_MANY_OPERATION_STREAMS_IN_REQUEST_PART';
    const TOO_MANY_OPERATIONS_IN_JOB = 'TOO_MANY_OPERATIONS_IN_JOB';
    const TOO_MANY_OPERATIONS_IN_REQUEST_PART = 'TOO_MANY_OPERATIONS_IN_REQUEST_PART';
    const TOO_MANY_RESULTS_TO_STORE = 'TOO_MANY_RESULTS_TO_STORE';
    const TOO_MANY_SCOPING_ENTITIES = 'TOO_MANY_SCOPING_ENTITIES';
    const UNKNOWN = 'UNKNOWN';
    const LOST_RESULT = 'LOST_RESULT';
    const UNPROCESSED_RESULT = 'UNPROCESSED_RESULT';
    const BATCH_FAILURE = 'BATCH_FAILURE';
    const SERVICE_PROVIDED_NO_RESULT = 'SERVICE_PROVIDED_NO_RESULT';


}
