<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class CampaignAdExtensionErrorReason
{
    const __default = 'ADEXTENSION_NOT_UNDER_CAMPAIGN';
    const ADEXTENSION_NOT_UNDER_CAMPAIGN = 'ADEXTENSION_NOT_UNDER_CAMPAIGN';
    const CANNOT_ADD_REMOVED_CAMPAIGN_ADEXTENSION = 'CANNOT_ADD_REMOVED_CAMPAIGN_ADEXTENSION';
    const CANNOT_OPERATE_ON_REMOVED_CAMPAIGN_ADEXTENSION = 'CANNOT_OPERATE_ON_REMOVED_CAMPAIGN_ADEXTENSION';
    const INVALID_ADEXTENSION_ID = 'INVALID_ADEXTENSION_ID';
    const MISSING_ADEXTENSION_ID = 'MISSING_ADEXTENSION_ID';
    const MUST_USE_CONCRETE_ADEXTENSION = 'MUST_USE_CONCRETE_ADEXTENSION';
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';


}
