<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class CampaignCriterionErrorReason
{
    const __default = 'CONCRETE_TYPE_REQUIRED';
    const CONCRETE_TYPE_REQUIRED = 'CONCRETE_TYPE_REQUIRED';
    const INVALID_PLACEMENT_URL = 'INVALID_PLACEMENT_URL';
    const CANNOT_EXCLUDE_CRITERIA_TYPE = 'CANNOT_EXCLUDE_CRITERIA_TYPE';
    const CANNOT_TARGET_AND_EXCLUDE = 'CANNOT_TARGET_AND_EXCLUDE';
    const TOO_MANY_OPERATIONS = 'TOO_MANY_OPERATIONS';
    const OPERATOR_NOT_SUPPORTED_FOR_CRITERION_TYPE = 'OPERATOR_NOT_SUPPORTED_FOR_CRITERION_TYPE';
    const SHOPPING_CAMPAIGN_SALES_COUNTRY_NOT_SUPPORTED_FOR_SALES_CHANNEL = 'SHOPPING_CAMPAIGN_SALES_COUNTRY_NOT_SUPPORTED_FOR_SALES_CHANNEL';
    const UNKNOWN = 'UNKNOWN';
    const CANNOT_ADD_EXISTING_FIELD = 'CANNOT_ADD_EXISTING_FIELD';


}
