<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class DatabaseErrorReason
{
    const __default = 'CONCURRENT_MODIFICATION';
    const CONCURRENT_MODIFICATION = 'CONCURRENT_MODIFICATION';
    const PERMISSION_DENIED = 'PERMISSION_DENIED';
    const ACCESS_PROHIBITED = 'ACCESS_PROHIBITED';
    const CAMPAIGN_PRODUCT_NOT_SUPPORTED = 'CAMPAIGN_PRODUCT_NOT_SUPPORTED';
    const DUPLICATE_KEY = 'DUPLICATE_KEY';
    const DATABASE_ERROR = 'DATABASE_ERROR';
    const UNKNOWN = 'UNKNOWN';


}
