<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class DataErrorReason
{
    const __default = 'CANNOT_CREATE_TABLE_ENTRY';
    const CANNOT_CREATE_TABLE_ENTRY = 'CANNOT_CREATE_TABLE_ENTRY';
    const NO_TABLE_ENTRY_CLASS_FOR_VIEW_TYPE = 'NO_TABLE_ENTRY_CLASS_FOR_VIEW_TYPE';
    const TABLE_SERVICE_ERROR = 'TABLE_SERVICE_ERROR';


}
