<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class ExperimentErrorReason
{
    const __default = 'EXPERIMENT_DELTA_STATUS_NOT_SPECIFIED';
    const EXPERIMENT_DELTA_STATUS_NOT_SPECIFIED = 'EXPERIMENT_DELTA_STATUS_NOT_SPECIFIED';
    const EXPERIMENT_DELTA_STATUS_NOT_ALLOWED = 'EXPERIMENT_DELTA_STATUS_NOT_ALLOWED';
    const EXPERIMENT_STATUS_NOT_ALLOWED = 'EXPERIMENT_STATUS_NOT_ALLOWED';
    const EXPERIMENT_NOT_ALLOWED_FOR_BIDDING_STRATEGY = 'EXPERIMENT_NOT_ALLOWED_FOR_BIDDING_STRATEGY';
    const EXPERIMENT_NOT_ALLOWED_FOR_CRITERION_TYPE = 'EXPERIMENT_NOT_ALLOWED_FOR_CRITERION_TYPE';
    const EXPERIMENT_NOT_ACTIVE = 'EXPERIMENT_NOT_ACTIVE';
    const INVALID_EXPERIMENT_ID = 'INVALID_EXPERIMENT_ID';
    const EXPERIMENT_ID_NOT_SPECIFIED_WITH_SEGMENTATION_CRITERIA = 'EXPERIMENT_ID_NOT_SPECIFIED_WITH_SEGMENTATION_CRITERIA';
    const TOO_MANY_CHANGES_TO_EXPERIMENT = 'TOO_MANY_CHANGES_TO_EXPERIMENT';
    const EXPERIMENT_ERROR = 'EXPERIMENT_ERROR';


}
