<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class JobErrorReason
{
    const __default = 'DUPLICATE_JOB_KEY_FOR_CUSTOMER';
    const DUPLICATE_JOB_KEY_FOR_CUSTOMER = 'DUPLICATE_JOB_KEY_FOR_CUSTOMER';
    const JOB_TYPE_NOT_SUPPORTED = 'JOB_TYPE_NOT_SUPPORTED';
    const PREREQUISITE_JOB_FAILED = 'PREREQUISITE_JOB_FAILED';
    const SELECTOR_CANNOT_USE_BOTH_JOB_IDS_AND_JOB_KEYS = 'SELECTOR_CANNOT_USE_BOTH_JOB_IDS_AND_JOB_KEYS';
    const TOO_LATE_TO_CANCEL_JOB = 'TOO_LATE_TO_CANCEL_JOB';
    const TOO_MANY_PREREQUISITE_JOBS = 'TOO_MANY_PREREQUISITE_JOBS';
    const TOO_MANY_JOBS_IN_QUEUE = 'TOO_MANY_JOBS_IN_QUEUE';
    const USER_CANCELED_JOB = 'USER_CANCELED_JOB';
    const WORKFLOW_FAILURE = 'WORKFLOW_FAILURE';
    const UNKNOWN = 'UNKNOWN';


}
