<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class LocationCriterionServiceErrorReason
{
    const __default = 'REQUIRED_LOCATION_CRITERION_PREDICATE_MISSING';
    const REQUIRED_LOCATION_CRITERION_PREDICATE_MISSING = 'REQUIRED_LOCATION_CRITERION_PREDICATE_MISSING';
    const TOO_MANY_LOCATION_CRITERION_PREDICATES_SPECIFIED = 'TOO_MANY_LOCATION_CRITERION_PREDICATES_SPECIFIED';
    const INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE';
    const LOCATION_CRITERION_SERVICE_ERROR = 'LOCATION_CRITERION_SERVICE_ERROR';


}
