<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class OfflineConversionErrorReason
{
    const __default = 'UNPARSEABLE_GCLID';
    const UNPARSEABLE_GCLID = 'UNPARSEABLE_GCLID';
    const CONVERSION_PRECEDES_CLICK = 'CONVERSION_PRECEDES_CLICK';
    const FUTURE_CONVERSION_TIME = 'FUTURE_CONVERSION_TIME';
    const EXPIRED_CLICK = 'EXPIRED_CLICK';
    const TOO_RECENT_CLICK = 'TOO_RECENT_CLICK';
    const INVALID_CLICK = 'INVALID_CLICK';
    const UNAUTHORIZED_USER = 'UNAUTHORIZED_USER';
    const INVALID_CONVERSION_TYPE = 'INVALID_CONVERSION_TYPE';
    const CLICK_MISSING_CONVERSION_LABEL = 'CLICK_MISSING_CONVERSION_LABEL';
    const UNKNOWN = 'UNKNOWN';


}
