<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class PagingErrorReason
{
    const __default = 'START_INDEX_CANNOT_BE_NEGATIVE';
    const START_INDEX_CANNOT_BE_NEGATIVE = 'START_INDEX_CANNOT_BE_NEGATIVE';
    const NUMBER_OF_RESULTS_CANNOT_BE_NEGATIVE = 'NUMBER_OF_RESULTS_CANNOT_BE_NEGATIVE';
    const UNKNOWN = 'UNKNOWN';


}
