<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class SharedCriterionErrorReason
{
    const __default = 'EXCEEDS_CRITERIA_LIMIT';
    const EXCEEDS_CRITERIA_LIMIT = 'EXCEEDS_CRITERIA_LIMIT';
    const INCORRECT_CRITERION_TYPE = 'INCORRECT_CRITERION_TYPE';
    const CANNOT_TARGET_AND_EXCLUDE = 'CANNOT_TARGET_AND_EXCLUDE';
    const NEGATIVE_CRITERION_REQUIRED = 'NEGATIVE_CRITERION_REQUIRED';
    const UNKNOWN = 'UNKNOWN';


}
