<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class SharedSetErrorReason
{
    const __default = 'CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE';
    const CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE = 'CUSTOMER_CANNOT_CREATE_SHARED_SET_OF_THIS_TYPE';
    const DUPLICATE_NAME = 'DUPLICATE_NAME';
    const SHARED_SET_REMOVED = 'SHARED_SET_REMOVED';
    const SHARED_SET_IN_USE = 'SHARED_SET_IN_USE';
    const UNKNOWN = 'UNKNOWN';


}
