<?php

namespace Google\AdsApi\AdWords\v201601\cm;

class SizeLimitErrorReason
{
    const __default = 'REQUEST_SIZE_LIMIT_EXCEEDED';
    const REQUEST_SIZE_LIMIT_EXCEEDED = 'REQUEST_SIZE_LIMIT_EXCEEDED';
    const RESPONSE_SIZE_LIMIT_EXCEEDED = 'RESPONSE_SIZE_LIMIT_EXCEEDED';
    const INTERNAL_STORAGE_ERROR = 'INTERNAL_STORAGE_ERROR';
    const UNKNOWN = 'UNKNOWN';


}
