<?php

namespace Google\AdsApi\AdWords\v201603\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class CampaignErrorReason
{
    const __default = 'CANNOT_GO_BACK_TO_INCOMPLETE';
    const CANNOT_GO_BACK_TO_INCOMPLETE = 'CANNOT_GO_BACK_TO_INCOMPLETE';
    const CANNOT_SET_END_DATE_BEFORE_EXPERIMENT_END_DATE = 'CANNOT_SET_END_DATE_BEFORE_EXPERIMENT_END_DATE';
    const DUPLICATE_CAMPAIGN_NAME = 'DUPLICATE_CAMPAIGN_NAME';
    const INCOMPATIBLE_CAMPAIGN_FIELD = 'INCOMPATIBLE_CAMPAIGN_FIELD';
    const INVALID_CAMPAIGN_NAME = 'INVALID_CAMPAIGN_NAME';
    const INVALID_AD_SERVING_OPTIMIZATION_STATUS = 'INVALID_AD_SERVING_OPTIMIZATION_STATUS';
    const INVALID_TRACKING_URL = 'INVALID_TRACKING_URL';
    const CANNOT_SET_BOTH_TRACKING_URL_TEMPLATE_AND_TRACKING_SETTING = 'CANNOT_SET_BOTH_TRACKING_URL_TEMPLATE_AND_TRACKING_SETTING';
    const MAX_IMPRESSIONS_NOT_IN_RANGE = 'MAX_IMPRESSIONS_NOT_IN_RANGE';
    const TIME_UNIT_NOT_SUPPORTED = 'TIME_UNIT_NOT_SUPPORTED';
    const INVALID_OPERATION_IF_SERVING_STATUS_HAS_ENDED = 'INVALID_OPERATION_IF_SERVING_STATUS_HAS_ENDED';
    const BUDGET_CANNOT_BE_SHARED = 'BUDGET_CANNOT_BE_SHARED';
    const CAMPAIGN_CANNOT_USE_SHARED_BUDGET = 'CAMPAIGN_CANNOT_USE_SHARED_BUDGET';
    const CAMPAIGN_LABEL_DOES_NOT_EXIST = 'CAMPAIGN_LABEL_DOES_NOT_EXIST';
    const CAMPAIGN_LABEL_ALREADY_EXISTS = 'CAMPAIGN_LABEL_ALREADY_EXISTS';
    const MISSING_SHOPPING_SETTING = 'MISSING_SHOPPING_SETTING';
    const INVALID_SHOPPING_SALES_COUNTRY = 'INVALID_SHOPPING_SALES_COUNTRY';
    const ADVERTISING_CHANNEL_TYPE_NOT_AVAILABLE_FOR_ACCOUNT_TYPE = 'ADVERTISING_CHANNEL_TYPE_NOT_AVAILABLE_FOR_ACCOUNT_TYPE';
    const INVALID_ADVERTISING_CHANNEL_SUB_TYPE = 'INVALID_ADVERTISING_CHANNEL_SUB_TYPE';
    const UNKNOWN = 'UNKNOWN';


}
