<?php

namespace Google\AdsApi\AdWords\v201603\cm;


/**
 * This file was generated from WSDL. DO NOT EDIT.
 */
class ExperimentServiceErrorReason
{
    const __default = 'AFTER_MAXIMUM_ALLOWABLE_DATE';
    const AFTER_MAXIMUM_ALLOWABLE_DATE = 'AFTER_MAXIMUM_ALLOWABLE_DATE';
    const AOL_PARTNER_CAMPAIGNS_CANT_RUN_EXPERIMENTS = 'AOL_PARTNER_CAMPAIGNS_CANT_RUN_EXPERIMENTS';
    const CANNOT_CREATE_EXPERIMENT_FOR_BIDDING_STRATEGY = 'CANNOT_CREATE_EXPERIMENT_FOR_BIDDING_STRATEGY';
    const CANNOT_CREATE_EXPERIMENT_FOR_BIDDING_STRATEGY_FEATURE = 'CANNOT_CREATE_EXPERIMENT_FOR_BIDDING_STRATEGY_FEATURE';
    const CANNOT_SET_DATE_TO_PAST = 'CANNOT_SET_DATE_TO_PAST';
    const CANNOT_SET_END_DATE_WITHOUT_SETTING_START_DATE = 'CANNOT_SET_END_DATE_WITHOUT_SETTING_START_DATE';
    const CANNOT_USE_EXPERIMENT_WITH_SHARED_BUDGET = 'CANNOT_USE_EXPERIMENT_WITH_SHARED_BUDGET';
    const DATE_OUTSIDE_CAMPAIGN_DATE_RANGE = 'DATE_OUTSIDE_CAMPAIGN_DATE_RANGE';
    const EXPERIMENT_ALREADY_STARTED = 'EXPERIMENT_ALREADY_STARTED';
    const EXPERIMENT_ENDED = 'EXPERIMENT_ENDED';
    const EXPERIMENT_LIMIT_EXCEEDED = 'EXPERIMENT_LIMIT_EXCEEDED';
    const INVALID_EXPERIMENT_NAME = 'INVALID_EXPERIMENT_NAME';
    const INVALID_QUERY_PERCENTAGE = 'INVALID_QUERY_PERCENTAGE';
    const CANNOT_CHANGE_QUERY_PERCENTAGE_AFTER_EXPERIMENT_HAS_STARTED = 'CANNOT_CHANGE_QUERY_PERCENTAGE_AFTER_EXPERIMENT_HAS_STARTED';
    const INVALID_STATUS_UPDATE = 'INVALID_STATUS_UPDATE';
    const START_DATE_AFTER_END_DATE = 'START_DATE_AFTER_END_DATE';
    const NO_VALID_BUDGET = 'NO_VALID_BUDGET';
    const EXPERIMENT_NOT_ACTIVE = 'EXPERIMENT_NOT_ACTIVE';
    const EXPERIMENT_SERVICE_ERROR = 'EXPERIMENT_SERVICE_ERROR';


}
